### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#102]
We need to be able to release the artifacts via gradle.
Hibernate ORM already has a solution for this and we should aim to use the same approach.
Here's some of the files in ORM responsible for the release:

- https://github.com/hibernate/hibernate-orm/blob/master/release/release.gradle
- https://github.com/hibernate/hibernate-orm/blob/master/gradle/published-java-module.gradle
- https://github.com/hibernate/hibernate-orm/blob/master/gradle/publishing-repos.gradle
- https://github.com/hibernate/hibernate-orm/blob/master/gradle/publishing-pom.gradle

**Comment by DavideD** [comment]
I just learned that the release process on ORM is still in testing and might be something to fix in regards of the files I mentioned

**Comment by Sanne** [comment]
@DavideD @yrodiere only docs + javadocs are missing right?

Should we create a different issue and close this one ?

**Comment by gavinking** [comment]
@Sanne that is already issue #230.
