### ISSUE TITLE
Add support for Oracle

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1032]
Requires #1010 

https://vertx.io/docs/vertx-oracle-client/java/

**Comment by DavideD** [comment]
I've created a branch upstream `wip/oracle` to keep track of the progress:
https://github.com/hibernate/hibernate-reactive/tree/wip/oracle

It's not clean but it allows testing with Oracle like we do for the other databases:
```
./gradlew testDbOracle -Pdocker
```
A lot more tests than I expected are already working. I haven't looked into the failures yet but most seems related to the usual: queries, query parameters syntax and converting the result type from queries.

Cheers

**Comment by DavideD** [comment]
I've updated the branch and when using the latest snapshot we have 7 failures caused by the same 2 errors:
* `Error Msg = ORA-00932: inconsistent datatypes: expected - got BLOB `: I've already [created an issue for Vert.x](https://github.com/eclipse-vertx/vertx-sql-client/issues/1085).
* Inheritance and some other case where we have queries with `RETURNING ROWID INTO ?`. I will check this next week

**Comment by tsegismont** [comment]
@DavideD 7 failures out of the entire test suite? Sounds like good news!

**Comment by DavideD** [comment]
I think the other problem that it's missing is an issue with Vert.x: https://github.com/eclipse-vertx/vertx-sql-client/issues/1108

**Comment by hernael** [comment]
Hi @DavideD, a question: Having added this issue to the next milestone, means that it is possible have Oracle Support in the next hibernate-reactive version?

**Comment by gavinking** [comment]
Haaaay, that's a _really_ great question! I've lost track of where we're at on Oracle support.

**Comment by blafond** [comment]
The `vertx-oracle-client` is in the build, which we developed against... probably 4.2.1?

Still waiting on [#1108](https://github.com/eclipse-vertx/vertx-sql-client/issues/1108) which right now is targeted at 4.3.0 vertx-sql-client

**Comment by DavideD** [comment]
> Having added this issue to the next milestone, means that it is possible have Oracle Support in the next hibernate-reactive version

That's the plan but I need to rebase and review what we have so that I can document the limitations (see https://github.com/hibernate/hibernate-reactive/issues/1032#issuecomment-991155858).
