### ISSUE TITLE
Allow configuration via Vertx Pool

### ISSUE THREAD

**Issue by aguibert** [hibernate/hibernate-reactive#105]
Currently it is only possible to configure RX via URL. However, it would also be good to configure RX by passing in an `io.vertx.sqlclient.Pool` instance.

This would have 2 benefits:
 - It will allow the same Vertx Pool to be used by other components. For example, in Quarkus you can configure a Pool via a set of properties and inject the `Pool` into your application. This would allow the same underling pool to be used directly by the application and by RX.
 - It is consistent with non-reactive case where you can configure via `AvailableSettings.URL` or `AvailableSettings.DATASOURCE`

I propose we add a new `AvailableRxSettings` interface with the following:

```java
public interface AvailableRxSettings extends org.hibernate.cfg.AvailableSettings {

    String VERTX_POOL = "hibernate.rx.connection.vertx.pool";

    // Can add more reactive-specific settings as needed...

}
```

**Comment by gavinking** [comment]
@aguibert am I right in assuming that this is something you require in order to simplify Quarkus integration?

**Comment by emmanuelbernard** [comment]
> @aguibert am I right in assuming that this is something you require in order to simplify Quarkus integration?

That’s right.

**Comment by gavinking** [comment]
So do we need it in the *initial* release?

**Comment by emmanuelbernard** [comment]
> So do we need it in the *initial* release?

It would be much much better otherwise it’s more work on the extension, need some extra mapping of properties and of course double the pool usage for nothing

**Comment by gavinking** [comment]
Then we need a volunteer to work on it.

**Comment by emmanuelbernard** [comment]
@aguibert do you think you would have the bandwidth for this?

**Comment by aguibert** [comment]
Sorry, was on vacation yesterday. I had already done the work for this but forgot to link the PR to the issue: https://github.com/hibernate/hibernate-reactive/pull/110

It is merged now
