### ISSUE TITLE
Replace deprecated `ExpectedException.none()` with `Assert.assertThrow`

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1058]

**Comment by ReyhanPatria** [comment]
Hi! Is this for every test? I'd like to work on this if you'd assign me to it. Thanks!

**Comment by DavideD** [comment]
Thank you!
I did a quick search and I've found 6 tests:
```
hibernate-reactive-core/src/test/java/org/hibernate/reactive/IdentityGeneratorTypeForCockroachDBTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveMultitenantNoResolverTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/configuration/ReactiveConnectionPoolTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/configuration/JdbcUrlParserTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/DefaultPortTest.java
hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveStatelessProxyUpdateTest.java
```

It might be more.

Please, make sure to use this code template: https://github.com/hibernate/hibernate-ide-codestyles

The one for Hibernate ORM.

Thanks again

**Comment by ReyhanPatria** [comment]
@DavideD I'm having trouble setting up the development environment, is there a guide on this?

**Comment by DavideD** [comment]
We don't have a guide because we haven't had many contributors and it should be possible to import the project without any particular configuration.

I cannot help you  if you don't give some more details: which IDE are you using and what's the issue?

**Comment by DavideD** [comment]
> it should be possible to import the project without any particular configuration.

Maybe I'm a bit optimistic about  this. We use Intellij IDEA and it should work in it as long as you import it as a Gradle project.
Not sure about other IDE.

**Comment by ReyhanPatria** [comment]
I'm using IntelliJ as well, I was having trouble runnings the tests. Do I
have to install every type of database?

**Comment by ReyhanPatria** [comment]
I'm using Java 1.8, Gradle 6.9.1, and Docker 20.10.10

**Comment by DavideD** [comment]
By default, it won't start the containers automatically. 
You need to set a system property: `docker=true`

Or you can change the value in this file: https://github.com/hibernate/hibernate-reactive/blob/main/gradle.properties#L25
I've just created an issue to use docker as the default approach: https://github.com/hibernate/hibernate-reactive/issues/1060

Anyway, all the descriptions about starting containers for testing and how to run the tests for each database are in the readme: https://github.com/hibernate/hibernate-reactive#running-tests

Also here you will find the instruction to start the containers using podman/docker (if you want to start the manually): https://github.com/hibernate/hibernate-reactive/blob/main/podman.md

Replace `podman` with `docker` (or `sudo docker`) and it should work

**Comment by ReyhanPatria** [comment]
Thanks! It works now, it was my docker that had problems.

**Comment by DavideD** [comment]
> Thanks! It works now, it was my docker that had problems.

Great!
That's not unusual and actually why we haven't enabled it as the default profile so far.

**Comment by blafond** [comment]
@Davide took a crack at this one:  [1058](https://github.com/blafond/hibernate-reactive/commits/issue_1058) if you wanna have a look tomorrow

**Comment by DavideD** [comment]
Nice.
Now that I look at the changes I'm thinking that maybe we could make the method more generic.
Something like:
```
	@Test
	public void testWithSessionThrowsExceptionWithoutTenant(TestContext context) {
		test( context, assertThrown( HibernateException.class, getSessionFactory().withSession( this::selectCurrentDB ) )
				.thenAccept( exception -> Assertions.assertThat( exception.getMessage() ).contains( "no tenant identifier" ) ) );
	}

	/**
	 * Assert that the expected exception type is thrown.
	 * If the thrown exception is a {@link CompletionException}, then the cause will be tested.
	 *
	 * @return a {@link CompletionStage} with the expected exception thrown by the stage we were testing.
	 */
	private <T extends Throwable> CompletionStage<T> assertThrown(Class<T> expectedException, CompletionStage<?> stage) {
		return stage
				// Depending on the use case, the real exception could be wrapped in a CompletionException
				.handle( (v, e) -> e instanceof CompletionException ? e.getCause() : e )
				.thenApply( e -> {
					Assertions.assertThat( e ).isInstanceOf( expectedException );
					return (T) e;
				} );
	}
```

Because it returns the exception after having asserted the type, it's possible to add specific assertions for each test.
WDYT?

**Comment by blafond** [comment]
It looks pretty clean ... but I don't know if it's generic enough?

Would you want to elevate this method to a generic test class?

That specific class has Mutiny test cases as well as cases with `withTransaction`, `withStatelessTransaction`. 
Couldn't quite figure out a Mutiny version of it because `handle()` & `thenApply()` won't work?

Suggestions?

**Comment by DavideD** [comment]
> Would you want to elevate this method to a generic test class?

Sure, that was just a copy and paste of an experiment I made. The idea  is that it will replace the methods you have now in the class you've added (it should also be static).

**Comment by DavideD** [comment]
I haven't tested, but for Mutiny it should be something like:
```
	static <U extends Throwable> Uni<U> assertThrown(Class<U> expectedException, Uni<?> uni) {
		return uni.onItemOrFailure().transform( ( s, e )  -> {
			Assertions.assertThat( e ).isInstanceOf( expectedException );
			return (U) e;
		});
	}

```

**Comment by DavideD** [comment]
Merged
