### ISSUE TITLE
Test SqlConnectOptions creation from URL

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1059]
See [JdbcUrlParserTest](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/test/java/org/hibernate/reactive/configuration/JdbcUrlParserTest.java#L43)

We have a simple test for Postgres but the logic changes a lot based on the database selected.
We should make sure to test that we create the right `SqlConnectOptions` for each database.

This is the method that creates the SqlConnectOptions object: https://github.com/hibernate/hibernate-reactive/blob/cd8d50c851a2a3a528e77555c214fca20693a7a8/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java#L92

Relates to #864

**Comment by blafond** [comment]
Logged vertx issue to allow additional URL properties to be captured during parsing. [#1115](https://github.com/eclipse-vertx/vertx-sql-client/issues/1115)

**Comment by blafond** [comment]
@gavinking @DavideD 

So do we want HR users to be able to pass arbitrary properties on their URLs through the vertx sql clients?  Currently there's logic in vertx that is limiting the values being processed. (see [#1115](https://github.com/eclipse-vertx/vertx-sql-client/issues/1115))

Currently the vertx `SqlConnectOptions` URL parsing implementations are creating a `JsonObject` map of specific or common parameters.

 Couple examples
* [PgConnectionUriParser](https://github.com/eclipse-vertx/vertx-sql-client/blob/352e8da205598ffd9730ef36891dbc28ff544e53/vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java#L151)
* [DB2ConnectionUriParser](https://github.com/eclipse-vertx/vertx-sql-client/blob/352e8da205598ffd9730ef36891dbc28ff544e53/vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2ConnectionUriParser.java#L145)

The parsing logic is customized to the DB-specific SqlConnectOptions implementations to match the getters/setters for some common and specific parameters.

It shouldn't take a lot of work to free things up on the vertx side, but want to know that we need these changes on our side.

**Comment by gavinking** [comment]
> So do we want HR users to be able to pass arbitrary properties on their URLs through the vertx sql clients?

Well, I mean naïvely I would say yes.

I don't see why we need to protect the database from receiving connection properties. That's it's responsibility to safely handle, I would have thought.
