### ISSUE TITLE
Use UriPoolConfiguration as default SqlClientPoolConfiguration

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1081]
Hibernate Reactive uses [DefaultSqlClientPoolConfiguration](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java) as the default class to convert an url into a set of options to pass to Vert.x

The problem of this class is that it has a lot of custom code that's not easy to maintain.
I think we could use [UriPoolConfiguration](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/test/java/org/hibernate/reactive/UriPoolConfiguration.java) instead.

We need to add some tests to make sure that everything work consistently.

This issue is related to https://github.com/hibernate/hibernate-reactive/issues/1059

Actually, we should be able to use `SqlConnectOptions` and reduce the code needed: https://github.com/eclipse-vertx/vertx-sql-client/pull/1101

**Comment by gavinking** [comment]
@DavideD check #333 which has at least some overlap with this.

**Comment by DavideD** [comment]
Ah right, I've forgotten that one. Thanks

**Comment by DavideD** [comment]
Duplicate of #333

**Comment by blafond** [comment]
@gavinking @DavideD   I'd like some clarity on #1059 and it's relation to this issue.

#1059 is about changing our tests to leverage the vertx URI parsing and that makes sense.

[DefaultSqlClientPoolConfiguration](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java) is added in HR core as a Reactive Service in [ReactiveServiceRegistryBuilder](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/provider/ReactiveServiceRegistryBuilder.java#L387).  Using the logic in UriPoolConfiguration requires DB-specific Vertx dependencies and I'm not sure we would want to do that.

Thoughts or suggestions?

**Comment by DavideD** [comment]
#1059 Is about adding some tests for the version that we have right now. You shouldn't have to touch the implementation but you need to check that we create the correct SqlClientOptions object.

The reason it is related to #333 is that once #1059 is solved we will have tests to make sure that after the refactoring everything will still work the same

**Comment by blafond** [comment]
@DavideD pushed a test to my fork at [issue-1059](https://github.com/blafond/hibernate-reactive/commit/84614fd2a4dede61fdf85d57f6e6b9ff6c28bb77).

The documentation for the vertx clients show a little different URL construction than what's being used in our connection logic. They put **user info** first rather than **host & port**

For PG and MYSQL I can test with either the URL format from vertx client docs OR our HR URL.

For MSSQL and DB2, our HR URL fails.  The REGEX for PG, MySQL, MSSQL and DB2 used for vertx URL parsing seems almost identical. Can't yet figure out why MSSQL & DB2 fails.

**Comment by blafond** [comment]
see:  https://vertx.io/docs/vertx-db2-client/java/#_configuration for an example

**Comment by blafond** [comment]
A little more info....

Looking at each of the vertx parser frameworks, they handle **general** properties as specific/known props. Their 
**[PgConnectionUriParser](https://github.com/eclipse-vertx/vertx-sql-client/blob/e430bd8a25327854b35ab3f2e2bca2ea76b1207b/vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java#L198)** pluck specific configuration parameters and anything left over is put in KEY/VALUE properties map.  This map is used to populate the JsonObject .  However, when the JSON object is given to **[PgConnectOptionsConverter.fromJson()](https://github.com/eclipse-vertx/vertx-sql-client/blob/17719e5db4d305ebeb5f0feac40b11277f0bcd90/vertx-pg-client/src/main/generated/io/vertx/pgclient/PgConnectOptionsConverter.java#L20)** the method is only looking for additional **specific** properties.

So if we want to allow additional DB-specific URL property/value pairs, the Vertx clients would have to be individually modified.

**Comment by DavideD** [comment]
In the documentation we don't have examples of the URLs that we support but I think we mention that it's possible to use the JDBC URL format for each database. It seemed like a good format to use at the time because it was the same supported by ORM.

Vert.x SQL Client goes toward a different road though, and they use a format different than the JDBC one from the same database.

In the end, I think what we have to do is:
* if the URL starts with `jdbc:`, it should follow with the JDBC url format (it might differ from what Vert.x supports);
* If it starts with nothing, it should work with Vert.x as is;

@gavinking Does this make sense? I think Quarkus also supports the prefix `vertx:`, should we do the same?

About additional properties in the URL, we need to recognize them and pass them accordingly. So, if the url query string looks like:
```
?username=Davide&password=pwd001&whatever=something
```
We have to recognize `username` and `password` and pass the remaining properties to the driver. We don't care how the driver uses them. 

Maybe, passing all of them as a properties map has the same effect. I don't know, I haven't tried.

**Comment by DavideD** [comment]
By the way @blafond, this issue is closed. I think we should comment on #333 instead

**Comment by gavinking** [comment]
It makes sense and indeed I think if you try it you'll find that what you just described *already* works in HR, at least for postgres and MySQL.
