### ISSUE TITLE
Add unproxy() method to session

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#109]
As noticed by @gbadner the `fetch()` method currently features the semantics of `Hibernate.unproxy()` rather than the semantics of `Hibernate.initialize()` (i.e. it passes your callback a "naked" reference to the entity).

That's probably wrong, and we should change it. But if we do so, we should add an additional method with the semantics of `unproxy()`.

**Comment by gbadner** [comment]
I pushed a fix to `CascadeComplicatedTest`. Now `#testMergeTransient` passes.

**Comment by gavinking** [comment]
Done.
