### ISSUE TITLE
Find elements with a EntityGraph

### ISSUE THREAD

**Issue by tiagomistral** [hibernate/hibernate-reactive#1098]
Hello,

As long as I understand it's possible to find an element but it isn't possible to execute a criteria query with an EntityGraph.

Code:

    @Entity
    @Table
    @NamedEntityGraph(name = "graph.Author.books", 
        attributeNodes = @NamedAttributeNode("books"))
    @NamedQuery(name = "Author.listAll",
        query = "SELECT e FROM Author e")
     public class Author {
        @Id
        private Integer id;
    
        private String name;
    
        @OneToMany(mappedBy = "author", cascade = PERSIST)
        private Collection<Book> books = new ArrayList<>();

        ...constructors get/set...
    }

    @Path("/api")
    public class ResourceApi {

        @Inject
        Mutiny.Session mutinySession;

        @Inject
        Mutiny.SessionFactory mutinySessionFactory;

        @GET
        @Path("/author/{authorId}")
        public Uni<Author> findAuthor(@PathParam("authorId") Integer authorId) {
            EntityGraph<Author> entityGraph = mutinySession.getEntityGraph(Author.class, "graph.Author.books");
            return mutinySession.find(entityGraph, authorId);  // This works fine and use EntityGraph
        }

        @GET
        @Path("/authors")
        public Uni<Author> findAuthors() {
            EntityGraph<Author> entityGraph = mutinySession.getEntityGraph(Author.class, "graph.Author.books");
            CriteriaBuilder cb = this.mutinySessionFactory.getCriteriaBuilder();
            CriteriaQuery<Author> query = cb.createQuery(Author.class);
            Root<Author> root = query.from(Author.class);
            Query<Author> createQuery = mutinySession.createQuery(query);
            createQuery.setPlan(entityGraph);  // This is method is comment on Mutiny#Query class
            return createQuery.getResultList();
        }
    }

I also try to achieve this using the hits parameter on EntityGraph annotation

       @NamedQuery(name = "Author.listAll",
              query = "SELECT e FROM Author e", 
              hints = @QueryHint(name= "javax.persistence.fetchgraph", value = "graph.Author.books"))

There's any limitation to `setPlan` are comment?
There's any workaround to achieve this?

Best,

**Comment by DavideD** [comment]
I'm checking

**Comment by DavideD** [comment]
@gavinking Any particular reason this was commented? Or we simply haven't implemented it yet

**Comment by gavinking** [comment]
commented where?

**Comment by gavinking** [comment]
oic, in `Mutiny.Query`.

**Comment by gavinking** [comment]
The commit comment that blame shows me is:

> add disabled code for EntityGraph fetch plans with Query  ORM itself doesn't support query fetch plans properly, so don't expose this for now.  (If I did expose it, then the user would run into #39.)

**Comment by gavinking** [comment]
And #39 is fixed. Not sure about whatever limitation I found in core.

**Comment by DavideD** [comment]
I will write a test

**Comment by DavideD** [comment]
@tiagomistral As a workaround, for now I wouldn't use entityGraphs but you can do a fetch with Criteria:
```
		final Root<Author> root = query.from( Author.class );
		root.fetch( "books" );
		Mutiny.Query<Author> createQuery = mutinySession.createQuery( query );
```

**Comment by tiagomistral** [comment]
Thanks for the reply @DavideD , I already use that for complex queries but that doesn't use the `@EntityGraph` :/

**Comment by gavinking** [comment]
I mean, if this is still a limitation in core, then I would simply close this issue.

**Comment by tiagomistral** [comment]
@gavinking does it make sense to uncomment the setPlan and (re)check if the queries work?

**Comment by gavinking** [comment]
Sure, if it works, then there's no problem allowing it.

**Comment by tiagomistral** [comment]
Should I close this topic or you will use it to tracker this investigation? :)

**Comment by gavinking** [comment]
> ORM itself doesn't support query fetch plans properly, so don't expose this for now

So, I wish I remembered what this is in reference to, I know there was something.

But anyway, for simple cases it seems to work at least a bit.
