### ISSUE TITLE
Reactive ValueGenerator<> for use with @GeneratorType? 

### ISSUE THREAD

**Issue by noobgramming** [hibernate/hibernate-reactive#1099]
Hello! 
I have a column I need generated from a SQL snippet during session. It uses SELECT to grab a db specific global variable and stuff it into a column on insert using     
```java 
@GeneratorType( type = GrabGlobalDbVarGenerator.class, when = GenerationTime.INSERT)
    @Column(updatable = false, nullable = false)
    private long dbFetchedGlobal;
```
How can I do this in Hibernate Reactive?  `ValueGenerator<Long>`  doesn't use reactive Session.

I can `session.unwrap(ReactiveSession.class)` but there's no return of `CompletionStage<Long>` so I don't think it will work properly

Can you point me in right direction if this is supported?

**Comment by DavideD** [comment]
I don't think we support that use case at the moment. As you say, we are reusing the interface from ORM so we cannot return a `CompletionStage`.

I will create an issue for this.

**Comment by noobgramming** [comment]
@DavideD thank you for quick response. I need to finish this migration to Reactive with least hacks possible :) , can you think of any workarounds for such functionality I can use now? 

I have looked at @Formula but it generates on SELECT and I want on insert only. 

Perhaps I can lie to Hibernate and pretend its part of ID so I can use custom ID generator? 

Open to any ideas to make this work for now

**Comment by gavinking** [comment]
So no, looks like we don't.

However, it looks like it might be pretty trivial to implement, it would be a completely localized change at line 639 of `ReactiveAbstractEntityPersister`, where we would have special handling for a `ValueGenerator` that returns `Uni` or `CompletionStage`. Serendipitously, the surrounding method is already reactive.

I mean, I *think* that would work.

**Comment by DavideD** [comment]
I will give it a go

**Comment by noobgramming** [comment]
I greatly appreciate it! 
If you would like, I can get permission from my company to contribute this enhancement. But if there's CLA involved it might get bogged down in legal and take longer than it would for you to implement

**Comment by DavideD** [comment]
I've sent a PR request. I've added two new interfaces that can be use instead of `ValueGenerator`: https://github.com/hibernate/hibernate-reactive/pull/1103/commits/7cbbba503037f9fdb2ec513e1aafc0f692da8e7e
