### ISSUE TITLE
setPackagesToScan on Mutiny.SessionFactory 

### ISSUE THREAD

**Issue by guy1699** [hibernate/hibernate-reactive#1104]
With the following code, the EntityManagerFactory's metamodel has no packages/classes.

I'm missing the parallel ` sessionFactory.setPackagesToScan()` in non reactive Hibernate.

```
EntityManagerFactory emf = Persistence.createEntityManagerFactory(PERSISTENCE_UNIT_NAME, hibernateReactiveProperties());
        Metamodel metamodel = emf.getMetamodel();
        
        Mutiny.SessionFactory reactiveSessionFactory = emf.unwrap(Mutiny.SessionFactory.class);
```

**Comment by guy1699** [comment]
solved by adding a class tag for each entity in persistence.xml

    
```

<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.1"
             xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">

    <persistence-unit name="default" >
        <provider>org.hibernate.reactive.provider.ReactivePersistenceProvider</provider>
        <class>com.company.EntityClassName</class>


    </persistence-unit>
</persistence>
```


Wonder if it can be scanned automatically for each class with @Entity annotation.

**Comment by DavideD** [comment]
>Wonder if it can be scanned automatically for each class with @entity annotation.

You can use in the `persistence.xml`: 
```
        <exclude-unlisted-classes>false</exclude-unlisted-classes>
```

Although, I would have expected this to be the default behaviour.

**Comment by jhhong0509** [comment]
> > Wonder if it can be scanned automatically for each class with @entity annotation.
> 
> You can use in the `persistence.xml`:
> 
> ```
> <exclude-unlisted-classes>false</exclude-unlisted-classes>
> ```
> 
> Although, I would have expected this to be the default behaviour.

In spring boot, `exclude-unlisted-classes` does not work for me.
When I try to use `find()`, following error occurred.
```
org.hibernate.UnknownEntityTypeException: Unable to locate persister: com.test.test.user.User
```
how can I scan entities automatically?

**Comment by DavideD** [comment]
Thanks @jhhong0509. I think it's a bug, I've created a separate issue for it: https://github.com/hibernate/hibernate-reactive/issues/1270

**Comment by gavinking** [comment]
> I'm missing the parallel `sessionFactory.setPackagesToScan()` in non reactive Hibernate.

But .... there's no such method in classic Hibernate ... and for good reason, since the `SessionFactory` is supposed to be immutable. Nor is there any such method on `Configuration` or `MetadataSources`.

So I'm not sure what it is that's missing.

**Comment by DavideD** [comment]
Closing the issue.
