### ISSUE TITLE
A way to pass SSL mode to the Vertx pgClient

### ISSUE THREAD

**Issue by guy1699** [hibernate/hibernate-reactive#1108]
Today there is no way to pass SSL mode by property or URL param when using Postgres.
Correct me if I'm wrong, the only client available is Vertx and it is using `io.vertx.pgclient.PgConnectOptions`.

The constructor of PgConnectOptions does not inherit the SSL mode from the SqlConnectOptions which Hibernate sends.
https://github.com/eclipse-vertx/vertx-sql-client/blob/352e8da205598ffd9730ef36891dbc28ff544e53/vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnectOptions.java#L139

The DefaultSqlConnectOptions also does not seem to have an option for SSL to be configured, is that correct?

**Comment by blafond** [comment]
@guy1699  I'm working on #1059 with the intent on capturing all valid properties on a URL, including for PostgreSQL. Vertx sql clients provide db-specific URL parsing ( see [PgConnectionUriParser](https://github.com/eclipse-vertx/vertx-sql-client/blob/352e8da205598ffd9730ef36891dbc28ff544e53/vertx-pg-client/src/main/java/io/vertx/pgclient/impl/PgConnectionUriParser.java#L185) ).

By leveraging vertx (and tweaking their parsers for general properties) we'll should have what you need.

**Comment by blafond** [comment]
Thx for the input. I think my fix will require a tweak to Vertx SQL client parsers. Created issue:  [#1115](https://github.com/eclipse-vertx/vertx-sql-client/issues/1115)

**Comment by DavideD** [comment]
Isn't this a Vert.x issue?

In Hibernate Reactive we allow passing a custom configuration using `hibernate.vertx.pool.configuration_class` (like you have already did) or, for other advance use cases, pass a cusomt pool using `hibernate.vertx.pool.class` ([it's not described in the documentation yet though](https://github.com/hibernate/hibernate-reactive/issues/1112)).

@blafond Is there anything we need to do on the Hibernate Reactive front? Or this is going to be solved by https://github.com/hibernate/hibernate-reactive/issues/1059?

**Comment by guy1699** [comment]
@DavideD, can you describe how to use a custom pool with `hibernate.vertx.pool.class` ?
Is this different than what I did?

**Comment by DavideD** [comment]
It's different because you would have to implement `ReactiveConnectionPool` instead. What you have done seems fine.

**Comment by DavideD** [comment]
But I'm not sure why we have the property considering that `ReactiveConnectionPool` is a service

**Comment by guy1699** [comment]
What property, how one implementation of `ReactiveConnectionPool` is chosen over another @DavideD ?

**Comment by DavideD** [comment]
1. `hibernate.vertx.pool.configuration_class`: It allows you to create a custom `SqlClientPoolConfiguration`
2. `hibernate.vertx.pool.class`: It allows you to use a custom `ReactiveConnectionPool`

The only use case I can think of for 2 is Multitenancy (we have an example in our test cases: [ReactiveMultitenantTest](https://github.com/hibernate/hibernate-reactive/blob/9db5950d395d08948a221d53a09c9bbf711786d9/hibernate-reactive-core/src/test/java/org/hibernate/reactive/ReactiveMultitenantTest.java#L50)). Otherwise I wouldn't recommend to use option 2 if 1 is enough.

These properties are there so that users can have a workaround if Hibernate Reactive doesn't offer a solution for a particular use case. Using one or the other depends by the use case.

**Comment by blafond** [comment]
@guy1699 The [PR for #1059](https://github.com/hibernate/hibernate-reactive/pull/1135) includes changes that utilize the vertx sql client and the `SqlConnectOptions.fromUri()` parsing. Currently the PostgreSQL `sslmode` parameter is supported and is accessible via [`PgConnectOptions.getSslMode()`](https://github.com/eclipse-vertx/vertx-sql-client/blob/0d10efe2bbedea3c27b380d69add2f1e036da9ad/vertx-pg-client/src/main/java/io/vertx/pgclient/PgConnectOptions.java#L223). I've tested it locally.

Unfortunately, the number of supported PG connection options is currently limited and an issue is logged:  [#1115](https://github.com/eclipse-vertx/vertx-sql-client/issues/1115)

**Comment by pendula95** [comment]
For better visibility adding solution for other to find

```java
public class PgClientPoolConfiguration extends DefaultSqlClientPoolConfiguration {

    private static String HIBERNATE_VERTX_PGSQL_SSL = "hibernate.vertx.pgsql.ssl";
    private static String HIBERNATE_VERTX_PGSQL_SSL_MODE = "hibernate.vertx.pgsql.ssl.mode";

    private boolean ssl;
    private String sslMode;

    @Override
    public void configure(Map configuration) {
        super.configure(configuration);
        ssl = ConfigurationHelper.getBoolean(HIBERNATE_VERTX_PGSQL_SSL, configuration);
        sslMode = ConfigurationHelper.getString(HIBERNATE_VERTX_PGSQL_SSL_MODE, configuration);
    }

    @Override
    public SqlConnectOptions connectOptions(URI uri) {
        SqlConnectOptions sqlConnectOptions = super.connectOptions(uri);
        PgConnectOptions pgConnectOptions = new PgConnectOptions(sqlConnectOptions);

        if (ssl) {
            pgConnectOptions.setSsl(true);
            pgConnectOptions.setTrustAll(true);
            pgConnectOptions.setSslMode(SslMode.of(sslMode));
        }
        return pgConnectOptions;
    }
}
```

**Comment by DavideD** [comment]
@pendula95 , I've create a separate issue to update the documentaion with this: https://github.com/hibernate/hibernate-reactive/issues/1866
