### ISSUE TITLE
In MSSQL: Incorrect syntax near the keyword 'rule'.

### ISSUE THREAD

**Issue by hernael** [hibernate/hibernate-reactive#1109]
In MSSQL Rule is a reserved keyword.
If there is a column with a reserved name it is necessary that the sql use square brackets to make it explicit that you mean the object named "rule" it.

Use [rule] instead of rule.

**Comment by gavinking** [comment]
There's various ways to tell Hibernate to use quoted identifiers, the easiest one being to quote the column name using backticks in the `@Column` annotation.

I suggest you check the Hibernate documentation.
