### ISSUE TITLE
Rename the project to 'Hibernate Reactive'

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#111]
as discussed on #77 and the mailing list.

- [x] Rename all packages
- [x] Review interface names
- [x] Review build scritps: artifact names & co
- [x] Review `readme` & other docs
- [x] Review examples
- [ ] Update the Quarkus extension draft to match
- [x] Find & replace as needed: code comments, javadoc, etc

**Comment by gavinking** [comment]
Note that this issue includes a rename of all packages and interfaces with `rx` or `Rx` in their names.

**Comment by Sanne** [comment]
good point Gavin. I've added a checklist

**Comment by DavideD** [comment]
Should we also rename packages called `impl` to `internal` like in ORM?

**Comment by Sanne** [comment]
> Should we also rename packages called `impl` to `internal` like in ORM?

Sounds good to me, it's a bit clearer.. no strong opinion though

**Comment by gavinking** [comment]
Don't care.

**Comment by gavinking** [comment]
Hold tight, working on this now!

**Comment by gavinking** [comment]
OK, this is done, except for the Quarkus extension.

@aguibert can you take care of that?

**Comment by aguibert** [comment]
Yep, I can get that updated later today

**Comment by gavinking** [comment]
Great, thanks.

**Comment by gavinking** [comment]
I think we can close this issue now, since the Quarkus Extension isn't actually strictly-speaking part of this project.

**Comment by aguibert** [comment]
Agreed, but FWIW I did update the Quarkus extension yesterday (just didn't report it back here)

**Comment by gavinking** [comment]
Perfect 👍
