### ISSUE TITLE
createNativeQuery method returns custom entity

### ISSUE THREAD

**Issue by janyyy** [hibernate/hibernate-reactive#1137]
How do I return a custom entity object after I call the createNativeQuery method? ExampleDto, for example, has only two fields. Unlike data and entities, the mapping can be customized when it is not reactive.

**Comment by gavinking** [comment]
I don't really understand the question, but have you used `@SqlResultSetMapping`?

**Comment by janyyy** [comment]
> I don't really understand the question, but have you used `@SqlResultSetMapping`?

It is to check the data table corresponding to entity A and return the DTO class of entity A. I'm trying the method you said
