### ISSUE TITLE
Add tests for unicode chars

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1151]
SQL Server  changes the enconding of the chars based on the column type. We need to check that everything works when storing non ASCII characters.

See this issue on Quarkus: https://github.com/quarkusio/quarkus/issues/19539

**Comment by gavinking** [comment]
But is this really our problem to worry about? I don't see character encodings as being something we should even be messing with.

**Comment by DavideD** [comment]
I just wanted to make sure that it works

**Comment by DavideD** [comment]
I don't think it hurts to have a test for this but we can remove it if it causes issues.

**Comment by gavinking** [comment]
Make sure that this isn't just because the user has VARCHAR instead of NVARCHAR columns. Possibly Hibernate ORM schema export has a "bad" default here.

**Comment by gavinking** [comment]
OK our messages crossed.
