### ISSUE TITLE
Add SessionFactory.getStatistics

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1161]

**Comment by gavinking** [comment]
I mean, I like ass too, but not sure what it has to do with Hibernate statistics.

**Comment by DavideD** [comment]
Maybe I've approved this too soon:

* It seems it fails on CI: https://github.com/hibernate/hibernate-reactive/runs/4968581689?check_suite_focus=true#step:6:1674
* Statistics use lock mechanisms, aren't this going to block the execution? https://github.com/hibernate/hibernate-orm/blob/5.6/hibernate-core/src/main/java/org/hibernate/stat/internal/QueryStatisticsImpl.java#L165

**Comment by gavinking** [comment]
> Statistics use lock mechanisms, aren't these going to block the execution?

Naaah, not at all. That's perfectly fine. In fact it's even less of a problem in reactive because there's only one thread.

**Comment by gavinking** [comment]
Ah right, looks like it's this assertion that's failing:

> context.assertNotEquals( 0L, queryStatistics.getExecutionMaxTime() );

I imagine because the database is responding too quickly. I did wonder about that.

**Comment by gavinking** [comment]
I disabled those assertions, let's see if that fixes it.

**Comment by gavinking** [comment]
> I disabled those assertions, let's see if that fixes it.

It did, so we're good.

The only problem was postgres is faster in the CI server, apparently.
