### ISSUE TITLE
Query parameter support and result limits and offset

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#120]
Support `Query.setParameter()` and `Query.setMaxResults()`.

Note that `Query.setMaxResults()` is mostly working, except for parameter binding, so these two things seem to be related.

**Comment by DavideD** [comment]
@gavinking are you working on this or is it something I can look into?

**Comment by gavinking** [comment]
@DavideD I have a couple of other tasks I'm still working on right now, so if you want to make a start go for it

**Comment by DavideD** [comment]
Cool, thanks

**Comment by gavinking** [comment]
When this is ready, we'll have to test it for:

- [ ] HQL queries
- [ ] native SQL queries
- [ ] filters (see #26)
- [ ] criteria queries

I'm hoping it will all Just Work by magic, but perhaps that's too optimistic.

**Comment by DavideD** [comment]
Should we keep this issue open until we added the additional test cases or close it and create a separate one?

**Comment by gavinking** [comment]
> Should we keep this issue open until we added the additional test cases

What tests are missing?

**Comment by DavideD** [comment]
Don't we need tests for native queries, filters, and criteria queries?

**Comment by gavinking** [comment]
Ah, OK, sure, good point. Yes we do. OK, open a new issue then.

Are we laying bets on whether they work with no changes?

**Comment by DavideD** [comment]
Absurd! Why would you bet knowing that our code is always perfect :)

**Comment by DavideD** [comment]
Created https://github.com/hibernate/hibernate-reactive/issues/211

Thanks
