### ISSUE TITLE
Improve error message when lazy collection is not initialized

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1205]
Currently, the error is:
```
org.hibernate.LazyInitializationException: HR000056: Collection cannot be initialized: com.example.Parent.lazyChildren
```

We should tell the user that they need to fetch the connection:
* Using a `fetch join` in the query
* Or, using the `Mutiny.fetch` or the `Stage.fetch`

We should also add this on the WebSite in the Faq section.

**Comment by liconalicona** [comment]
Hi, I have the same issue with panache reactive on Quarkus 2.8.3.Final
_com.fasterxml.jackson.databind.JsonMappingException: HR000056: Collection cannot be initialized_

The non-reactive version of this code works fine.


Thanks

**Comment by DavideD** [comment]
@liconalicona You are seeing this error message because you are trying to access a lazy association. You can do that with Hibernate ORM - the non-reactive version - but you cannot do it with Hibernate Reactive. 
This paragraph in the documentaion should explain to you what's happening: https://hibernate.org/reactive/documentation/1.1/reference/html_single/#_fetching_lazy_associations

This issue is not about the adding a new feature to Hibernate Reactive, it's about updating the error message and make it easier for people to find an explanation of the behavior.
