### ISSUE TITLE
Add support for result transformers

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1209]
In ORM is possible to [apply a ResultTransformer to a native query](https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html#sql-dto-query):
```
session.createNativeQuery(...).setResultTransformer(...)
```

We already have an internal interface [ReactiveNativeQuery](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/ReactiveNativeQuery.java) that accepts `ResultTransformer`.

We probably just need to decide how to expose it.

**Comment by gavinking** [comment]
I don't think we should expose this because it's deprecated in Hibernate ORM.

**Comment by janyyy** [comment]
> I don't think we should expose this because it's deprecated in Hibernate ORM.

You say it's deprecated, is there an alternative? Actual business may involve such operations, complex report queries, etc. Using native SQL query, map a non-@Entity database entity class.

**Comment by gavinking** [comment]
I mean, what's wrong with just transforming the `Object[]` arrays returned to you by `getResultList()`?

**Comment by DavideD** [comment]
If it makes it easier, It's also possible to return the result as a `javax.persistence.Tuple`: 
```
session.createNativeQuery("select title, isbn, id from books", Tuple.class ).getResultList()
.thenAccept( list -> {
	Tuple tuple = list.get(0);
        String isbn = tuple.get("isbn");
} )
```

**Comment by DavideD** [comment]
I'm closing this one. They are deprecated and it doesn't seem critical to have them at the moment.  It's also possible to return the entity if the native query returns all the necessary columns.
