### ISSUE TITLE
Periodic slowdowns, how to troubleshoot?

### ISSUE THREAD

**Issue by schlumpfling42** [hibernate/hibernate-reactive#1220]
I wrote a server that is using Hibernate for persistence and I made a version with regular hibernate and a reactive version. The entities are very simple the main entity has a one-to-one and a one-to-many relation, but the test is not using the one-to-many. The relations are fetched eager it's using a join to fetch .
I created a JMeter test with 20 threads, 2 puts, 6 gets, 1 post and one delete. The server can do about 350 requests/s against a local PostgreSQL server. Both implementations are very much comparable, except that once in a while the reactive version slows down significantly for several requests and then goes back to normal. There is no slowdown in the implementation using the regular hibernate version. I'm using the latest versions for Hibernate, Smallrye and PostgreSQL Jdbc driver. The Vertx has 16 instances (one per core), hibernate is configured with 50 connections. I tried changing the number of instances, number of connections, but no changes.
I don't believe the database is the reason for the slowdowns, since the non-reactive version doesn't have those issues. 
How can I figure out what is causing this? 
Here is what the get/find does:

```
            Query<Long> countQuery;
            Query<Collection<?>> query;
            countQuery = session.createQuery("select count(e) from Entity e");
            query = session.createQuery("select e from Entity e");
            query.setLockMode(LockMode.READ);
            query.setFirstResult(0);
            query.setMaxResults(100);
            long startTime = System.currentTimeMillis();
            return countQuery.getSingleResult().attachContext().chain(countWithContext -> {
                countWithContext.context().put("SQL", System.currentTimeMillis() - startTime);
                return query.getResultList()
                    .map(list -> new Page<>(countWithContext.get(), pageRequest, list)).map(result -> {
                        countWithContext.context().put("SQL", countWithContext.context().get("SQL") + ":" + (System.currentTimeMillis() - startTime));
                        return result;
                    });
                });
```
Here is log output I'm generating: (Total = time from request coming in until the response is written, CTRL = time in the controller, SQL = time for select count: time for select)
Total:31, CTRL:31, SQL:1:31
Total:32, CTRL:31, SQL:1:31
Total:33, CTRL:33, SQL:1:32
Total:47, CTRL:47, SQL:1:46
Total:30, CTRL:30, SQL:1:30
Total:30, CTRL:30, SQL:1:30
Total:31, CTRL:31, SQL:1:31
Total:33, CTRL:33, SQL:1:32
Total:33, CTRL:33, SQL:1:33
Total:36, CTRL:35, SQL:1:35
Total:29, CTRL:29, SQL:1:29
Total:46, CTRL:45, SQL:1:45
Total:46, CTRL:46, SQL:1:46
Total:573, CTRL:572, SQL:1:572
Total:574, CTRL:573, SQL:2:573
Total:574, CTRL:574, SQL:2:574
Total:47, CTRL:47, SQL:1:47
Total:47, CTRL:46, SQL:1:46
Total:573, CTRL:573, SQL:1:573
Total:574, CTRL:573, SQL:1:573
Total:573, CTRL:573, SQL:1:573
Total:574, CTRL:573, SQL:2:573
Total:574, CTRL:573, SQL:2:573
Total:573, CTRL:573, SQL:2:573
Total:573, CTRL:573, SQL:1:573
Total:573, CTRL:573, SQL:2:573
Total:583, CTRL:582, SQL:1:582
Total:583, CTRL:583, SQL:1:583
Total:578, CTRL:578, SQL:1:578
Total:577, CTRL:577, SQL:1:577
Total:576, CTRL:575, SQL:1:575

**Comment by DavideD** [comment]
Can you share the project? 

> The Vertx has 16 instances (one per core)

Are you talking about Vert.x instances or [Verticles](https://vertx.io/docs/vertx-core/java/#_verticles)? Because, usually, one vert.x instance is enough and it will create a number of event loop threads that's 2 * (number of core processors):

> Verticles are chunks of code that get deployed and run by Vert.x. A Vert.x instance maintains N event loop threads (where N by default is core*2) by default.

**Comment by schlumpfling42** [comment]
1 vertx instance, 16 verticles/event loop threads.

**Comment by DavideD** [comment]
@Sanne maybe you want to chime in?

**Comment by Sanne** [comment]
I would suggest starting from basic system metrics; for example, is the slowdown corelated to any GC related activities?

It might also be useful to see if the two versions of the application have the same baseline performance; if - for example - the reactive version is able to more quickly saturate the available resources in the DB (or of the channels and pools connecting to the DB) that would fire back.

Which is the reason we don't normally suggest running a benchmark this way: there's no much point in seeing how the system will perform when it's close to saturation - that's an interesting exercise *exclusivelly* to check what the system behaviour will be when pushed close to its limits.

A better way to compare the two systems is to define expected SLAs and then see how the two solutions fare to match such SLAs, and possibly what cost factors would be impacted.

If you could share some JFR recordings it might be possible for us to help you figure out *what* is causing this particular anomaly, which could be interesting for us to improve *some* anomalies possibly interesting for us to know, but I'd still suggest you change approach so to not pursue the wrong metrics.

**Comment by schlumpfling42** [comment]
A couple of things. I'm just trying to compare the behavior. I really would like to go forward with the reactive version, but if I cannot have the same kind of consistent throughput, I will have to abandon hat idea.
I do not believe that with 20 thread I hit any limits in the database, memory or IO limits. The database is very responsive to other requests that I'm doing while the test is running. I have a tool to see the number of transactions per seconds and I can see there are more spikes when using the non-reactive version, but I don't know if that is the cause of the problem or the reaction to the problem. I used Visual VM to see memory consumption and the reactive implementation has significant higher memory consumption, but well below the maximum. The average GC activity is about 0.2% with the occasional hike to 2.5%. The average CPU usage is 30%. I do not see any resource that could be maxed out.
I do not want to know how to solve the problem, I would like to get an idea on how to debug/pinpoint the problem. Visual VM is unable to profile my app, I don't know why. But even if it would be I doubt that it will be able to provide me with the same kind of insight that it would be providing me with the non-reactive app would.

**Comment by Sanne** [comment]
> I do not want to know how to solve the problem, I would like to get an idea on how to debug/pinpoint the problem.

I agree with the spirit :+1: 

It's always about lack of some resource; the process is about identifying it - either because it comes to your mind or because you get to trace the execution and get clues pointing to it. Good to know it's not GC nor CPU.. that rules out the basics. What about available connections in the pool?  JFR recordings might give you more clues.

It's hard for me to help you further, you didn't mention versions and I don't even know what you're running this on: is it Vert.x web? Quarkus?

Remember the connection pool in vert.x 4 changed design compared to v.3 - try to ensure also (for a fair comparison) that both applications use the same number of total connections. It might be easier to log/trace this on the DB side to confirm sizing is working as expected.

**Comment by schlumpfling42** [comment]
![non-reactive_reactive_db](https://user-images.githubusercontent.com/2719863/156677258-9ca754d9-8bc3-4e10-9fd9-91b610457adb.png)
I'm very confused by what's happening on the database side. The non-reactive is the first bit ... it's even it equals about 370 request/second in JMeter. The reactive server is the second bit. The transactions per second is quite a bit higher, but IO is lower ... and it's about 330 request/second in JMeter. 
So ... IO seems to match the throughput I see in JMeter, but transactions don't.
I don't know where the higher number of transactions are coming. Will double check the code and make sure that I'm not doing extra stuff, but I'm fairly sure, that I am not.

**Comment by schlumpfling42** [comment]
I turned on tracing, the pg client supports it out of the box and I have 12! selects that are executed for fetching entities. I have 2 relations in my model, a one-to-one and a many-to-one. In my test I'm using the one-to-one but not the many-to-one. I have FetchMode.JOIN set in the annotations (unfortunatly I cannot provide a sample, because I generate the entity classes. When I take the relations out I'm down to 2 queries per request as I'm expecting it and the throughput is quite a bit better, still not as linear as the other implementation.
So questions is FetchMode.JOIN working?

**Comment by DavideD** [comment]
Yes, `FetchMode.JOIN` should work.

But we cannot help without having an example of your model or the query that are executed.
I'm going to close this issue because without additional information, there is not much we can do. Feel free to comment on here if have some more questions.
