### ISSUE TITLE
Hibernate Reactive Panache NonUniqueObjectException

### ISSUE THREAD

**Issue by LazaroR94** [hibernate/hibernate-reactive#1228]
Hello all, I am currently working on a project that uses Hibernate Reactive Panache and I am seeing a new error that I have not seen before: `org.hibernate.HibernateException: java.util.concurrent.CompletionException: org.hibernate.NonUniqueObjectException: A different object with the same identifier value was already associated with the session : [..database.entity.Egress#35]`. This is how I am doing the insert into that table (batch):
```
     override fun saveAll(entities: List<Transaction>): Uni<Void> =
        Panache.withTransaction { egressRepo.persist(entities.map { Egress.of(it) }) }
            .onFailure().invoke { failure -> log.error("Error while connecting to DB: ${failure.localizedMessage}") }
```
The table does have a generated sequence on the database to auto increment a specific column based on the created sequence:
```
    @Id
    @SequenceGenerator(name = "some_sequence", sequenceName = "some_sequence_name")
    @GeneratedValue(generator = "egress_sequence", strategy = GenerationType.IDENTITY)
    @Column(name = "SomeTable", unique = true, nullable = false)
    var id: Long = -1L
```
This error seems to happen once or twice every hour when a batch of records come through. Am I doing something wrong?

**Comment by DavideD** [comment]
> var id: Long = -1L

Why -1 and not `null`?

**Comment by LazaroR94** [comment]
> > var id: Long = -1L
> 
> Why -1 and not `null`?

Seeing as this implementation was not mine, I believe the reasoning for this was for traceability. But will this cause an issue if it is not nullable?

**Comment by DavideD** [comment]
Well, the error says that the failed entity is ` database.entity.Egress#35`. So maybe it's not related

**Comment by DavideD** [comment]
Could you show the full stacktrace?
