### ISSUE TITLE
AutoFlush listener calls the wrong listener at the wrong time

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1232]
1. Calls `EventListenerManager#flushEnd` instead of `EventListenerManager#partialFlushEnd`
2. The last call to `.whenComplete` is not chained correctly
3. Uses `ActionQueue` instead of `ReactiveActionQueue`

**Comment by Sanne** [comment]
This looks like rather critical, would you agree? Do you have a concrete example of how this issue could manifest in an application?

**Comment by DavideD** [comment]
No idea. I've found out about these because I've noticed that the `whenComplete` wasn't chained.
