### ISSUE TITLE
Specify the repository where to download the docker images

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1235]
Docker doesn't always use docker hub as the default repository. 
If the configuration contains multiple repositories, the build with reactive will fail because we use the short name of the image.

This issue is about specifying the long name of the image, for example:
```
docker.io/mariadb:10.7.1
```
Progress:
- [X] MariaDB
- [X] Oracle
- [X] MS SQL Server (Not necessary...probably)
- [X] MySQL
- [X] CockroachDB
- [X] PostgreSQL
- [X] Db2

**Comment by DavideD** [comment]
@Sanne how come mariadb was the only one causing problems? It's because you already had the other images locally?

**Comment by Sanne** [comment]
Yes. It's the only one that  (I didn't have locally) AND (can be fetched from multiple sources)

**Comment by Sanne** [comment]
N.B. it needs to be `docker.io/mariadb:10.7.1` and not `docker.io/library/mariadb:10.7.1`. I had fixed the description but it seems you reverted it.

**Comment by DavideD** [comment]
Fixed back

**Comment by DavideD** [comment]
Fixed, thanks!
