### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#126]
So in the Gradle build we have:

```gradle
    compile ("org.hibernate:hibernate-core:${hibernateOrmVersion}") {
        exclude group: 'org.javassist', module: 'javassist'
        exclude group: 'net.bytebuddy', module: 'byte-buddy'
        exclude group: 'org.dom4j', module: 'dom4j'
        exclude group: 'javax.activation', module: 'javax.activation-api'
        exclude group: 'org.glassfish.jaxb', module: 'jaxb-runtime'
        exclude group: 'javax.xml.bind', module: 'jaxb-api'
        exclude group: 'org.hibernate.common', module: 'hibernate-commons-annotations'
        exclude group: 'org.jboss.spec.javax.transaction', module: 'jboss-transaction-api_1.2_spec'
    }
    testCompile ("org.hibernate:hibernate-testing:${hibernateOrmVersion}")
    compile 'io.vertx:vertx-pg-client:3.9.0'
    compile 'io.vertx:vertx-mysql-client:3.9.0'

    runtimeOnly 'org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:1.1.1.Final'
```

I would like to know what is the reason for all the exclusions here. I would naïvely have expected us to just declare a dependency to `hibernate-core`, and then programs that use HR would not need to explicitly declare their own dependency to Hibernate. But with all these exclusions, they need to redeclare the dependency in order to pick up stuff like `net.bytebuddy`.

I suspect that these exclusions might not now be the right thing, since I've eliminated the separate `-api` module.

Also I'm confused by the exclusion of `jboss-transaction-api_1.2_spec` and then the re-inclusion as a runtime dependency.

@DavideD could you throw some light on this, I'm sure there was some reason.

**Comment by DavideD** [comment]
I think the idea was to remove all dependencies that we didn't need for a first prototype. @Sanne ^

**Comment by Sanne** [comment]
I can review these.

**Comment by Sanne** [comment]
> Also I'm confused by the exclusion of jboss-transaction-api_1.2_spec and then the re-inclusion as a runtime dependency.

On that point: it's only to exclude the JTA API when our own new code is compiled; this helps ensure that we don't expose the blocking JTA API, or use it otherwise unintentionally.

It's then re-introduced as a runtime dependency as I believe ORM can't boot without having it - we might be able to improve on that and make it 100% unnecessary but it doesn't feel like a priority

**Comment by gavinking** [comment]
Well the issue is that right now, by excluding all those things, at least some of which are hard dependencies of Hibernate ORM, we force users to explicitly depend on Hibernate ORM as well as HR.

**Comment by gavinking** [comment]
> I think the idea was to remove all dependencies that we didn't need for a first prototype.

*We* might not need them, but the user's program can't run without them.

**Comment by Sanne** [comment]
Sure I understand. We'll add the ones that the user application needs - the intention is only to exclude dead weight that they won't need.

N.B. the  configuration name in Gradle named "compile" is not meaning what the name suggests :) Hint: there's also a "compileOnly". https://docs.gradle.org/4.10.2/userguide/building_java_projects.html

It's also a very old and deprecated name, I'll change it to use the better named configurations it offers nowadays in Gradle 6+

**Comment by gavinking** [comment]
OK, great, thanks guys.
