### ISSUE TITLE
Eliminate dependencies on specific Vertx drivers

### ISSUE THREAD

**Issue by aguibert** [hibernate/hibernate-reactive#128]
Currently core depends on all of the individual Vertx drivers:

```
    compile 'io.vertx:vertx-pg-client:3.9.1'
    compile 'io.vertx:vertx-mysql-client:3.9.1'
    compile 'io.vertx:vertx-db2-client:3.9.1'
```

With a few minor exceptions, this is needed to create the DB-specific ConnectOptions object (e.g. `DB2ConnectOptions`).

Recently a new API was added to Vertx that will allow generic creation of the SqlConnectOptions like this:
```java
SqlConnectOptions opts = new SqlConnectOptions()
    .setHost("mydb.com")
    .setPort(1234)
    // etc...
Pool pool = Pool.pool(opts);
```

The only limitation with this generic approach is that there must be exactly 1 Vertx driver found on the classpath. Otherwise, an error is thrown.

So I think we have 3 options here:
1) Use the generic SPI described above (with the limitation that only 1 driver can be on the classpath)
2) Use the current approach, but load/instantiate the DB-specific ConnectOptions using reflection as to not have a compile dependency on all drivers
3) Use a hybrid of options (1) and (2). First try option (2), which will tolerate cases where multiple drivers are on the classpath. If none are found there, try option (1) which will account for any new Vertx drivers that we don't have explcit knowledge of in option (2) (e.g. the SQL Server driver).

I'm leaning towards option (3) since it's the most flexible. 
Any other thoughts on this @gavinking @Sanne @DavideD ?

**Comment by emmanuelbernard** [comment]
How much would that affect Quarkus which passes the connection pool? I am thinking it wont. And we would be able to have multiple Vert.X pools of different DB types, correct?

**Comment by gavinking** [comment]
I would love to not have this stuff work by reflection.

I propose option (4) which is change the Vert.x API so that it can handle having multiple drivers in the classpath and let you select the one you want explicitly.

**Comment by aguibert** [comment]
@emmanuelbernard Right, Quarkus already passes the Vertx pool in directly, so from a Quarkus perspective all this does is eliminate unnecessary dependencies. Quarkus can already have multiple different pools and will still be able to do that regardless of what option we go with here. This issue only effects standalone Hibernate Reactive usage.

@gavinking Yes, I think it would be good if we added a `SqlConnectOptions#setKind(String)` method to the Vertx API to help disambiguate. Currently `SqlConnectOptions` only holds generic information like host/port/dbname/user/pass so just by inspecting a `SqlConnectOptions` instance  we can't tell what type of DB it's for. However, we can't create/use such an option until the next Vert.x release, which wont' be for a while. How about we do option (3) during the Vertx 3.9.1 timeframe and then implement option (4) once Vertx 3.9.2 comes out?

**Comment by gavinking** [comment]
> How about we do option (3) during the Vertx 3.9.1 timeframe and then implement option (4) once Vertx 3.9.2 comes out?

I suppose it's our only reasonable option.

**Comment by DavideD** [comment]
What's going to be the time frame between Vertex 3.9.1 and 3.9.2? couldn't we keep the dependencies for the time being and only implement option 4?

**Comment by aguibert** [comment]
If the gap between 3.9.0 and 3.9.1 is any indication, it's roughly 2 months out
