### ISSUE TITLE
Support for Array Types

### ISSUE THREAD

**Issue by iamKunal** [hibernate/hibernate-reactive#1285]
Hi

I am trying to use a `List` (and Array) of `String`s and map it and use it with Postgres Text array type (`text[]`).

I looked at https://github.com/hibernate/hibernate-reactive/issues/279 and tried using the  `@Type(type = "com.vladmihalcea.hibernate.type.array.StringArrayType")` and `@Type(type = "com.vladmihalcea.hibernate.type.array.ListArrayType")` but both of them try to access https://github.com/hibernate/hibernate-reactive/blob/1.1.4/hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/PreparedStatementAdaptor.java#L506-L509 while setting the array via https://github.com/vladmihalcea/hibernate-types/blob/hibernate-types-parent-2.16.2/hibernate-types-55/src/main/java/com/vladmihalcea/hibernate/type/array/internal/ArraySqlTypeDescriptor.java#L36-L39

Any suggestions on getting `List<String>` and `String[]` to map to `text[]` while working with Postgres?

**Comment by DavideD** [comment]
I think using a UserType is the easiest approach:
```
	public class StringArray implements UserType {

		@Override
		public int[] sqlTypes() {
			return new int[] { Types.OTHER };
		}

		@Override
		public Class returnedClass() {
			return String[].class;
		}

		@Override
		public boolean equals(Object x, Object y) throws HibernateException {
			return Objects.deepEquals( x, y );
		}

		@Override
		public int hashCode(Object x) throws HibernateException {
			return Arrays.hashCode( (String[]) x );
		}

		@Override
		public Object nullSafeGet(ResultSet rs, String[] names, SharedSessionContractImplementor session, Object owner)
				throws HibernateException, SQLException {
			return rs.getObject( names[0] );
		}

		@Override
		public void nullSafeSet(PreparedStatement st, Object value, int index, SharedSessionContractImplementor session)
				throws HibernateException, SQLException {
			if ( value == null ) {
				st.setNull( index, Types.OTHER );
			}
			else {
				st.setObject( index, value );
			}
		}
                ...
}
```

and you can use it when mapping the entity:
```
		@Type( type = "org.example.StringArray")
		@Column(columnDefinition = "text[]")
		String[] stringArray;
```

We use the same approach for mapping [Json](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/Json.java) types. 
The Hibernate ORM guide also contains some additional [info about user types](https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html#basic-custom-type-UserType)
