### ISSUE TITLE
Create a test for 'hibernate.order_updates'  option

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1287]
We already have a fix we tested manually. We need to add JUnit test.
See #1284

**Comment by blafond** [comment]
@DavideD I pushed a draft test to my repo. I don't think it's set up correctly yet so I have some questions

**Comment by blafond** [comment]
@DavideD @Sanne this issue was logged stating the config property `hibernate.order_updates` was not effective.  I'm having trouble defining an applicable test.

Is there an example somewhere you recommend that would create the persist/update scenario that would trigger that property?

**Comment by DavideD** [comment]
The one we discussed yesterday doesn't work?

**Comment by blafond** [comment]
The test passes, but I can't reproduce any scenario where removing the 1 line fix creates an error of some sort.

**Comment by Sanne** [comment]
It's indeed tricky to catch a failure; the reason I noticed that it wasn't doing the right thing is that when having multiple parallel requests, under load, is that occasionally there would be spikes in latency because of contention on the data in the database.
In extreme cases (but still quite likely under load) a deadlock would manifest.

These deadlocks would happen because we're locking N rows at random, in an unspecified order. But having set `order_updates` I would have expected all operations to be completed by locking the N rows in the same, consistent order - in which case deadlocks wouldn't happen.

N.B. I'm not suggesting to include a stress test or a load test - that would be overkill. Just verifying that update SQL statements are emitted in the expected order would be enough.

**Comment by blafond** [comment]
@DavideD I pushed a couple of new commits and rewrote the test.  Wasn't a simple change to capture logged queries with actual parameter values. I had to tweak SqlClientConnection to trigger the process of generating additional SQL statements for the tracker to serve up to the tests.

I couldn't find a way around not moving `SqlStatementTracker` into `pool/impl` package though.  Wasn't my first choice.

And I still can't make the test fail by removing your one-line [commit](https://github.com/hibernate/hibernate-reactive/commit/d62630f68ce0170b377253bd2c0417462abd79e8).

**Comment by DavideD** [comment]
I've created a draft for a test case here: https://github.com/DavideD/hibernate-reactive/commit/ebb7475ff4150854efddb4a6c7317f715a7f207a?diff=unified

You can see in the log that when the `hibernate.order_updates` property is false the SQL queries logged are:
```
[Hibernate] update Category set name=$1 where id=$2
[Hibernate] update Product set name=$1, price=$2 where id=$3
[Hibernate] update Category set name=$1 where id=$2
[Hibernate] update Product set name=$1, price=$2 where id=$3
[Hibernate] update Category set name=$1 where id=$2
[Hibernate] update Product set name=$1, price=$2 where id=$3
...
```

when set to true:
```
[Hibernate] update Category set name=$1 where id=$2
[Hibernate] update Category set name=$1 where id=$2
[Hibernate] update Category set name=$1 where id=$2
[Hibernate] update Category set name=$1 where id=$2
....
[Hibernate] update Product set name=$1, price=$2 where id=$3
[Hibernate] update Product set name=$1, price=$2 where id=$3
[Hibernate] update Product set name=$1, price=$2 where id=$3
[Hibernate] update Product set name=$1, price=$2 where id=$3
[Hibernate] update Product set name=$1, price=$2 where id=$3
[Hibernate] update Product set name=$1, price=$2 where id=$3
...
```

Can you refactor it to a proper test case, please?

* Remove the ORM part (it was only for checking the differences)
* Add the proper assertions
* Add test for `hibernate.order_inserts` property too
* The changes to the SqlTracker are not necessary anymore
* Test that when we set the Batch size only the expected number of queries run. For example, setting `hibernate.jdbc.batch_size`  to 50 will only log two  update queries in this case (when `order_inserts` is true)

Let me know if you need more info.
