### ISSUE TITLE
how Hibernate reactive work with Database

### ISSUE THREAD

**Issue by HelloTo4x** [hibernate/hibernate-reactive#1320]
Hi, some RDBMS doesn't support with Stream, so how can Hibernate reactive can work with it to get data like "Reactive stream", thank u so much

**Comment by gavinking** [comment]
Hibernate Reactive doesn't work with every database, only with the databases explicitly listed. If your database is on the list, you are good; if it's not on the list, you can't use HR.

**Comment by HelloTo4x** [comment]
@gavinking , i am using Oracle and MySQL, but 2 database don't support Stream, so how can u do it with Reactive ?

**Comment by DavideD** [comment]
I think we talked about this here some time ago: https://github.com/hibernate/hibernate-reactive/issues/153
Basically, Streaming the result of a query is not possible at the moment.

**Comment by HelloTo4x** [comment]
> I think we talked about this here some time ago: #153 Basically, Streaming the result of a query is not possible at the moment.

No, i mean some database doesn't support Stream, how u can do with it to make it Reactive

**Comment by gavinking** [comment]
Well you just said the same thing again, still without defining what you mean by "Stream".

Look, all "reactive" means here is the use of nonblocking I/O for communication between client and server. 

So: Hibernate Reactive does not blocking the requesting thread while waiting for a response from the database server. 

I don't know what "Stream" has to do with that, or why the database server would need it.

**Comment by HelloTo4x** [comment]
> Well you just said the same thing again, still without defining what you mean by "Stream".
> 
> Look, all "reactive" means here is the use of nonblocking I/O for communication between client and server.
> 
> So: Hibernate Reactive does not block the requesting thread while waiting for a response from the database server.
> 
> I don't know what "Stream" has to do with that, or why the database server would need it.

i mean if you don't use "Stream", Stream for process each element of data, we can't make it Reactive

**Comment by gavinking** [comment]
> each element of data

Ok, so if what you mean you mean by this is that you want to hold a result set (along with its associated memory and/or locks) _open on the database server_, while the client incrementally "pulls" individual rows of the result set as needed, then:

1. that's simply not a requirement for the system to be "reactive", and
2. it's almost always a terrible idea.

So no, we don't do that. And it's a good thing we don't.
