### ISSUE TITLE
note and warn icons in documentation

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#1325]
The docs on the website currently have broken image links for the note and warning icons.

**Comment by gavinking** [comment]
This appears to be caused by blocked access to the font-awesome stylesheet. @Sanne any idea how to fix this?

<img width="1146" alt="Screen Shot 2022-06-08 at 10 31 12 PM" src="https://user-images.githubusercontent.com/579974/172711616-2d433155-cf9a-4106-b798-f9edd3cf9c98.png">

**Comment by yrodiere** [comment]
@DavideD knows about this, he configured content security policy in the first place.

**Comment by Sanne** [comment]
> @DavideD knows about this, he configured content security policy in the first place.

thanks - I have no idea myself. Davide is travelling, I guess he'll have a look tomorrow.

**Comment by DavideD** [comment]
ACK

**Comment by gavinking** [comment]
Perfect, thanks man.
