### ISSUE TITLE
Stream with Oracle

### ISSUE THREAD

**Issue by FishingZVVZ** [hibernate/hibernate-reactive#1346]
Hi, i see Oracle and MySQL still support Stream like: https://docs.oracle.com/database/121/STRMS/strms_over.htm , so i have a question, Do you use it for designing Reactive Protocol for Hibernate reactive

**Comment by DavideD** [comment]
I think this is a question for the [Vert.x SQL client](https://github.com/eclipse-vertx/vertx-sql-client/) team. At the moment, we don't support streaming to databases but if the feature becomes available, we will add it to the SQL client.

[We discussed this in the past](https://github.com/hibernate/hibernate-reactive/issues/153) and decided that we couldn't yet implement it in a way that made sense.  But it's something that we would like to add at some point.

**Comment by DavideD** [comment]
Sorry, I don't know what you mean.
I'm going to close this issue because it's not really an issue, but feel free to continue the conversation here.

**Comment by DavideD** [comment]
Yes, in Hibernate Reactive we connect through the db using the drivers. If the drivers don't support it, we cannot support it.
