### ISSUE TITLE
NamedQuery doesn't work 

### ISSUE THREAD

**Issue by semistone** [hibernate/hibernate-reactive#1368]
**Version**: tag 1.1.7
**Reproduce Step**

org.hibernate.reactive.example.session.Book

`@NamedQuery(name = "findByAuthor", query = "FROM Book B WHERE author.id = :authorId")`
`class Book {
...
`

org.hibernate.reactive.example.session.Main
add test

```
			Book findByAuthor = factory.withSession(session -> session.createNamedQuery("findByAuthor", Book.class)
					.getSingleResult()).toCompletableFuture().join();
```

**Error**

Caused by: org.hibernate.QueryException: Named parameter not bound : authorId

Database: MySQL

and it worked in 1.0.0.CR6

**Comment by gavinking** [comment]
But ... in that code snippet you don't seem to bind a value to the named parameter ... so the error message looks correct!

**Comment by semistone** [comment]
sorry , 
test by wrong code.
