### ISSUE TITLE
Hibernate Reactive not an insert/update/delete query

### ISSUE THREAD

**Issue by LazaroR94** [hibernate/hibernate-reactive#1427]
Hello all! I've recently migrated over to Kotlin coroutines and opted to use `Mutiny.SessionFactory` as my database operations layer but I seem to be having an issue when creating query using that framework. I have an UPDATE query set up to perform an update operation on a specific entity on the database but it keeps failing with error: **not an insert/update/delete query**.

This is what I have so far:
```
sessionFactory.withTransaction { session ->
                session.createQuery<SomeEntity>(
                    "UPDATE inbd_trans " +
                        "SET inboundTransaction = :inboundTransaction, " +
                        "createdUserId = :createdUserId " +
                        "WHERE transactionMessageId = :transactionMessageId"
                )
                    .setParameter("inboundTransaction", entity.inboundTransaction)
                    .setParameter("createdUserId", entity.createdUserId)
                    .setParameter("transactionMessageId", entity.transactionMessageId)
                    .executeUpdate()
            }
```

To me, this looks correct - am I missing anything?

**Comment by DavideD** [comment]
Hello,
the query looks fine, how did you map the entity?
Can you create a small test case?

**Comment by LazaroR94** [comment]
> 

Hello Davide, I unfortunately cannot share much more as this is enterprise code but I will share how my entity looks like:
```
@Cacheable
@LoggedObject
@Entity(name = "inbd_trans")
data class InboundEntity(
    @Id
    @Column(name = "trans_msg_id", length = 40, nullable = false)
    var transactionMessageId: String? = "",

    @Column(name = "iso_alpha3_ctry_cd", length = 3, nullable = false)
    var countryCode: String? = "",

    @Column(name = "trans_sta_nm", length = 10, nullable = false)
    var transactionStatusName: String? = "",

    @Column(name = "trans_msg_tx", length = 20000, nullable = false)
    var inboundTransaction: String? = "",

    @Column(name = "trans_msg_srce_sys_nm", length = 20, nullable = false)
    var transactionMessageSourceSystemName: String? = "",

    @Column(name = "prog_nm", length = 30, nullable = false)
    var programName: String? = "",

    @Type(type = POSTGRES_DATE_TIME)
    @Column(name = "creat_ts", nullable = false)
    var createTimestamp: OffsetDateTime? = currentOffsetDateTimeInUTC,

    @Column(name = "trans_type_nm", length = 20, nullable = false)
    var transactionTypeName: String? = "",

    @Column(name = "trans_am", precision = 19, scale = 2, nullable = false)
    var transactionAmount: BigDecimal? = BigDecimal.ZERO,

    @Column(name = "trans_curr_cd", length = 3, nullable = false)
    var transactionCurrencyCode: String? = "",

    @Column(name = "creat_user_id", length = 34, nullable = false)
    var createdUserId: String? = "",

    @Type(type = POSTGRES_DATE_TIME)
    @Column(name = "trans_msg_rcv_ts")
    var transactionMessageReceivedTimestamp: OffsetDateTime? = currentOffsetDateTimeInUTC
)
```

**Comment by DavideD** [comment]
We need to parse the query before running it, it's possible that something goes wrong when we replace the parameters.
Are you using Quarkus?

**Comment by LazaroR94** [comment]
Yes I am using Quarkus. I am specifically using `Mutiny.SessionFactory` with this extension function to interact with the database:
```
fun <T> Mutiny.SessionFactory.execute(
    func: (Mutiny.Session) -> Uni<T>
): Uni<T> =
    this.openSession().chain { session ->
        session.withTransaction { func.invoke(session).eventually(session::flush) }
            .eventually(session::close)
    }
```

**Comment by LazaroR94** [comment]
The insert seems to be the only thing working for me, any other update/query gives me that error. I'm using Quarkus **2.14.x** and I have worked on another service before on Quarkus **2.9.x** and there was never an issue with updates.

**Comment by DavideD** [comment]
I've create a test project based on the info you gave me: https://github.com/DavideD/quarkus-issues/tree/main/quarkus-1427

If you can let me know what I need to do to see the error, I might be able to help you.
Currently, it seems to work fine.

**Comment by LazaroR94** [comment]
I apologize Davide, I was able to find my fault. After further debugging I found out the issue lied with another entity class and me accidentally applying the `executeUpdate()` function on a SELECT query. After removing that everything is now working just fine.

**Comment by DavideD** [comment]
No problem
