### ISSUE TITLE
Add link to the docs of the Vert.x DB2 client

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#144]
In the [README](https://github.com/hibernate/hibernate-reactive/blob/master/README.md#compatibility) we have a link for the other clients but it's missing for DB2.

That's because the section has not been added to the [Vert.x website](https://vertx.io/docs/) yet.
I've created this issue so that we don't forget about it

**Comment by gavinking** [comment]
@DavideD you fixed this and forgot to close the issue :-)

**Comment by DavideD** [comment]
Thanks, completely forgot about it :)

Fixed in #287
