### ISSUE TITLE
Distinct with QueryHint PASS_DISTINCT_THROUGH

### ISSUE THREAD

**Issue by holomekc** [hibernate/hibernate-reactive#1441]
Hi team,

I need to use distinct in my query. So that duplicates because of a fetch join are handled properly. Nearly everywhere it is highly recommended to use query.setHint(QueryHints.PASS_DISTINCT_THROUGH, false). See: https://www.baeldung.com/java-hql-distinct

I see no way how I can do that in Hibernate Reactive. The only totally crazy way I came up with is:

```java
    private static void addDistinctHint(final Mutiny.Query<?> query) {
        final MutinyQueryImpl<?> q = (MutinyQueryImpl<?>) query;
        try {
            final Field delegate = q.getClass().getDeclaredField("delegate");
            delegate.setAccessible(true);

            ((ReactiveQueryImpl<?>) delegate.get(q)).setHint(QueryHints.PASS_DISTINCT_THROUGH, false);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
```

Am I missing something? I mean it works but it is super ugly and unstable in case you decide to change the delegate field. The query by the session should allow setting hints as usual.

Without this option when I use distinct I am again facing other issues:
1. Inefficient because I have a lot of columns I am selecting, which are compared due to distinct.
2. Failing because we have json types. Can workaround with jsonb though

**Comment by gavinking** [comment]
> ly. Nearly everywhere it is highly recommended to use1 query.setHint(QueryHints.PASS_DISTINCT_THROUGH, false)`.

This was a feature that was a personal hobby horse of _one person_ who no longer develops Hibernate. I consider it a complete misfeature, and I removed it from Hibernate 6.

If you do _not_ require `distinct` to be applied at the database level, and just want to make things distinct in Java, then Java has a built-in feature for that called `HashSet`. You just type:

```java
new HashSet(session.createQuery("....")).getResultList())
```

Easy huh? And typesafe, unlike stupid stringly-typed query hints.

**Comment by gavinking** [comment]
> The query by the session should allow setting hints as usual.

FTR, no it should not. The stringly-typed query hints are _only_ for use with JPA-standard APIs, where the typesafe versions of the operations are not available via the JPA APIs.

`QueryHints.PASS_DISTINCT_THROUGH` was a very special case where there was not corresponding typesafe operation, because, as I said, it was a one-person hobby-horse feature that the rest of the team did not approve of.

**Comment by holomekc** [comment]
Ok. Thx for the quick answer. Then I will update it accordingly.
