### ISSUE TITLE
stream query results over Multi

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#153]
Now that we have a Mutiny-based API, we would like to have a method like `Query.getResultStream()` or something that returns query results via a `Multi`. This would be sorta a bit conceptually-similar to Hibernate's `ScrollableResults` (though not scrollable, obviously).

**Comment by gavinking** [comment]
So today I spent just a little bit of time playing with what the vert.x `SqlClient` offers here. If I'm not mistaken, the thing I'm supposed to be looking at is the support for cursors.

Aaand ... I guess I'm a little disappointed: I guess when people were talking about streaming results over a `Multi`, I figured that what we were thinking of was having the program be able to process the rows of a query result set one by one, as they were received by the client. I guess that was never said explicitly so this was really just me jumping to conclusions.

Now, if I'm not mistaken, that's *not* what this is about. What we have is really just an open cursor an the server, and when the client wants more rows, it explicitly asks for them, and they get sent back and processed as a chunk (`RowSet`). Honestly this doesn't seem very exciting to to me, it's really just the same sort of scrollable results processing that we've always had in Hibernate (and JDBC), and that hardly anybody has ever used, since it's almost always better to use query pagination.

Anyway, @vietj, please correct me if I'm wrong, and there's something I'm missing.

Also, @FroMage and @emmanuelbernard please tell me what was *your* understanding of what this feature was supposed to be about, because apparently I was just imagining something that simply doesn't exist.

**Comment by emmanuelbernard** [comment]
Right I did not have in mind the idea of keeping a DB cursor open to implement `Multi`. There is a difference though between `ScrollableResults` as Hibernate implements it and a `Multi` solution.
The back pressure and push vs pull. The API is vastly simpler to use because the `Multi` and the backpressure is wired up to the top (or rather bottom) of the stack. This is different than having to keep some Scrollable around.
Also exposing `Multi` as a type means clients participate in this transparent propagation (including via server side events).

The grudge with an explicit pagination is that you have to carry the state around. But yes underneath that `Multi` would be implemented with pagination.

That's my thoughts but I haven't spent hours on it.

**Comment by gavinking** [comment]
> The grudge with an explicit pagination is that you have to carry the state around. But yes underneath that `Multi` would be implemented with pagination.

Oh so the idea was that this would just be some total sugar on top of `setMaxResults()`/`setFirstResult()`, totally implemented as a wrapper, not something that went all the way back to the database client?

Must admit I'm struggling to see how you would even use this in a real program.

**Comment by FroMage** [comment]
We could start with implementing it as pagination until someone wants cursors indeed.

As for its usefulness, it's just the difference in API usability between `Uni<List<T>>` and `Multi<T>`. The first of which is a mix of two paradigms while the second is not.

I do wonder if we'll be able to map the multi paging methods to underlying DB paging though, but I suspect not:

```java
multi.transform().bySkippingFirstItems(start).transform().byTakingFirstItems(pageSize);
```

**Comment by gavinking** [comment]
> Right I did not have in mind the idea of keeping a DB cursor open
...
> We could start with implementing it as pagination until someone wants cursors indeed.

But @emmanuelbernard @FroMage my point is that _even if we did use cursors_, at least in the current API of Vert.x, what you're getting back from the database at each request is still a whole table of results, fully materialized.

Now, I honestly have no idea what's possible at the underlying database-native protocol level: perhaps there *is* some way to obtain results in a truly streaming fashion analogous to how you can stream stuff in HTTP. But if there is such a capability, it's not exposed.

(Further, it's never _ever_ been really very clear to me what are the performance implications of using `LIMIT` clauses vs. having the database itself track your current row on the server side with a cursor. I always *assumed* that cursors were more expensive in typical web architectures, but perhaps there are cases where cursors are efficient.)

So I'm trying to understand what is the real motivation for wanting to turn what is logically a `Uni<List>` into a `Multi`? Is it a pure programming convenience? In that case isn't there some sort of general operation in Mutiny for flattening `Uni<Iterable>` to `Multi`? Can we just call that and consider this issue "done".

Because right now it's just not even clear to me what it is we're even trying to do here.

**Comment by gavinking** [comment]
> In that case isn't there some sort of general operation in Mutiny for flattening `Uni<Iterable>` to `Multi`?

@cescofier I've actually looked for something like this a couple of times and didn't find it. I think I can see how to do it with an emitter but that looks a bit more verbose than it should be.

**Comment by emmanuelbernard** [comment]
Good points Gavin.

Converting Uni<List<?>> to `Multi<?>` is a possible solution., I was about to say "but then you have to load the whole list in memory". It turns out that with `Multi` you do too.

If we are to limit the amount of data in memory at a given time, we need a forward only mode to make sure we can drop objects that have been pushed to the `Multi` stream. But that also mean that we either need to detach objects from the session as soon as we load them, or that we do detach them regularly. That means that a "endless" stream personified by `Multi` would get a different semantic than the other queries returning `Uni<List<?>>`.

We could technically say that `Multi` hides a pagination logic but keep objects attached. The idea being that it would be an optimistic model where we hope people will only fetch the top n most of the time. To implement the UI infinite list pattern, that's handy.

**Comment by cescoffier** [comment]
To create a Multi from an Iterable, just use `Multi.createFrom().items(iterable)`. 
If you have a cursor like API, use:

```
Multi<String> stream = Multi.createBy().repeating()
        .uni(
                () -> new AtomicInteger(),
                state -> api.getNextChunk(state.getAndIncrement()))
        .until(list -> list.isEmpty())
        .onItem().disjoint();
```

**Comment by gavinking** [comment]
> But that also mean that we either need to detach objects from the session as soon as we load them, or that we do detach them regularly.

Right, that's the semantics of `StatelessSession`.

**Comment by gavinking** [comment]
> To create a Multi from an Iterable

Not from an `Iterable`, @cescoffier, for a `Uni<Iterable>`.

I expected to find something like this:

```java
Uni<List<Book>> results = session.createQuery(...).getResultList();
Multi<Book> resultStream = Multi.createFrom().iterableUni(results);
```

But I didn't find anything obvious.

> If you have a cursor like API

I think it's a bit more involved that that: the Vert.x client API for cursors is rather a mess of callbacks. But I'm not even going to go *there* right now.

**Comment by cescoffier** [comment]
So, it should be something like:

```

Multi<Book> books = session.createQuery(...).getResultList()
  .onItem().produceMulti(list -> Multi.createFrom().iterable(list));

```

**Comment by gavinking** [comment]
@cescoffier right, sure, OK, that would work.

I would still prefer a shortcut for it though.

**Comment by gavinking** [comment]
Well, I've added an operation that just transforms the result list to a `Multi`.

I'm not going to do anything more work than that unless we have a really well-defined and well-thought-out need and problem we're trying to solve and strategy for solving it.

Which we clearly don't have right now.

So I'm going to close the issue now.

**Comment by emmanuelbernard** [comment]
I think @FroMage , you and I should have a chat over... some fruit syrup to discuss that further.

**Comment by FroMage** [comment]
@emmanuelbernard you know my address for shipping said fruit syrup. I'd prefer cereal syrup if it's possible ;)
