### ISSUE TITLE
Detected call to non reactive method. Alternative reactive method: `reactiveAssemble` thrown when OneToOne mapping not joined/fetched

### ISSUE THREAD

**Issue by radovanradic** [hibernate/hibernate-reactive#1539]
Hello,

This again might not be an issue, but I am seeing inconsistent behavior in our code when moving from hibernate-reactive 1.1.9 and hibernate 5.6.15 to hibernate-reactive 2.0.0.Alpha2 and hibernate 6.2.0.CR4.
Maybe I should not have opened issue if this in not an issue (didn't find discussions in this repo) but it can be closed anyway later.

Here are mapping classes: 
```
@Entity
public class Author {

    @Id
    private Long id;
    private String name;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "author")
    private List<Book> books;
   ...
}
@Entity
public class Genre {

    @Id
    @GeneratedValue
    private Long id;
    private String name;
   ...
}
@Entity
public class Book {

    @Id
    private Long id;
    private String title;
    private int pages;
    @ManyToOne(fetch = FetchType.LAZY)
    private Author author; 
    @OneToOne
    private Genre genre;
   ...
}
```
and for example these two methods in AuthorRepository 
```
public class AuthorRepository {

    private static final String GET_AUTHOR_QUERY = "SELECT author_ FROM com.example.domain.Author AS author_ LEFT JOIN FETCH author_.books author_books_ WHERE (author_.name = :name)";

    private static final String GET_AUTHOR_QUERY_WITH_JOINS = "SELECT author_ FROM com.example.domain.Author AS author_ LEFT JOIN FETCH author_.books author_books_ LEFT JOIN FETCH author_books_.genre author_books_genre_ WHERE (author_.name = :name)";

public Mono<Author> findByName(String name) {
        return Mono.fromCompletionStage(sessionFactory.withTransaction(session -> session.createQuery(GET_AUTHOR_QUERY, Author.class)
                .setParameter("name", name).getSingleResult()));
    }

    public Mono<Author> findByNameWithJoins(String name) {
        return Mono.fromCompletionStage(sessionFactory.withTransaction(session -> session.createQuery(GET_AUTHOR_QUERY_WITH_JOINS, Author.class)
                .setParameter("name", name).getSingleResult()));
    }
   ...
}
```
Method findByName doesn't join book->genre while findByNameWithJoins does. When executing, findByName throws an error
```
org.hibernate.HibernateException: HR000075: Detected call to non reactive method. Alternative reactive method: `reactiveAssemble`
	at org.hibernate.reactive.sql.results.graph.ReactiveDomainResultsAssembler.assemble(ReactiveDomainResultsAssembler.java:26)
	at org.hibernate.sql.results.graph.entity.AbstractEntityInitializer.extractConcreteTypeStateValues(AbstractEntityInitializer.java:1039)
```
apparently trying to assemble Graph field in the Book entity but since it's not joined/fetched in the query then resolved assembler is `ReactiveDomainResultsAssembler`
![Screenshot 2023-03-28 at 13 33 54](https://user-images.githubusercontent.com/10271067/228226001-ed3f7a20-b731-4ad6-a886-2b2db78d180d.png)

and it throws an error from the issue title.
When Genre is explicitly joined/fetched in the query then it works fine as appropriate assembler is resolved. I think in prev version behavior is that field Genre would not be tried to be resolved and would just return null. Here is attached example in hibernate-reactive2 with hibernate6 that fails as explained.
[hibernate-reactive2-joins.zip](https://github.com/hibernate/hibernate-reactive/files/11088894/hibernate-reactive2-joins.zip)
And the one with hibernate-reactive1 and hibernate5 not failing on either method, whether Genre is being fetched or not.
[hibernate-reactive1-joins.zip](https://github.com/hibernate/hibernate-reactive/files/11088893/hibernate-reactive1-joins.zip)

So, just wanted to ask if this is an issue or we just have to join all mappings in the queries with new hibernate reactive?

Thanks

**Comment by radovanradic** [comment]
Great, thank you!

**Comment by DavideD** [comment]
Thanks for the test case.

I've checked your test case and I can confirm that the error disappear when I use the latest Hibernate Reactive snapshot
