### ISSUE TITLE
allow replacement of the ReactiveConnectionPool

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#154]
If we let users replace the `ReactiveConnectionPool`, they could in principle integrate different database drivers.

**Comment by Sanne** [comment]
This is already possible, if the users aren't too scared to inject a custom implementation into the bootstrap registry: provided services take precedence over the ServiceInitiator.

So while this will be easy for us, for example in Quarkus, did you mean we should make it "easier" for end users?

**Comment by Sanne** [comment]
I just see the PR now.

Are you aware you can inject custom service implementations at boot by doing:

    StandardServiceRegistry registry = new StandardServiceRegistryBuilder()
				.applySettings( properties )
				.addService( ReactiveConnectionPoolProvider.class, someCustomImplementationInstance );
				.build();

**Comment by gavinking** [comment]
No it's not possible because there was no *well-defined*, *well-specified* API for doing it.

> So while this will be easy for us, for example in Quarkus, did you mean we should make it "easier" for end users?

Exactly. They need a well-defined published API for that.

> Are you aware you can inject custom service implementations at boot by doing:

I am indeed aware of that. That's the functionality my PR takes advantage of.

**Comment by gavinking** [comment]
> No it's not possible

Also, up until yesterday it wasn't possible at all because `ReactiveConnection` leaked Vert.x-specific types in its APIs. But I already fixed that as a preliminary to this.

**Comment by Sanne** [comment]
ah, so the gist of your change is that you shift the focus to a new `Service` which abstracts from `ReactiveConnection` ?

**Comment by gavinking** [comment]
My change makes it clear that `ReactiveConnectionPool` and `ReactiveConnection` are user-implementable APIs, and that our Vert.x-based default implementation (`SqlClientPool` and `SqlClientConnection`) is "hidden" from the rest of Hibernate Reactive.

Previously this code was scattered almost at random across three different packages and it wasn't clear what was API and what was implementation.

**Comment by gavinking** [comment]
Also if I'm not mistaken, there used to be a warning from Hibernate because the `StandardServiceInitiator` for the `ReactiveConnectionPool` claimed to be a service implementation for the implementation class instead of for the service API interface. (Even though the client code was correctly requesting the service API interface.)

**Comment by DavideD** [comment]
Merged

**Comment by gavinking** [comment]
Thanks, done.

**Comment by Sanne** [comment]
Ok, sounds great. I'll start my second wave of conflict resolutions :)

**Comment by gavinking** [comment]
> I'll start my second wave of conflict resolutions :)

Yeah, sorry about that. :-(
