### ISSUE TITLE
Queries using EntityGraph and maxResults don't return all items in joined collection

### ISSUE THREAD

**Issue by radovanradic** [hibernate/hibernate-reactive#1551]
Hello,

This might be the case of misusing API perhaps, but some of our tests using EntityGraph started failing with hibernate reactive 2 alpha. We have these example entities
```
@Entity
public class Author {

    @Id
    @GeneratedValue
    private Long id;

    private String name;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "author")
    private Set<Book> books;
    ...
}

@Entity
public class Book {

    @Id
    @GeneratedValue
    private Long id;

    private String title;

    private int pages;

    @ManyToOne(fetch = FetchType.LAZY)
    private Author author;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "book")
    private List<Chapter> chapters = new ArrayList<>();
    ...
}

@Entity
public class Chapter {

    @Id
    @GeneratedValue
    private Long id;

    private String name;

    @ManyToOne
    private Book book;
    ...
}
```
and method in `AuthorRepository`
```
private static final String FIND_AUTHOR_BY_NAME_LIKE_QUERY = "SELECT a FROM org.example.domain.Author AS a WHERE (a.name LIKE :name)" +
            " ORDER BY a.name";

public Mono<Author> findByNameLike(String name) {
        return Mono.fromCompletionStage(sessionFactory.withTransaction(session -> {
            Stage.Query query = session.createQuery(FIND_AUTHOR_BY_NAME_LIKE_QUERY, Author.class)
                    .setParameter("name", name);
            query.setHint("jakarta.persistence.fetchgraph", createEntityGraph(session));
            query.setMaxResults(1);
            return query.getSingleResult();
        }));
    }

    private EntityGraph<Author> createEntityGraph(Stage.Session session) {
        RootGraph<Author> rootGraph = (RootGraph<Author>) session.createEntityGraph(Author.class);
        rootGraph.addAttributeNode("books");
        Graph<?> graph = rootGraph.addSubGraph("books");
        graph.addAttributeNode("chapters");
        return rootGraph;
    }
```
If we have author and 2 books, this method will return only one book. Most likely because of setMaxResults(1) and query adding `fetch first $2 rows only` that worked differently in hibernate reactive 1.1.9. Also, method with explicit joins and setMaxResults returns correct join collection. It works correctly with non reactive hibernate.
Like I said, maybe using setMaxResults is not considered to be used with this case, but we have this used in some generic API and can't have workaround currently.

Attaching hibernate 2 and 1.1.9 examples to reproduce behavior if needed.
[hib-entitygraph-reactive2.zip](https://github.com/hibernate/hibernate-reactive/files/11135793/hib-entitygraph-reactive2.zip)
[hib-entitygraph-reactive1.zip](https://github.com/hibernate/hibernate-reactive/files/11135792/hib-entitygraph-reactive1.zip)

Thanks,
Radovan

**Comment by agreedSkiing** [comment]
Having a simliar or maybe the same issue with the Mutiny.SessionFactory where you can't event do `query.setHint`

**Comment by DavideD** [comment]
Ah, this issue fell under the radar. I will have a look soon

**Comment by DavideD** [comment]
I've tested this with the latest Hibernate Reactive and I think it's a bug in Hibernate ORM.
Basically, if the HQL query looks like this:
```
FROM Author a WHERE a.name LIKE :name ORDER BY a.name
```
it will add `fetch first ? rows only` to the end of the SQL query:
```
 select a1_0.id,b1_0.author_id,b1_0.id,c1_0.book_id,c1_0.id,c1_0.name,b1_0.pages,b1_0.title,a1_0.name from Author a1_0 left join Book b1_0 on a1_0.id=b1_0.author_id left join Chapter c1_0 on b1_0.id=c1_0.book_id where a1_0.name like ? escape '' order by a1_0.name fetch first ? rows only
```
 This means that it won't return all the associated elements.

But, if I change the HQL and fetch the collections, it works as expected. This HQL:
```
FROM Author a left join fetch a.books b left join fetch b.chapters WHERE a.name LIKE :name ORDER BY a.name
``` 
the SQL becomes:
```
select a1_0.id,b1_0.author_id,b1_0.id,c1_0.book_id,c1_0.id,c1_0.name,b1_0.pages,b1_0.title,a1_0.name from Author a1_0 left join Book b1_0 on a1_0.id=b1_0.author_id left join Chapter c1_0 on b1_0.id=c1_0.book_id where a1_0.name like ? escape '' order by a1_0.name
```

without limiting the results in the SQL.

But I don't see any difference between Hibernate ORM or Reactive in terms of behaviour in the latest version.
I've created a test case that uses ORM and Reactive: https://github.com/DavideD/hibernate-reactive/commit/1e5e9c0109dc3b2e97d1a03da05d1e5b195de259#diff-8e8a62954bbe01f50f87992c231ad3bd081e1b5cc4b063c5a4317d2b8d55f30fR143
 
@gavinking, I think this is a bug in Hibernate ORM. Or am I missing something?

**Comment by gavinking** [comment]
[There's a big difference between Hibernate 5 and 6 here.]

**Comment by gavinking** [comment]
But the issue description is extremely unclear, and I'm not sure what it is that the user is claiming is wrong.

**Comment by DavideD** [comment]
The issue is about the fact that the user expects to retrieve all the books from the selected author. But when setting `.setMaxResults(1)`, the books association in author only contains one book (instead of the whole collection) . If I understand correctly, this happens because collections aren't eagerly fetched.

**Comment by gavinking** [comment]
> The issue is about the fact that the user expects to retrieve all the books from the selected author. But when setting `.setMaxResults(1)`, the books association in author only contains one book (instead of the whole collection) 

If I understand correctly, this describes the legacy behavior of Hibernate prior to H6. 

In H6, this should not occur.

**Comment by DavideD** [comment]
I've tested this with H6. I think it's still happening.
You can check the test I wrote here: https://github.com/DavideD/hibernate-reactive/blob/1e5e9c0109dc3b2e97d1a03da05d1e5b195de259/hibernate-reactive-core/src/test/java/org/hibernate/reactive/types/EntityGraphTest.java#L111

Maybe I've missed something.

**Comment by gavinking** [comment]
I'm not really sure what the subtleties are, since I didn't work on this.  Better ask @sebersole

**Comment by gavinking** [comment]
OK, now I see what's going on. So this is very specific to the use of `Query.setEntityGraph()` and does not affect the same query written with `join fetch`. And it's indeed a bug in core, so it should be reported there.

**Comment by DavideD** [comment]
I've created an issue for Hibernate ORM: https://hibernate.atlassian.net/browse/HHH-17698
