### ISSUE TITLE
pass the DatabaseVersion to the Dialect constructor

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#1564]
In Hibernate 6, we are supposed to pass a `DatabaseVersion` to the constructor of the `Dialect`. This is really important, because if we don't do it, the dialect defaults to an old version of the database.

Vert.x exposes this info via `DatabaseMetadata`.

It's critical we get this fixed before the release.

**Comment by DavideD** [comment]
I have a prototype ready: https://github.com/hibernate/hibernate-reactive/pull/1575

**Comment by gavinking** [comment]
> I have a prototype ready: #1575

Super.
