### ISSUE TITLE
Document differences in supported features among dbs

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#158]
Mainly the one that could be surprising for a user when switching dbs.

For example, at the moment:
- Some types are not supported by DB2
~~Db2 does not support column names with underscore~~
- I'm sure there is something that doesn't work for MySQL

**Comment by gavinking** [comment]
Would it be better if this were documented by the SQL Client team, and we gave a link?

Or is that expecting too much?

**Comment by DavideD** [comment]
I think that would work. And it would be useful for them as well to have a page as well.
We might do a better job in highlighting which mapping may cause problems though.
Like, a limitation in the username length is not going to affect the mapping of the entity (I think)

**Comment by aguibert** [comment]
I agree with @gavinking that driver limitations (e.g. DB2 client not supporting some data types) should be documented by the Vertx SQL client, and we should just reference that.

More generally, the documentation of limitations should be where the source of the limitation is. In the case of Java types, that's the driver, but in the case of column names not being able to start with an underscore, that's a long-standing limitation / design decision of the DB2 database itself. I'm all for collecting up links to the limitation pages to help the user find them more easily though.

**Comment by DavideD** [comment]
Can you use '$' instead of underscore?

**Comment by aguibert** [comment]
Not sure off the top of my head, I'd have to check

**Comment by DavideD** [comment]
Sorry, I got distracted.

There  are some situations where it's not obvious how the mapping will translate. For example, if you declare an inner class as an entity the name of the table will contain a $ that might not be supported by the db. It would be nice to add them because the user might not know where is the problem.

**Comment by DavideD** [comment]
> There are some situations where it's not obvious

I mean ... if one is not familiar with the library.

**Comment by aguibert** [comment]
> There are some situations where it's not obvious how the mapping will translate. For example, if you declare an inner class as an entity the name of the table will contain a $ that might not be supported by the db. It would be nice to add them because the user might not know where is the problem.

This shouldn't be any different than the limitations we already have with ORM+DB2 though. Could we just refer to that existing documentation if it exists?

Also, dollar signs in table names (i.e. inner class entities) works fine. It's just the first char being an underscore in a column name was the particular issue I ran into.

**Comment by DavideD** [comment]
Probably the column one was a bad example. I will remove it

**Comment by DavideD** [comment]
> This shouldn't be any different than the limitations we already have with ORM+DB2 though. Could we just refer to that existing documentation if it exists?

Sure, but if we know that a particular mapping is not supported, why not to add it?

Anyway, this is something that we don't have to do now. if at the time of a semi-stable release we don't have any meaningful limitations that we want to add, we can close it.

**Comment by DavideD** [comment]
But let's wait until we have the test suite fixed.

**Comment by gavinking** [comment]
> I'm sure there is something that doesn't work for MySQL

Currently we don't have any disabled tests for MySQL. So I think that's fixed.

With respect to DB2 limitations, if @aguibert wants to document them somewhere, then great. (The README is perhaps not the best place, perhaps in a separate file.)

Otherwise, I would say we can close this issue.

**Comment by aguibert** [comment]
Perhaps we could add a link to the Vertx driver limitations in our limitations section? https://github.com/hibernate/hibernate-reactive#limitations

**Comment by gavinking** [comment]
> Perhaps we could add a link to the Vertx driver limitations in our limitations section?

Yes, that's fine by me. But does the limitations list you want to link to exist yet?

**Comment by aguibert** [comment]
yes, we are building the list up here in source form on the DB2 driver:
https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-db2-client/src/main/asciidoc/index.adoc#reactive-db2-client
I'll raise an issue to ensure we document limitations for all drivers besides just DB2 within Vertx

This will be published on vertx.io documentation once the next release goes out

**Comment by DavideD** [comment]
> Perhaps we could add a link to the Vertx driver limitations in our limitations section? https://github.com/hibernate/hibernate-reactive#limitations

That's fine by me

**Comment by gavinking** [comment]
By the way, @aguibert I noticed that when I enabled the prepared statement cache on DB2, it resulted in a couple of failures in our test suite. Might be worth looking in to.

**Comment by gavinking** [comment]
I added the link to the readme.

Closing this for now.
