### ISSUE TITLE
Upgrade the test suite to JUnit 5

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1582]

**Comment by blafond** [comment]
@DavideD

I pushed my latest and rebased :  https://github.com/blafond/hibernate-reactive/commits/JUnit5-upgrade

840 tests    
53 failures ( in 22 test classes)
121 ignored  (PostgreSQL)

Couple notes:

- The SqlStatementTracker is being "registered" as a service, but isn't getting called so 4 test classes failing

```
OrderQueriesTestBase.java
InsertOrderingReferenceSeveralDifferentSubclassBase.java
BatchingConnectionTest.java
FetchedAssociationTest.java
```

- `DatabaseSelectionRule` implements `ExecutionCondition` and correctly checks the relevant DB's  However,  there are some cases where the test is disabled (i.e. Running PG with a rule that "runOnlyFor(MYSQL)") but looks like this error reflects that the `VertxTestContext` is active and we aren't completing/closing it if no tests are run.

**Comment by DavideD** [comment]
I bet you have changed something in `BaseReactiveTest` and now `constructConfiguration` doesn't get called at the right time

**Comment by blafond** [comment]
@DavideD 
Pushed my latest.  Down to 5 failures in 2 test classes:
```
ReactiveConnectionPoolTest. configureWithCredentials(VertxTestContext)
ReactiveConnectionPoolTest. configureWithJdbcUrl(VertxTestContext)
ReactiveConnectionPoolTest. configureWithWrongCredentials(VertxTestContext)
SchemaUpdateTestBase$GroupedStrategyTest. testMissingColumnsCreation(VertxTestContext)
SchemaUpdateTestBase$IndividuallyStrategyTest. testMissingColumnsCreation(VertxTestContext)
```

**Comment by blafond** [comment]
@DavideD 
[JUnit5-upgrade](https://github.com/blafond/hibernate-reactive/tree/JUnit5-upgrade) branch builds without error with PostgreSQL locally for me

- MySQL, SQLServer, CockroachDB and MariaDB mostly build with 5 or less failures
- DB2 & Oracle mostly don't work at all.

Don't think it's not ready for a PR... but it's rebased to main as of this morning.

**Comment by blafond** [comment]
I'm converting [integration-tests package to JUnit5](https://github.com/blafond/hibernate-reactive/tree/junit5-integration-tests) and have run into an issue.

The build log contains:
```
Execution failed for task ':bytecode-enhancements-it:test'.
> No tests found for given includes: [org.hibernate.reactive.it.LazyBasicFieldTest](--tests filter)
```

Searched similar issues and from what I can tell, there could be a dependency that still uses JUnit4.  I checked that 
 package's build.gradle and it appears that dependencies use JUnit5
