### ISSUE TITLE
Add releases to GitHub releases

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1583]
Our releases should appear [here](https://github.com/hibernate/hibernate-reactive/releases) with the extra info.
This is something that we need to integrate with the release process.

**Comment by blafond** [comment]
Creating a release by hand with a `tag` and a PR isn't hard. (https://github.com/blafond/hibernate-reactive/releases/tag/v1.1.test)

Looking at Quarkus, they are using [JReleaser](https://jreleaser.org/guide/latest/index.html) to integrate their build/test/release scripts.

Going to chat with Guilliame tomorrow to ask him some questions on if/how they customize the generated GIT release output content.

**Comment by blafond** [comment]
Installed cli.github and executed this feature: https://cli.github.com/manual/gh_release_create

Was able to mimic github's UI for create new release:   `gh release create v3.0`  It appeared that the options were similar to the UI experience plus some additional ways to specify release notes

A few options we might implement:
```
Use release notes from a file
$ gh release create v1.2.3 -F changelog.md

Upload all tarballs in a directory as release assets
$ gh release create v1.2.3 ./dist/*.tgz

Upload a release asset with a display label
$ gh release create v1.2.3 '/path/to/asset.zip#My display label'
```

**Comment by DavideD** [comment]
I'm closing this one because we are going to add them manually for now. I will create a new issue related to the whole release process when we have time to improve it
