### ISSUE TITLE
MSSQL deadlocks on sequence increase under load

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#1609]
When running `MultithreadedInsertionTest` and/or `MultithreadedIdentityGenerationTest` on SQL Server, one can occasionally see this error:

```
Transaction (Process ID 81) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.', serverName='cd70a22b97e5', lineNumber=1}] [select tbl.next_val from Entity_SEQ tbl with (updlock,holdlock,rowlock)]
```

I'm not sure why we explicitly attempt to use pessimistic locking hints, this seems and odd choice and we should ask the ORM team. Also surprising that a deadlock is reported - if it's being identified I wonder if we're running within a parent transaction, while typically the sequence increment should ignore it.

**Comment by DavideD** [comment]
The query contains the pessimistic lock because of this: https://github.com/hibernate/hibernate-reactive/issues/1596

Basically, we are using an old dialect.
There are still other issue when using the correct dialect version that I'm investigating.
