### ISSUE TITLE
Get all tests passing with MySQL

### ISSUE THREAD

**Issue by aguibert** [hibernate/hibernate-reactive#161]

**Comment by gavinking** [comment]
FYI I have fixed a bunch of the MySQL tests that were failing on my machine.

**Comment by gavinking** [comment]
So there's a bit of a minor problem however: in order to get stuff working on MySQL I had to set schema export back to `"create-drop"`, but that means we're back to having Vert.x complain about blocked threads. :-/

**Comment by gavinking** [comment]
> So there's a bit of a minor problem however

I have finally solved this, after wasting *way* too much time on it.

**Comment by gavinking** [comment]
It seems to me that this can be closed now.

**Comment by DavideD** [comment]
Any reason for keeping [MySQLBasicTest](https://github.com/hibernate/hibernate-reactive/blob/master/hibernate-reactive-core/src/test/java/org/hibernate/reactive/MySQLBasicTest.java)?

**Comment by gavinking** [comment]
> Any reason for keeping `MySQLBasicTest`?

Probably not.

**Comment by DavideD** [comment]
Deleted: https://github.com/hibernate/hibernate-reactive/commit/1dabb5abd86283ec4e03b1c5a5c22bf7956e6332

**Comment by gavinking** [comment]
You missed one: 05dda4b94c5866d3664694cb7897ba63aa7720be :-)

**Comment by aguibert** [comment]
@DavideD Also remember to add MySQL to CI under `.github/workflows/build.yml`

**Comment by aguibert** [comment]
If we do PRs on changes this will be a lot more obvious, and we get the validation of CI (as opposed to pushing directly to master)

**Comment by DavideD** [comment]
Thanks :)

**Comment by DavideD** [comment]
There is another test that has been disabled for MySQL: UUIDGeneratorTest @gavinking Did you look into it?

**Comment by gavinking** [comment]
Yeah, I looked briefly at it and the UUID is not being stored correctly by MySQL.

TBH I don't recall if this functionality is even supposed to work on MySQL in Hibernate ORM.

Sometime we should look at it more carefully.

**Comment by gavinking** [comment]
(I mean, *something* gets written to the MySQL table, just not a meaningful UUID.)

**Comment by gbadner** [comment]
@gavinking, @DavideD , there is a similar ORM [test](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/test/java/org/hibernate/id/uuid/GeneratedValueTest.java) using a generated UUID as ID.

That test maps the column as:
`		@Id
		@Column( length = 16 )
		@GeneratedValue
		public UUID id;
`
The ORM test passes using MySQL8. 

When I removed `@Column( length = 16 )`  from the ORM test, the entity could no longer be found, and the test failed.

After adding  `@Column( length = 16 )`  to the TableId#id mapping for `UUIDGeneratorTest`, that test passes.

Should I go ahead and push a commit enabling `UUIDGeneratorTest` for MySQL with the updated ID mapping using this issue (#161)?

**Comment by gavinking** [comment]
@gbadner ah, perfect, thanks!

**Comment by gavinking** [comment]
Right, because the column type is `binary`, not `varbinary`, it was getting padded with zeros.

**Comment by gavinking** [comment]
@gbadner were you going to push that fix, or shall I?

**Comment by gbadner** [comment]
@gavinking, I just pushed it.

**Comment by gavinking** [comment]
👍thanks
