### ISSUE TITLE
test SQL array and UDT support

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#1641]
Hibernate 6 introduces the `@Struct` and `@Array` annotations for mapping to SQL arrays and UDTs.

We should test this stuff. It's likely the Vert.x client doesn't support this stuff yet.

**Comment by DavideD** [comment]
@gavinking Are you already working on this? Otherwise I think this is one of the issues we can have a look this week

**Comment by blafond** [comment]
Pushed a couple tests around `@Struct` annotation:  [#1641](https://github.com/blafond/hibernate-reactive/tree/issue_1641)

Works for DB2, PG but fails for Oracle at the moment.
