### ISSUE TITLE
Reactive repository using micronaut and project reactor

### ISSUE THREAD

**Issue by fstolar-vendavo** [hibernate/hibernate-reactive#1668]
In Micronaut project we tried to use https://guides.micronaut.io/latest/micronaut-data-hibernate-reactive-gradle-kotlin.html
Everything seems to be fine until we test modifying operations like save or update.
Then we end up which this exception:
<img width="1452" alt="image" src="https://github.com/hibernate/hibernate-reactive/assets/108322242/36e8e98c-98a9-4e59-a304-1db39c8ad294">

I found that the method which was called onFlush is not implemented, thus throwing UnsupportedOperationException exception.
Is there any work I can do to help implement/solve that issue?

https://github.com/hibernate/hibernate-reactive/blame/c1d51e6d89d85dffa4fedc510e3b03d57b36c5cd/hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveFlushEventListener.java#L62

**Comment by DavideD** [comment]
That method should never gets called. I'm having a look

**Comment by DavideD** [comment]
Ah, I think this is the wrong repository.

This is `org.hibernate.reactive:hibernate-reactive-core`, but micronaut needs `io.micronaut.data:micronaut-data-hibernate-reactive`.

**Comment by DavideD** [comment]
There is probably something wrong with the dependencies in your project
