### ISSUE TITLE
How do I write query sql to configuration files, such as xml or json files, using reactive hibernate?

### ISSUE THREAD

**Issue by zuochangqin** [hibernate/hibernate-reactive#1676]
As flexible as mybatis configuration, you do not need to deeply bind sql with entities, because some complex queries can not be represented by entities, and with one-to-many, multi-to-one and other relational queries, sometimes very complex, but also prone to problems.

**Comment by DavideD** [comment]
I don't think Hibernate Reactive or ORM have an out-of-the-box feature for this.

But, depending on your use case, you can save the queries as constants in a class or interface, or save them in a properties file and read them with regular Java.

@gavinking any suggestion?
