### ISSUE TITLE
support StatelessSession.upsert()

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#1702]
`StatelessSession` has a new `upset()` operation. We should add a reactive version.

**Comment by blafond** [comment]
Waiting on changes to some method visibility in ORM:  
[HHH-17204](https://hibernate.atlassian.net/browse/HHH-17204)
[Relax visibility of some methods for reactive upsert() support](https://hibernate.atlassian.net/browse/HHH-17204)

[PR #7318](https://github.com/hibernate/hibernate-orm/pull/7318)

**Comment by gavinking** [comment]
Great! Thanks!
