### ISSUE TITLE
Fix deprecations due to changes in ORM

### ISSUE THREAD

**Issue by blafond** [hibernate/hibernate-reactive#1714]
Fixes #1714

Includes changes to uses of Loadable, EntityMetamodel, Type and getProperty()

**Comment by blafond** [comment]
Created ORM issue [HHH-16999](https://hibernate.atlassian.net/browse/HHH-16999) and submitted a [PR](https://github.com/hibernate/hibernate-orm/pull/7079) to help reduce redundancy and simplify reactive code

Will utilize these changes in ORM for this issue.

**Comment by blafond** [comment]
Created a [draft PR](https://github.com/hibernate/hibernate-reactive/pull/1715) for reactive changes

**Comment by DavideD** [comment]
Waiting for the next ORM release

**Comment by DavideD** [comment]
Superseded by https://github.com/hibernate/hibernate-reactive/pull/1771
