### ISSUE TITLE
Add support for `Order`

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1735]
Related to https://github.com/hibernate/hibernate-reactive/issues/1706

See the new class in ORM: [org.hibernate.query.Order](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/query/Order.java)

**Comment by DavideD** [comment]
We need to wait for this change to be merged: https://github.com/hibernate/hibernate-orm/pull/7260

**Comment by blafond** [comment]
Pushed my first attempt at implementing `setOrder(....)` in reactive.  [issue_1735_order_support](https://github.com/blafond/hibernate-reactive/commits/issue_1735_order_support)
