### ISSUE TITLE
Support `{h-schema}`, `{h-domain}`, or `{h-catalog}` in native query

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1737]
See https://docs.jboss.org/hibernate/orm/6.3/userguide/html_single/Hibernate_User_Guide.html#sql-global-catalog-schema

**Comment by gavinking** [comment]
@sebersole is this still a documented feature or is it something that's been deprecated or is being phased out?

**Comment by sebersole** [comment]
I wasn't planning on removing it no

**Comment by gavinking** [comment]
OK thanks then we should support it:
