### ISSUE TITLE
Add support for soft deletes

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1787]
Hibernate ORM 6.4 introduces soft deletes, we should check if the new feature also works in Hibernate Reactive

Hibernate ORM docs: https://docs.jboss.org/hibernate/orm/6.4/userguide/html_single/Hibernate_User_Guide.html#soft-delete

**Comment by blafond** [comment]
@DavideD I"m making some progress.  I"ve created 2 tests on my [branch](https://github.com/blafond/hibernate-reactive/commit/fcbe5fcf46c2b17cfecf92dc03295f1e2bd05c85).  ORM has a bunch of different @SoftDelete tests and checks not only query results but metadata from the session metamodel.  I'm assuming we should stick to the query tests.
