### ISSUE TITLE
entity loaders design issue

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#181]
The entity loaders currently override the `load()` method of `UniqueEntityLoader` and refine its return type to `CompletionStage`. This was an OK hack to get started, but we should migrate this code to use `reactiveLoad()` methods since this stands in the way of fixing #40.

**Comment by DavideD** [comment]
I'm going to close this issue because it doesn't seem relevant anymore and with Hibernate 6 everything related to the loaders has changed anyway
