### ISSUE TITLE
check tests currently disabled for certain dialects

### ISSUE THREAD

**Issue by blafond** [hibernate/hibernate-reactive#1823]
A number of tests are currently disabled due to errors for specific dialects.

Re-run these tests and enable if tests work.

**Comment by DavideD** [comment]
Ok, but make sure that there is an issue for each disabled test so that we don't forget about them

**Comment by blafond** [comment]
sure thing.

Here's my first pass:  https://github.com/blafond/hibernate-reactive/commit/240187281261e15438c9c44aeb8b578e93023d76

**Comment by DavideD** [comment]
Mmmh.... OK. But from the description of the issue I didn't expect this kind of refactoring.
Could you update the description and title?

Is this issue about checking which tests we might enable, or is it about removing the custom extension for JUnit? Or both?

**Comment by DavideD** [comment]
I think this has been superseded by #1827
