### ISSUE TITLE
Document and test second-level cache options

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#184]
At some stage we'll have to spend some more time thinking about what our story is with respect to second-level cache.

**UPDATE**

By story I mean we need to be able to give users one or two options which are:

1. tested, and
2. documented.

Because right now we have not tested the second level cache *at all* with HR.

**Comment by Sanne** [comment]
In Quarkus - currently - we only support local caching: no distributed stuff:
 - https://quarkus.io/guides/hibernate-orm#limitations-of-caching

There's an issue to improve on that - as there's also a need for caches which are able to maintain consistency across multiple nodes - but that's a problem to be solved later.

So for now I'd propose that Hibernate Reactive also supports local caching exclusively: this implies we won't need to worry about the cache blocking the background on network operations. However even local caches might still need a quick in-memory lock, such as access to a synchronized block of code..  might be acceptable for reactive code to use these as-is ?

I don't know how often they'd block and what the impact would be on a reactive application. @FroMage might have an opinion?

**Comment by Sanne** [comment]
FWIW, while extensively profiling applications using in-memory 2LC we'd never see contention so I'm not particularly concerned about it - just bringing it up for completeness.

**Comment by gavinking** [comment]
> So for now I'd propose that Hibernate Reactive also supports local caching exclusively

Wellyes, that's pretty much what we already say in the README.

> In Quarkus - currently - we only support local caching

OK, well, in that case perhaps we *don't* need a better story for now...

> However even local caches might still need a quick in-memory lock, such as access to a synchronized block of code.. might be acceptable for reactive code to use these as-is ?

IMO that's totally fine. It's IO we care about. A `synchronized` block around what is essentially a hashmap lookup shouldn't be any sort of problem at all.

**Comment by gavinking** [comment]
Actually this issue description wasn't well-written at all. The things I was thinking of was really mainly just actually documenting and testing one or two cache options that we think *are* good choices for HR.

The thing is if a user asks me today what cache they should use with HR and will it actually work I will simply have no answer to them, knowhatimean?

**Comment by Sanne** [comment]
Cool. In Quarkus we can then enable the same 2LC implementation which we have for the existing ORM.

**Comment by Sanne** [comment]
> The thing is if a user asks me today what cache they should use with HR and will it actually work ... I will simply have no answer to them, knowhatimean?

Right, we need to document what's ok.  Many caches though (notably Infinispan and Ehcache) can be configured both in local and in clustered mode - we don't really know how they are setup.

So we need to warn that they shouldn't be configured to use blocking operations.

**Comment by gavinking** [comment]
But we also need to test it for ourselves. There is HR code in the codepath to the cache.

**Comment by gavinking** [comment]
@Sanne @sebersole 

So while I was working on this one, I came across something a little surprising which is that executing a HQL `update` or `delete` query doesn't seem to evict entities of the updated/deleted type from the cache.

It looks to me like this should in principle be rather straightforward to implement, since the query certainly knows which entry it is updating/deleting and can discover the cache region directly.

Have I done something wrong or is this something that's normal?

Should we fix it?

**Comment by sebersole** [comment]
That's really strange.  There is code to handle it -
`org.hibernate.action.internal.BulkOperationCleanupAction`

Maybe you've hit a path where that does not happen.  Is this a multi-table
entity?  Depending, have a look at `BasicExecutor#doExecute` or the 2
multi-table forms for update/delete.  *Looking* at the code, I do not see
how that does not happen, but devils-in-the-details and you have the
details :)  Or you can get me a test case and I can look into it.

**Comment by gavinking** [comment]
Ah, OK, thanks Steve, then this is surely a bug in Hibernate Reactive, possibly related to #237.

Probably @gbadner knows, but anyway, I will investigate further.

**Comment by gavinking** [comment]
I've tracked down the source of the problem, but it's definitely not trivial to fix. I will probably need to patch hibernate-core.

**Comment by sebersole** [comment]
I'm not in the weeds with you so hard to say.  But in theory it should not
be difficult.  At the end of the day it is simply built on top of
`org.hibernate.action.spi.AfterTransactionCompletionProcess`

**Comment by gavinking** [comment]
> But in theory it should not be difficult.  

Actually scratch what I said: I think it's totally straightforward. Sorry for noise.

**Comment by sebersole** [comment]
NP

**Comment by gavinking** [comment]
Done!

The second-level cache is tested with JCache-based EHCache as the cache provider.

I've added documentation, and fixed the bug related to HQL update/delete queries.

**Comment by Sanne** [comment]
Awesome! I'll check if there's any need for changes in Quarkus.

**Comment by gavinking** [comment]
> Awesome! I'll check if there's any need for changes in Quarkus.

Yeah right, that's a good point, there's a f[air bit of configuration](https://github.com/hibernate/hibernate-reactive/blob/master/documentation/src/main/asciidoc/reference/introduction.adoc#enabling-the-second-level-cache) involved in setting up the second-level cache these days, and there needs to be a way to do all that via the extension.
