### ISSUE TITLE
Empty predicate array passed to where(predicates) result in NullPointerException

### ISSUE THREAD

**Issue by s4iko** [hibernate/hibernate-reactive#1860]
Hi,

I'm using Hibernate Reactive 3.7.1 (core 6.4.2) with criteria to build a delete query. 

The predicates are appended in a list converted to an array to pass them to `where(Predicate ... predicates)` method.
It works well when some predicates are given, but if none is, it results in an NPE.

A check probably should be done to verify if the predicate array is empty and if so, do not add the where clause at all.
It seems the code to modify is in hibernate-core:
```Java
org.hibernate.query.sqm.tree.AbstractSqmRestrictedDmlStatement.setWhere(Predicate...)

	protected void setWhere(Predicate... restrictions) {
		if(restrictions.length == 0) {
			// no predicate result to no where clause
			return;
		}
		final SqmWhereClause whereClause = initAndGetWhereClause();
		// Clear the current predicate if one is present
		whereClause.setPredicate(null);
		for ( Predicate restriction : restrictions ) {
			whereClause.applyPredicate( (SqmPredicate) restriction );
		}
	}
```

As a workaround (a bit ugly but avoid to modify to much existing code), always add a first predicate:
```
List<Predicate> predicates = new ArrayList<>();
predicates.add(cb.equal(cb.literal(1), cb.literal(1)));
// ...
```

Thanks for your great work !

**Comment by DavideD** [comment]
Thanks for the feedback.

The only `NullPointerException` I see is when restrictions is `null`.
But that's more a javadoc issue than anything. I guess we could check for it.

If that's the issue, your solution won't solve it.
Maybe, you could attach a stacktrace, or a testcase. With the current information, I don't see how that could happen.

I've tested it with the Hibernate Reactive 2.2.2.Final and ORM 6.4.2.Final using this simple test:
```java

	@Test
	public void testWhereClause(VertxTestContext context) {
		CriteriaBuilder builder = getSessionFactory().getCriteriaBuilder();
		CriteriaUpdate<Book> update = builder.createCriteriaUpdate( Book.class );
		Root<Book> b = update.from( Book.class );
		update.set( b.get( "title" ), "XXX" );
		Predicate[] restrictions = {};
		update.where( restrictions );
		test(
				context,
				getSessionFactory().withTransaction( session -> session.createQuery( update ).executeUpdate() )
		);
	}
```

In any case, this is an issue for Hibernate ORM: https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/?filter=allissues

Or Quarkus: https://github.com/quarkusio/quarkus/issues

But, please, make sure to provide a test case or some more information before opening a new issue.

I'm closing this issue for now, but feel free to ask more questions if you need advice.

Thanks
