### ISSUE TITLE
Reactive find with lock in Quarkus with reactive hibernate

### ISSUE THREAD

**Issue by alexjaravete** [hibernate/hibernate-reactive#1896]
Hi, when using Quarkus with reactive hibernate and trying to run this `findById(id, LockModeType.PESSIMISTIC_WRITE)`, I get following Error: `JPA error: java.lang.UnsupportedOperationException`

The error seems to be coming from here: 
https://github.com/hibernate/hibernate-reactive/blob/5cb015d24703a493d9d745f7df0aa4d362a19b28/hibernate-reactive-core/src/main/java/org/hibernate/reactive/event/impl/DefaultReactiveLockEventListener.java#L238-L241

Is this intended, or is the implementation not finished? I can see that the last time this was edited was 4 years ago.

**Comment by DavideD** [comment]
It seems lie a bug. We shouldn't call this method. We should call `.reactiveOnLock`.

**Comment by DavideD** [comment]
I've tried to change one of the quarkus quickstarts to see the error, but I couldn't recreate it.
Could you provide a reproducer, please?
Or, at least, you could tell what's different from your use case.

The changes are here: https://github.com/DavideD/quarkus-quickstarts/tree/findById/hibernate-reactive-panache-quickstart

**Comment by alexjaravete** [comment]
I tried your quickstart example and the error does not show up. 
The difference is that we are using Kotlin. 
But even after rewriting everything to Kotlin, the error still does not show up.
Now I am trying to find out what the difference between our set-up and the quickstart project is.

I will let you know if I can reproduce it in the quickstart project.

**Comment by DavideD** [comment]
Thanks.

I'm going to close this issue for now. Feel free to reopen it or comment here when you have a test case.
