### ISSUE TITLE
Is it possible to batch insert using native queries?

### ISSUE THREAD

**Issue by MarciaBM** [hibernate/hibernate-reactive#1908]
Hello,

As the title suggests, is it possible to batch insert using native queries? I can't find an answer to this question, and I've tried without success to do this. Is there a way? If so, could you provide me an example?

Best regards,
Márcia Matias

**Comment by DavideD** [comment]
In theory yes, but I think there's a bug. I'm having a look

**Comment by DavideD** [comment]
Sorry, I was wrong. Currently batching of native insert queries is not supported.
