### ISSUE TITLE
hibernate-reactive latest version

### ISSUE THREAD

**Issue by Sharofiddin** [hibernate/hibernate-reactive#2002]
As [an issue with embeddedId in hibernate-reactive](https://github.com/hibernate/hibernate-reactive/issues/1979) has been already fixed, why it is not included in latest quarkus versions? We can not update quarkus in our projects (which works with 3.13.x), because of this issue.

**Comment by DavideD** [comment]
I think this is a question for Quarkus. [But the PR that upgrades Hibernate Reactive and fixes the bug](https://github.com/quarkusio/quarkus/pull/43348) has been tagged with `triage/backport`. So it should be included in the next Quarkus 3.15 and it's already been merged for Quarkus 3.16

Maybe, the release of 2.4.1.Final happened a bit too close to the release of Quarkus 3.15.1 to risk including it (it's just my guess).
