### ISSUE TITLE
Stateless reactive insert doesn't return the id

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#2010]
[Hibernate ORM stateless insert returns the id](https://github.com/hibernate/hibernate-orm/blob/dd036023cf7585283a2642c4a584bb870a5a8270/hibernate-core/src/main/java/org/hibernate/StatelessSession.java#L118):

```
Object insert(String entityName, Object entity);
``` 

The one in Hibernate Reactive should return `CompletionStage<Object>` but returns `CompletionStage<Void>`.
Same for Mutiny.

The upgrade to ORM 7 seems a good place to apply these changes.

@gavinking Was this a design choice or something that changed over time?

**Comment by gavinking** [comment]
Um, TBH I don't really recall, but I don't think it's essential. You can always just get the id from the entity itself.

**Comment by DavideD** [comment]
OK, let's keep things as they are.
