### ISSUE TITLE
align semantics of insertAll() and friends with insertMultiple() and friends in ORM

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#2042]
As of H6, ORM has operations like `insertMultiple()` accepting `List<?>` which implicitly set the batch size to the size of the given list. Reactive has very similar `insertAll()` operations, but they do _not_ set the batch size, though you can accomplish the same thing by calling `reactiveInsertAll(array.length, array)`.

I think the behavior in ORM is more convenient.

On a similar note: after much consideration, I decided that the operations in ORM should accept `List` instead of varargs, and that `Multiple` was less ambiguous than `All`. I'm wondering if it's worth adding `insertMultiple(List)` and friends to the reactive API (we don't need to drop or rename the older operations).

**Comment by DavideD** [comment]
Merged, thanks

**Comment by gavinking** [comment]
Cheers
