### ISSUE TITLE
Hibernate v5 to v6 Migration: Property is annotated with @GeneratedValue but is not part of an identifier

### ISSUE THREAD

**Issue by aahlad2000** [hibernate/hibernate-reactive#2051]
Hi team,

Currently facing an issue with Hibernate upgrade from v5 to v6.
I am currently upgrading Springboot 3.2 -> 3.4 and Kotlin 1.7 to 2.0
Issue: Non primary key columns which are annotated with @GenerateValue are throwing an exception:
"Property xx is annotated with @GeneratedValue but is not part of an identifier."

Could you please advice how this could be resolved?

**Comment by gavinking** [comment]
Just remove the `@GeneratedValue`  annotation from the non-`@Id` property. That is something that never had any effect in Hibernate 5 (it was silently ignored). 

In future please use the user forum or Zulip to ask usage questions. This is the bug tracker for Hibernate Reactive.
