### ISSUE TITLE
Additional test cases for queries with parameters

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#211]
This follows https://github.com/hibernate/hibernate-reactive/issues/120

If this task becomes too big we can split it.
We have all the logic for queries and parameters in place but some tests are missing:

- [x] native SQL queries
- [x] filters (see #26)
- [x] criteria queries

We can create new issues if we find problems along the way.

**Comment by gavinking** [comment]
Wrong milestone :-)

**Comment by DavideD** [comment]
By the way, What exactly FIRST CUT means ? is it the first release or the first final?

**Comment by gavinking** [comment]
First release.

**Comment by gavinking** [comment]
I've tested filters, and added tests, but there is a remaining problem #223 
Closing this issue.
