### ISSUE TITLE
Features for Panache Reactive

### ISSUE THREAD

**Issue by FroMage** [hibernate/hibernate-reactive#217]
Hi,

I've started to port Panache Reactive and found the following methods I used to call on `EntityManager` or the JPA `Query` to be missing:

- `Query.setLockMode` (the one taking no alias and a JPA lock enum). It appears not trivial to call the present version with aliases because the code paths differ, so not sure they're equivalent
- `Query.setHint`
- `Query.getQueryOptions` (required to get current paging info)
- `Multi<T> Query.getResuls()` for streaming results, but that one's probably planned for later and I can probably emulate it by wrapping the `Uni<List>` result for now

If those first three are easy to support, can we get them please?

**Comment by gavinking** [comment]
Damn, so the very first actual user of this stuff is the guy who's using all the features where I said to myself "oh, nobody every uses that".

**Comment by gavinking** [comment]
What is it that you're passing to `setHint()`?

**Comment by gavinking** [comment]
I have given you two of your wishlist items, completely without any sort of testing at all.

**Comment by FroMage** [comment]
Thanks :)

**Comment by gavinking** [comment]
So to summarize where we're at on this one:

1. `Query.setLockMode` is done.
2. `Query.setHint()` is implemented but not exposed, because I can't find any hints where are meaningful for use:
    - the vertx client doesn't have timeouts yet
    - there is no notion of a fetch size
    - we have a `setComment()` method, no need for a hint for that
    - likewise, we have methods for setting the flush mode and lock mode
    - I have not tested fetch plans with queries, and if/when we do, I would add a method for it
    - we don't support the query cache yet (at least, we have not tested it), and when we do I would add methods for this
3. I have not done anything about `getQueryOptions()`. The only relevant options are first/max result, so perhaps I should just add getters for those two settings.
4. Streaming results is #153.

**Comment by gavinking** [comment]
> I have not done anything about getQueryOptions(). The only relevant options are first/max result, so perhaps I should just add getters for those two settings.

Now I've added getters in 6ad870b3512ebc35bcbe5be2588c493f1b678c2a. 

@FroMage may I close this issue please?

**Comment by FroMage** [comment]
Actually I just noticed you didn't give me `setLockMode(LockModeType)` which takes the JPA lock mode enum (not the Hibernate enum). Is that on purpose?

**Comment by gavinking** [comment]
Yes, it's on purpose because Hibernate actually has a couple of extra very specific `LockMode`s that JPA doesn't have (`UPGRADE_NOWAIT` and `UPGRADE_SKIPLOCKED`) and because the other enums (`CacheMode` and `FlushMode` are also from `org.hibernate`).

Now, I wouldn't object to overloading those methods to accept the JPA version if it would help.

**Comment by gavinking** [comment]
> Now, I wouldn't object to overloading those methods to accept the JPA version if it would help.

(On the other hand, that might not help much, since the *getters* would still be returning the `org.hibernate` version.)

**Comment by FroMage** [comment]
I mean, ATM I'm calling:

```java
            jpaQuery.setLockMode(LockModeConverter.convertToLockMode(lockModeType));
```

and downstream, you do the exact opposite :(

**Comment by FroMage** [comment]
Oh, damnit, I should have checked what we use the `getQueryOptions` method for, it turns out we use it to reset paging:

```java
//            RowSelection options = jpaQuery.unwrap(org.hibernate.query.Query.class).getQueryOptions();
//            options.setFirstRow(null);
//            options.setMaxRows(null);
```

Sorry about this, I got confused about what this code did, that's my fault. The normal setters don't seem to allow for disabling paging.

**Comment by gavinking** [comment]
> and downstream, you do the exact opposite

I don't. Internally Hibernate converts all `LockModeType`s to `LockMode`s.

**Comment by gavinking** [comment]
> The normal setters don't seem to allow for disabling paging.

They do, I think: you set first to 0 and maz to `Integer.MAX_VALUE`. I believe that that is documented :-)

**Comment by FroMage** [comment]
> They do, I think: you set first to 0 and maz to Integer.MAX_VALUE. I believe that that is documented :-)

Huh. IIRC when this PR got merged, the reporter reported still seeing `LIMIT/OFFSET` clauses in the db query when using that method. But perhaps my memory is wrong.

**Comment by FroMage** [comment]
`LimitHelper.hasFirstRow`  agrees with you, but `LimitHelper.hasMaxRows` doesn't.

**Comment by gavinking** [comment]
> `LimitHelper.hasFirstRow` agrees with you, but `LimitHelper.hasMaxRows` doesn't.

In fairness, the JPA spec is a bit ambiguous. It *does* say that `getMaxRows()` *returns* `MAX_VALUE` when not set, but it doesn't say what setting `MAX_VALUE` does.

I would prefer to change Hibernate to interpret `MAX_VALUE` as no limit.

**Comment by gavinking** [comment]
> > and downstream, you do the exact opposite
> 
> I don't. Internally Hibernate converts all `LockModeType`s to `LockMode`s.

Oh wait. You're right, inside the `Query` they *do* get converted to the `LockModeType`. And then back to `LockMode` later on, I suppose. Pfff.

**Comment by gavinking** [comment]
> > > and downstream, you do the exact opposite
> > 
> > 
> > I don't. Internally Hibernate converts all `LockModeType`s to `LockMode`s.
> 
> Oh wait. You're right, inside the `Query` they _do_ get converted to the `LockModeType`. And then back to `LockMode` later on, I suppose. Pfff.

Oh but only for the one with no alias. Sheesh.

**Comment by gavinking** [comment]
Hahaha OMG the `Query` converts the `LockMode` to a `LockModeType` and then back to a `LockMode`.

**Comment by gavinking** [comment]
> Hahaha OMG the `Query` converts the `LockMode` to a `LockModeType` and then back to a `LockMode`.

Fixed.

**Comment by gavinking** [comment]
> I have not tested fetch plans with queries, and if/when we do, I would add a method for it

I tested this, and ORM itself has a rubbish implementation (n+1 selects) so I won't expose it for now. (If I'm not mistaken, this will be fixed in H6.)

**Comment by gavinking** [comment]
> we don't support the query cache yet

I've opened #247 to capture this.

**Comment by gavinking** [comment]
Closing this one, since the remaining work is in #153 and #247. 

@FroMage if something else is still missing please let me know.
