### ISSUE TITLE
Build fails with MySQL

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#229]

**Comment by gavinking** [comment]
I *suspect*, but do not know for sure yet, that this is a result of @Sanne's new config code breaking my MySQL-specific configuration in `BaseReactiveTest.before()`.

**Comment by gavinking** [comment]
Right, yeah, it's that. `NoJdbcConnectionProviderInitiator` now gets started later and therefore "wins".

**Comment by gavinking** [comment]
Should be fixed now.
