### ISSUE TITLE
Create documentation subproject

### ISSUE THREAD

**Issue by yrodiere** [hibernate/hibernate-reactive#230]
This should produce in particular:

* aggregated javadoc
* asciidoc-based reference documentation

**Comment by gavinking** [comment]
> asciidoc-based reference documentation

So my question is: where is this going to go on the Hibernate website. You see `https://hibernate.org/validator/` currently doesn't exist.

**Comment by DavideD** [comment]
I'm working on the website

**Comment by gavinking** [comment]
> I'm working on the website

Excellent, thanks!

**Comment by yrodiere** [comment]
> So my question is: where is this going to go on the Hibernate website. You see https://hibernate.org/reactive/ currently doesn't exist.

Documentation is hosted on jboss.org for other Hibernate projects anyway. We just link to jboss.org from the website.

We can change that later if necessary, but as a first step I'll just do it the same way as other Hibernate projects :)

**Comment by gavinking** [comment]
OK, but it's not so much a question of where the docs will be *hosted* as where can we put HR so it will have visibility to Hibernate users. I have the same problem with [Query Validator](https://github.com/hibernate/hibernate-reactive) right now. We could do a release of it ... but it wouldn't have any visibility on hibernate.org. And so I'm not quite sure what to do about that.

**Comment by emmanuelbernard** [comment]
My take is Query validator could go https://hibernate.org/tools/ or https://hibernate.org/others/
And HR in https://hibernate.org/reactive
Indeed Davide's work on the website will be critical for visibility.

**Comment by gavinking** [comment]
@emmanuelbernard SGTM
