### ISSUE TITLE
Multi-table update and delete queries are not supported

### ISSUE THREAD

**Issue by gbadner** [hibernate/hibernate-reactive#237]
Currently, updates and deletes that affect multiple entity tables are not supported 

For example, suppose `Folder`, `Document`, and `SymbolicLink` all extend  ` abstract File`, which has a `name` property, and uses `InheritanceType.TABLE_PER_CLASS`.

That means that `Folder`, `Document`, and `SymbolicLink` each has it's own DB table, each having a `name` column.

In order to delete all `File` entities with name like 'Enron%', rows have to be deleted from all 3 tables.

Fixing this would require something like `MultiTableUpdateExecutor` and `MultiTableDeleteExecutor`.

**Comment by gavinking** [comment]
I have an initial, fairly crappy, fix for this in #325.

**Comment by gavinking** [comment]
This problem is fixed, except on DB2, and I'm just waiting for a release of core to merge #325.
