### ISSUE TITLE
use markdown-doclet

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#248]
I *loved* being able to write doc comments in Markdown in Ceylon, and it's such a bummer to go back to the awful quasi-HTML-ish format that's native to Java.

Fortunately, someone has [written a doclet for this](https://github.com/Abnaxos/markdown-doclet), so let's try it out.

**Comment by emmanuelbernard** [comment]
For info, we also experimented and used the asciidoc doclet in Quarkus. I forgot if that’s still in place or if we gave up @gsmet 
I remember I liked it

**Comment by gavinking** [comment]
I've already written most of the API doc in Javadoc now, and can't be bothered rewriting it. Closing this issue.
