### ISSUE TITLE
MS SQL Server support

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#255]
Support for SQL Server is only available in Vert.x 4 at present ~~, and we're currently tied to Vert.x 3.9 by the need to support Quarkus~~.

Also, last time we checked, the SQL Server client was not very robust, and will need some bugfixes to work with HR.

**Comment by gavinking** [comment]
I'll see if I can fine time to read support for SQL Server today.

**Comment by DavideD** [comment]
I think I have a branch with some code ready if you are interested. I don't remember why I didn't finish it, at the moment

**Comment by gavinking** [comment]
Mainly I just need to figure out the right friction' JDBC URL to use in testcontainers. Do you have that somewhere?

**Comment by DavideD** [comment]
Not sure what you mean, but my project is here:
https://github.com/DavideD/hibernate-reactive/tree/mssql-vertx-4

I've rebased it to the latest changes, it builds but it might not work.

**Comment by DavideD** [comment]
I've created a new branch on hibernate/hibernate reactive: https://github.com/hibernate/hibernate-reactive/tree/wip/mssql

@tsegismont We can use that one from now. Please, let me know if somethingis missing or I did something wrong.
Thanks

**Comment by tsegismont** [comment]
@DavideD I can't see any commit missing :+1:

**Comment by DavideD** [comment]
I'm going to rebase the `wip/mssql`  branch to the latest changes and have a look at some of the tests to see if we can make them work for now. Let me know if somebody is already working on this.

**Comment by DavideD** [comment]
Done.
I've disabled [BatchQueryConnectionTest](https://github.com/DavideD/hibernate-reactive/commit/c4591f137b089374cb1611ded952938514097df6) because it blocks the build and it seems batching is not supported at the moment
