### ISSUE TITLE
Quarkus quickstart

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#260]
We need to create the quickstart for quarkus: https://github.com/quarkusio/quarkus-quickstarts

**Comment by DavideD** [comment]
@aguibert Are you already working on this?

**Comment by mgonzaga1990** [comment]
Hi @DavideD , is the connection configuration simillar to this **hibernate-orm-quickstart** ? 
I'm trying to integrate this on my project as we speak..

**Comment by aguibert** [comment]
hey @DavideD, no I haven't started on it yet but it was on my TODO list

**Comment by DavideD** [comment]
@aguibert I will assign this to myself ten
@mgonzaga1990 I still have to finish it but I suppose it's similar. I will let you know when I've finished it.

**Comment by mgonzaga1990** [comment]
@DavideD - let me know if there is anything i could help you on this one.. since I'm gonna use it together with quarkus and mutiny.

**Comment by DavideD** [comment]
PR sent: https://github.com/quarkusio/quarkus-quickstarts/pull/610

**Comment by DavideD** [comment]
Also: https://github.com/quarkusio/quarkus-quickstarts/pull/618

This last one hasn't been included yet but I'm considering these issues done/
