### ISSUE TITLE
CompletionStage exceptions leak into Mutiny API

### ISSUE THREAD

**Issue by FroMage** [hibernate/hibernate-reactive#263]
I just got a `CompletionException` via the `Mutiny` API, which wraps any exception thrown inside a `CompletionStage` pipeline. I believe this is very annoying because it means I must wrap all my `Uni` into an exception mapper that unwraps these silly exception wrappers into their original causes.

Can we make sure the Mutiny API unwraps those?

Otherwise you'll have to document that `NoResultException` are sometimes thrown directly but sometimes wrapped inside a `CompletionException`, and that feels wrong, no?

**Comment by gavinking** [comment]
Hrm. I almost feel like this is something that `Uni.createFrom().completionStage()` should do for me. I mean, we could do it in 27 different places (so far!) in Hibernate Reactive, or Mutiny could do it in one place.

WDYT @cescoffier?

**Comment by cescoffier** [comment]
Yes, something we should do in Mutiny. Do you have the code you are doing somewhere?

**Comment by gavinking** [comment]
> Do you have the code you are doing somewhere?

No, the reason @FroMage opened this issue is that we *don't* do it.

**Comment by FroMage** [comment]
> Yes, something we should do in Mutiny

Ah, good point, shall I open an issue in Mutiny then?

**Comment by cescoffier** [comment]
Yes please.

But no "attacks of stack trace" ;-) [while it could be a great movie title]

**Comment by FroMage** [comment]
Moved to https://github.com/smallrye/smallrye-mutiny/issues/179
