### ISSUE TITLE
Trouble with gradle dependency solving

### ISSUE THREAD

**Issue by dorinesinenco** [hibernate/hibernate-reactive#265]
Hi guys, first of all thanks for awesome work!

my setup is JDK14/11 (tested on both)
intellij
gradle quarkus project

adding, tried all the variation possible of dependency path

dependencies {
  ..
  implementation 'org.hibernate.reactive:hibernate-reactive-core:1.0.0-SNAPSHOT'
  //    implementation 'org.hibernate.reactive:hibernate-reactive-core'
  //    implementation 'com.github.hibernate:hibernate-reactive:1.0.0.Aplha5'
}

and even with git resolver

repositories {
      ....
     maven { url 'https://jitpack.io' }
}

IT ALL YIELDS :

 "Could not find org.hibernate.reactive:hibernate-reactive-core:1.0.0-SNAPSHOT.
Required by:
    project :
"

??

**Comment by dorinesinenco** [comment]
Nevermind :) Missspelled "Alpha", sorry!

**Comment by DavideD** [comment]
This should be the latest one [available on Maven central](https://search.maven.org/artifact/org.hibernate.reactive/hibernate-reactive-core/1.0.0.Alpha5/jar):
```
implementation 'org.hibernate.reactive:hibernate-reactive-core:1.0.0.Alpha5'
```

We didn't release a version 1.0.0-SNAPSHOT and I don't think you need to use the one on github

**Comment by DavideD** [comment]
> `Nevermind :) Missspelled "Alpha", sorry!

Cool :)

**Comment by dorinesinenco** [comment]
> This should be the latest one [available on Maven central](https://search.maven.org/artifact/org.hibernate.reactive/hibernate-reactive-core/1.0.0.Alpha5/jar):
> 
> ```
> implementation 'org.hibernate.reactive:hibernate-reactive-core:1.0.0.Alpha5'
> ```
> 
> We didn't release a version 1.0.0-SNAPSHOT and I don't think you need to use the one on github

Well, the problem is - that in your docs - the text mentions this snapshot version, i am not using it for production

**Comment by DavideD** [comment]
Ah, that's a bug. I'm going to fix it. Thanks
