### ISSUE TITLE
The README should point to the latest release available

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#266]
Currently it always says:
```
org.hibernate.reactive:hibernate-reactive-core:1.0.0-SNAPSHOT
```

but before the release we should update it with the version released.
Example:
```
org.hibernate.reactive:hibernate-reactive-core:1.0.0.Alpha5
```

**Comment by gavinking** [comment]
I already fixed this, and in fact this section was removed from the README.

**Comment by DavideD** [comment]
Not what I meant but I guess it's easier this way.

In the [Including Hibernate Reactive in your project build](https://github.com/hibernate/hibernate-reactive/blob/master/documentation/src/main/asciidoc/reference/introduction.adoc#including-hibernate-reactive-in-your-project-build) we could add a link to the Hibernate Reactive website with the latest available stable version once we have it.
