### ISSUE TITLE
[Question] How to controll transaction without using withTranscation 

### ISSUE THREAD

**Issue by semistone** [hibernate/hibernate-reactive#272]
Hi
  When I try the RX example, 
it suggests using Mutiny.SessionFactory or Stage.SessionFactory and withTransaction method
but this method will commit or rollback after exit withTransaction method.
But usually, we need to proceed a transaction within different threads. 
eg: begin tx -> query -> call rest API -> insert table 1 -> query cache  -> insert table2 -> commit
then how can I do it by withTransaction?

Can we have beginTransaction which return Transaction object to let the user 
 control and pass transaction objects manually?

Thanks.
Angus

**Comment by gavinking** [comment]
Hi, I don't really understand what you're asking for here:

- what are the session boundaries in what you've written above?
- what precisely do you mean be a "thread" in the context of reactive?

Have you seen that there is also a `withTransaction()` on `Session`, as well as `SessionFactory`?

**Comment by avillev** [comment]
I think he is confused by how to use the withTransaction method and execute several queries within the transaction that is all.

Which queries are using that transaction and when the transaction is commited is unclear.

The doc example is:

```java
session.withTransaction( tx -> session.persist(book) )
```

Maybe we could get a simple example of how to do it with several inserts/reads chained together ?

**Comment by gavinking** [comment]
Ah, OK, well there are a couple of examples in the example program:

```java
		factory.withTransaction(
				// retrieve a Book and delete it
				(session, tx) -> session.find(Book.class, book2.id)
						.thenCompose( book -> session.remove(book) )
		)
				.toCompletableFuture().join();

		factory.withTransaction(
				// delete all the Books in a transaction
				(session, tx) -> session.createQuery("delete Book").executeUpdate()
				factory.withTransaction(
				// retrieve a Book and delete it
				(session, tx) -> session.find(Book.class, book2.id)
						.thenCompose( book -> session.remove(book) )
		)
```

And:

```java
		factory.withTransaction(
				// delete all the Books in a transaction
				(session, tx) -> session.createQuery("delete Book").executeUpdate()
						// delete all the Authors
						.thenCompose( $ -> session.createQuery("delete Author").executeUpdate() )
		)
				// delete all the Authors
						.thenCompose( $ -> session.createQuery("delete Author").executeUpdate() )
		)
```

But sure, I can add an example like that to the docs.

**Comment by semistone** [comment]
Hi, 

I check the source code  of Transaction
```
Uni<T> execute(Function<Mutiny.Transaction, Uni<T>> work) {
			return begin()
					.flatMap( v -> work.apply( this ) )
					// only flush() if the work completed with no exception
					.flatMap( result -> flush().map( v -> result ) )
					// have to capture the error here and pass it along,
					// since we can't just return a CompletionStage that
					// rolls back the transaction from the handle() function
```
then I think I know the answer. 
I will try to write simple example tomorrow.

thanks

**Comment by DavideD** [comment]
I guess we can close this

**Comment by semistone** [comment]
thanks. 
we could close this ticket.

but just share what we do recently.
because we plan to integrate with Spring Webflux.
and it's mainly using reactor (Mono and Flux)

because currently only supports Stage and Mutiny
so I just wrap Stage into Mono/Flux interface. (include Query, Factory, and Session)
then I don't need to convert Uni -> Mono, and Mono -> Uni everywhere even it's simple

because we need to use Context in Mono, so using Uni isn't that convenient in our project.
