### ISSUE TITLE
Insecure coding pattern: Missing default case in switch statements 

### ISSUE THREAD

**Issue by paser4se** [hibernate/hibernate-reactive#277]
Greetings, 

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found that your code does not have a default case in the switch statement. According to the Common Weakness Enumeration organization, this is a security weakness. See the link https://cwe.mitre.org/data/definitions/478.html

Source: https://github.com/hibernate/hibernate-reactive/blob/master/hibernate-reactive-core/src/main/java/org/hibernate/reactive/stage/impl/StageSessionImpl.java and https://github.com/hibernate/hibernate-reactive/blob/master/hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java

Fix: Fix #276 and #278 

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by gavinking** [comment]
Thanks but no thanks.
