### ISSUE TITLE
Session/EntityManager is closed and Unexpected access to the database

### ISSUE THREAD

**Issue by mgonzaga1990** [hibernate/hibernate-reactive#282]
Hi,

Would like to seek your advice regarding on my issue.

So I have an angular front end which is calling my some backend api. One of which is my api that fetches list of person.
at first i dont get any issues.. but when i refresh my angular page in the browser by hitting F5. I'm getting this error.

```
Caused by: java.lang.IllegalStateException: Session/EntityManager is closed

2020-07-13 03:33:54,324 ERROR [org.hib.AssertionFailure] (executor-thread-1) HHH000099: an assertion failure occurred (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): org.hibernate.AssertionFailure: Unexpected access to the database
2020-07-13 03:33:54,331 ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002020: Unhandled asynchronous exception, sending back 500: org.hibernate.AssertionFailure: Unexpected access to the database
```

This is my first time seeing this kind of error don't kind of lost on which part I missed or if its a bug.

here is my DAO class.

```
@Inject
 Uni<Mutiny.Session> mutinySession;
```

```
public Uni<List<Person>> getAll(){
        return this.mutinySession
                .flatMap(session -> session.createNamedQuery("Person.findAll",Person.class)
                        .getResultList())
                .onFailure().invoke(ex-> new PersonException(ex.getMessage(), ALL_FETCH));
 }`

`public Uni<Person[]> getAll(String sort, String order, Long pageNumber,Integer size){
        return this.mutinySession
                .flatMap(session -> {
                    var sql = "SELECT * " +
                            "FROM PERSON ORDER by :sort " + order + " " +
                            "OFFSET ( :size * ( (:pageNumber) - 1)) ROWS " +
                            "FETCH NEXT :size ROWS ONLY";
                    return session.createNativeQuery(sql,Person.class)
                            .setParameter("sort",sort)
                            .setParameter("pageNumber",pageNumber + 1)
                            .setParameter("size",size)
                            .getResultList();
                })
                .map(persons -> persons.toArray(new Person[persons.size()]))
                .onFailure().invoke(ex-> new PersonException(ex.getMessage(),ALL_FETCH));
 }
```

My code for Save and update is working so far, so i didn't put it here.

Thanks for your help.

**Comment by mgonzaga1990** [comment]
I just basically follow the example here [quick-start](https://github.com/DavideD/quarkus-quickstarts/tree/hibernate-reactive-quickstart-development/hibernate-reactive-quickstart)

**Comment by DavideD** [comment]
Can you try disabling the query-cache?
(Remove the @QueryHint and the @Cachable annotations if you have any).

**Comment by mgonzaga1990** [comment]
I see.. thanks for your help i appreciate it

**Comment by DavideD** [comment]
Did it solve the issue?

**Comment by mgonzaga1990** [comment]
Yes. I did, I'll just find another way to cache the data but it worked and
thanks so much.

**Comment by mgonzaga1990** [comment]
However I'm getting this error *ReactiveSessionImpl#initializeCollection
not supported, use reactiveInitializeCollection instead*.
Been looking for that error in the internet but got nothing so far.

I do have a feeling that it has something related with my entity mappings

Person has many Address.

and Address has different parts like. addressLine1,addressLine2 and City,
Province.

In my case.. I'm allowed to insert a person without address..
But I must be wrong.

Caused by: java.lang.UnsupportedOperationException:
ReactiveSessionImpl#initializeCollection not supported, use
reactiveInitializeCollection instead
at
org.hibernate.reactive.session.impl.ReactiveSessionImpl.initializeCollection(ReactiveSessionImpl.java:375)
at
org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:589)
at
org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:264)
at
org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:585)
at
org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:149)
at
org.hibernate.collection.internal.AbstractPersistentCollection$1.doWork(AbstractPersistentCollection.java:178)
at
org.hibernate.collection.internal.AbstractPersistentCollection$1.doWork(AbstractPersistentCollection.java:163)
at
org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:264)
at
org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:162)
at
org.hibernate.collection.internal.PersistentBag.size(PersistentBag.java:371)
at
org.hibernate.bytecode.enhance.spi.interceptor.LazyAttributeLoadingInterceptor.takeCollectionSizeSnapshot(LazyAttributeLoadingInterceptor.java:160)
at
org.hibernate.bytecode.enhance.spi.interceptor.LazyAttributeLoadingInterceptor.lambda$loadAttribute$0(LazyAttributeLoadingInterceptor.java:110)
at
org.hibernate.bytecode.enhance.spi.interceptor.EnhancementHelper.performWork(EnhancementHelper.java:127)
at
org.hibernate.bytecode.enhance.spi.interceptor.LazyAttributeLoadingInterceptor.loadAttribute(LazyAttributeLoadingInterceptor.java:76)
at
org.hibernate.bytecode.enhance.spi.interceptor.LazyAttributeLoadingInterceptor.fetchAttribute(LazyAttributeLoadingInterceptor.java:72)
at
org.hibernate.bytecode.enhance.spi.interceptor.LazyAttributeLoadingInterceptor.handleRead(LazyAttributeLoadingInterceptor.java:53)
at
org.hibernate.bytecode.enhance.spi.interceptor.AbstractInterceptor.readObject(AbstractInterceptor.java:153)
at org.pdao.model.Person.$$_hibernate_read_addressList(Person.java)
at org.pdao.model.Person.getAddressList(Person.java:54)

**Comment by DavideD** [comment]
I suspect  it has to do with this: https://github.com/hibernate/hibernate-reactive#fetching-lazy-associations

If you don't add the entities and the query/command you are running (or a test), it's pretty hard for us to help you.

**Comment by mgonzaga1990** [comment]
Sorry I missed that part.

Here is my Person Entity

`@Data
@Entity
@Builder
@Table(name = "person")
@NoArgsConstructor
@AllArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Person {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    Long id;

    @NotBlank(message = "Lastname is required")
    String lastname;
    @NotBlank(message = "Firstname is required")
    String firstname;
    String middlename;

    @JsonbDateFormat(value = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
    @Past(message = "Date of birth should be in the past")
    LocalDateTime dob;

    @ValueOfEnum(enumClass  = Gender.class,message = "Incorrect value of Gender")
    String gender;

    @OneToMany(mappedBy = "person",fetch = FetchType.LAZY)
    List<Address> addressList;
}`


`@Data
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "address")
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Address {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    Long id;

    String addressLine1;
    String addressLine2;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "person_id",nullable = false,referencedColumnName = "id")
    Person person;
}`


`public Uni<Person[]> getAll(String sort, String order, Long pageNumber,Integer size){
        return this.mutinySession
                .flatMap(session -> {
                    var sql = "SELECT * " +
                            "FROM PERSON ORDER by :sort " + order + " " +
                            "OFFSET ( :size * ( (:pageNumber) - 1)) ROWS " +
                            "FETCH NEXT :size ROWS ONLY";
                    return session.createNativeQuery(sql,Person.class)
                            .setParameter("sort",sort)
                            .setParameter("pageNumber",pageNumber + 1)
                            .setParameter("size",size)
                            .getResultList();
                })
                .map(persons -> persons.toArray(new Person[persons.size()]))
                .onFailure().invoke(ex-> new PersonException(ex.getMessage(),ALL_FETCH));
    }`

It's when my person's address is null (which is part of my use case for homeless people)
Also, I tried both EAGER and LAZY

**Comment by mgonzaga1990** [comment]
I Have seen the example but this is not using the **createNativeQuery** I also checks the tests but couldn't find any.

**Comment by DavideD** [comment]
Are you using Lombok? Which version?
What's `@ValueOfEnum`?

**Comment by DavideD** [comment]
Probably doesn't matter

**Comment by mgonzaga1990** [comment]
```
<dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.12</version>
      <scope>provided</scope>
    </dependency>
```

the `@ValueOfEnum` is just my annotation used for validation. My DTO for my rest api is as the same as my entity model.

```
@Target({ElementType.METHOD, ElementType.FIELD, ElementType.ANNOTATION_TYPE, ElementType.CONSTRUCTOR, ElementType.PARAMETER, ElementType.TYPE_USE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Constraint(validatedBy = ValueOfEnumValidator.class)
public @interface ValueOfEnum {
    Class<? extends Enum<?>> enumClass();
    String name() default "";
    String message() default "must be any of enum {enumClass}";
    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};
}
```

```
public class ValueOfEnumValidator  implements ConstraintValidator<ValueOfEnum,CharSequence> {
    private List<String> acceptedValues;

    @Override
    public void initialize(ValueOfEnum annotation) {
        acceptedValues = Stream.of(annotation.enumClass().getEnumConstants())
                .map(Enum::name)
                .collect(Collectors.toList());
    }

    @Override
    public boolean isValid(CharSequence value, ConstraintValidatorContext context) {
        if (value == null) {
            return true;
        }

        return acceptedValues.contains(value.toString().toUpperCase());
    }
}
```

**Comment by DavideD** [comment]
Thanks, I can replicate the issue but the problem for me is solved when I apply one of these two approaches:
1. declare *both* side of the association as EAGER
2. use `session.fetch(...)`

**Comment by DavideD** [comment]
Note that having null shouldn't matter and that error occurs when Hibernate Reactive has to initialize a collection at the wrong time.
This is a known limitation that we will fix at some point.

**Comment by mgonzaga1990** [comment]
`session.fetch(...)` if that's the case then I can no longer use the below method.

```
public Uni<Person[]> getAll(String sort, String order, Long pageNumber,Integer size){
        return this.mutinySession
                .flatMap(session -> {
                    var sql = "SELECT * " +
                            "FROM PERSON ORDER by :sort " + order + " " +
                            "OFFSET ( :size * ( (:pageNumber) - 1)) ROWS " +
                            "FETCH NEXT :size ROWS ONLY";
                    return session.createNativeQuery(sql,Person.class)
                            .setParameter("sort",sort)
                            .setParameter("pageNumber",pageNumber + 1)
                            .setParameter("size",size)
                            .getResultList();
                })
                .map(persons -> persons.toArray(new Person[persons.size()]))
                .onFailure().invoke(ex-> new PersonException(ex.getMessage(),ALL_FETCH));
    }
```

Also, as far as i can see. `fetch` only return a single data.

I may need to change my implementation and rules until we got the fix on that limitation.

**Comment by gavinking** [comment]
> Note that having null shouldn't matter and that error occurs when Hibernate Reactive has to initialize a collection at the wrong time.
> 
> This is a known limitation that we will fix at some point.

Well we already removed the limitation (or more accurately @gbadner removed it) for at least the cases I knew about. I'm trying to understand what is different here to the things we've already tested. Is it because this is a native query? What happens with the equivalent HQL?

Perhaps Gail has some insight.

**Comment by gavinking** [comment]
waaait ... there is a `LazyAttributeLoadingInterceptor` in the stack trace ... what's that doing there? Exactly what is triggering this collection fetch?

**Comment by gavinking** [comment]
> waaait ... there is a `LazyAttributeLoadingInterceptor` in the stack trace ... what's that doing there? Exactly what is triggering this collection fetch?

Is it something specific to field-level lazy fetching?

**Comment by DavideD** [comment]
Ah, I just realized that I haven't enabled the  `bytecode enhancement`. I will check again

**Comment by mgonzaga1990** [comment]
thanks David please let us know then once ur good

**Comment by DavideD** [comment]
I could replicate the exact stacktrace on Hibernate Reactive so I've created a test in the quarkus-quickstart project: https://github.com/DavideD/quarkus-quickstarts/tree/bytecode-error/hibernate-reactive-bytecode-enhancement

The entities are not exactly the same because I wanted to have a simpler test but if you remove the last commit you will have the same exception.

Adding the eager solved the issue: https://github.com/DavideD/quarkus-quickstarts/commit/ae4f48825c274ae90c7d92a77d44ebc54c98abc6:

I've tried different combinations and also tested it with your exact entities but always with the same result.
I'm not sure why it doesn't work for you.

@mgonzaga1990 If you publish your project somewhere I can have a look at it

**Comment by mgonzaga1990** [comment]
let me pattern my implementation from yours. And will let you know after.

**Comment by mgonzaga1990** [comment]
anyway i just noticed you have

`<quarkus-plugin.version>999-SNAPSHOT</quarkus-plugin.version>`

```
 <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-reactive-deployment</artifactId>
            <scope>provided</scope>
            <version>${quarkus-plugin.version}</version>
        </dependency>
```
I did not put that dependency in my pom so i added it in.
`<quarkus-plugin.version>1.6.0.Final</quarkus-plugin.version>`

```
<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-reactive-deployment</artifactId>
      <scope>provided</scope>
    </dependency>
```

now it's working but still the fetch type should be **EAGER**. Is this an ongoing issue or limitation? you mentioned before?

_test reponse_
```
[
    {
        "addressList": [],
        "dob": "2019-10-31T00:00:00.000Z",
        "firstname": "Vincent",
        "gender": "Male",
        "id": 1,
        "lastname": "Wingham"
    },
    {
        "addressList": [],
        "dob": "2019-07-13T00:00:00.000Z",
        "firstname": "Lynea",
        "gender": "Female",
        "id": 2,
        "lastname": "Macconaghy"
    },
    {
        "addressList": [],
        "dob": "2019-11-28T00:00:00.000Z",
        "firstname": "Jacinta",
        "gender": "Female",
        "id": 3,
        "lastname": "Krahl"
    },
    {
        "addressList": [],
        "dob": "2019-07-23T00:00:00.000Z",
        "firstname": "Kyle",
        "gender": "Male",
        "id": 4,
        "lastname": "Pilch"
    },
    {
        "addressList": [],
        "dob": "2019-11-18T00:00:00.000Z",
        "firstname": "Earlie",
        "gender": "Male",
        "id": 5,
        "lastname": "Janjic"
    }
]
```

**Comment by DavideD** [comment]
> Well we already removed the limitation 

@gavinking What do you mean? I don't expect bi-directional lazy association to work in this case unless you fetch the association eagerly somehow

**Comment by gavinking** [comment]
Well, no, if things are lazy and getting fetched because they're being explicitly accessed by the program, then I would expect an error.

But I don't see where the association is being accessed in the code posted above. That's why I was asking: exactly what triggers this association to be fetched. I don't see where it happens.

**Comment by DavideD** [comment]
Ah, I see. Let me check. I think it was `.size()` call on the collection somewhere one the result is returned.

**Comment by DavideD** [comment]
Yes, it's RestEasy checking the association to generate the response during marshalling. Even if it's empty null it still check the size and calls underneath PersistentBag#size().

**Comment by gavinking** [comment]
> Yes, it's RestEasy checking the association to generate the response during marshalling. Even if it's empty it still check the size and calls underneath PersistentBag#size().

OK then it should throw a `LazyInitializationException`. The exception type is wrong.
