### ISSUE TITLE
[Question] Mutiny.Session#createNativeQuery(String) returns Query<Integer>

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#284]
https://github.com/hibernate/hibernate-reactive/blob/master/hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java#L625

It seems on purpose (reading javadoc) but this surprised me:
* `Mutiny.Session#createQuery(String)` doesn't
* we return the integer when running `.executeUpdate()`

Shouldn't this return `<R> Query<R>` like all the other similar functions?
@gavinking (\cc @Sanne, @gbadner)

**Comment by gavinking** [comment]
Definitely intentional. If you don't pass anything describing the type of the result set for a native query, there's no way for Hibernate to know what to do with it.

HQL is different because we can figure out the return type from the query string itself. We can't do that with SQL.

**Comment by DavideD** [comment]
Doesn't ORM returns an Object[]? I was expecting to receive whatever object the driver returns.

**Comment by DavideD** [comment]
> I was expecting to receive whatever object the driver returns.

I mean... for each column. Also, isn't `createNativeQuery` quite misleading as a name when everywhere else we return something different?

**Comment by gavinking** [comment]
> Doesn't ORM return an Object[]? I was expecting to receive whatever object the driver returns.

I don't recall. But if it does, it would need to use JDBC metadata for that, which we don't have yet.

Hrm, I seem to recall I might have opened a feature request against the Vert.x client related to this, but I forget the details.

**Comment by gavinking** [comment]
See my comments [here](https://github.com/hibernate/hibernate-reactive/pull/180#discussion_r429576118).

**Comment by DavideD** [comment]
I'm missing how the column type is needed in this case.

I can actually write:
```
List<?> results = mutinySession.createNativeQuery( "select * from artist a" )
                .getResultList().await().indefinitely();
```
and it returns what I expected (List<Object[]>).

This also compile
```
List<Integer> result = mutinySession.createNativeQuery(" select * from artist a" )
                .getResultList().await().indefinitely();
```

This doesn't compile, though:
```
List<Object[]> results = mutinySession.createNativeQuery(  "select * from artist a" )
                .getResultList().await().indefinitely();
```

**Comment by gavinking** [comment]
TBH I really don't recall all the context. But anyway if that code works then I guess you're right and we should change the return type.

**Comment by DavideD** [comment]
Done https://github.com/hibernate/hibernate-reactive/issues/284
