### ISSUE TITLE
Handling empty results

### ISSUE THREAD

**Issue by k0l0ssus** [hibernate/hibernate-reactive#294]
Mutiny provides a couple of options to handle events when things don't go as expected. `ifNoResult` feels like a natural fit here. So, given the following query orchestration:

       mutinySession.map(session -> session.find(Fruit.class, Long.valueOf("1234")))
                .ifNoItem()
                .after(Duration.ofMillis(3000))
                .failWith(new IllegalArgumentException("No fruit found for that Id"))
                .onItem()
                .apply(fruitUni-> {
                    try {
                        return fruitUni.subscribeAsCompletionStage().get();
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    } catch (ExecutionException e) {
                        e.printStackTrace();
                    }
                    return new Fruit("DeadFruit");
                })
                .map(Fruit::fromFruitEntity)
                .subscribe()
                .asCompletionStage()
                .get();

I'd expect an `IllegalArgumentException` to be thrown when I supply a non-existent ID. What I get instead, is a `NullPointerException` for trying to call `get` on a `CompletionStage`, indicating that `ifNoItem` had no effect. **This is inside a Quarkus application, v1.6.0.Final**, with the following rxHibernate dependencies:

        <dependency>
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-hibernate-reactive</artifactId>
        </dependency>
        <dependency>
              <groupId>io.quarkus</groupId>
              <artifactId>quarkus-hibernate-reactive-deployment</artifactId>
              <scope>provided</scope>
        </dependency> 

Is there something else I ought to be doing?

**Comment by gavinking** [comment]
Stack trace?

**Comment by DavideD** [comment]
I think what you are looking for is this:
```
Fruit fruit = mutinySession.onItem().transformToUni( session -> session.find( Fruit.class, Long.valueOf("1234") ) )
				.await().atMost( Duration.ofMillis( 1000 ) );
if ( fruit == null ) {
    throw  new IllegalArgumentException("No fruit found for that Id");
}
```

`.failWith` is not going to stop everything and throw an exception, it creates a failed Uni with the exception you selected.
It is up to you to manage  this uni. At the moment, you are always returning the result that, because of the exception, is always going to be null.

Here a subscribe that manages the result and/or the exception:
```
.subscribe().asCompletionStage().whenComplete( (res, err) -> {
		System.out.println( "Result: " + res );
		System.err.println( "Error: " + err ); // Illegal Argument exception
});
```

Also, you don't need to convert everything completion stages:
```
.subscribe().with(
		res -> System.out.println(res),
		Throwable::printStackTrace
);
```

**Comment by k0l0ssus** [comment]
Thanks @DavideD . Thanks for the completion stage -> await tip. A consumer like `with` won't cut it for me though. Thing is, I'm trying to avoid a manual nullcheck and going by [Mutiny's documentation](https://smallrye.io/smallrye-mutiny/#_how_do_i_handle_timeout), felt that `ifNoItem`  would be a good, idiomatic fit. `ifNull` doesn't behave the way it ought to either. 

     AnagramResponse anagramResponse = mutinySession.onItem()
                .produceUni(session -> session.find(Anagram.class, Long.valueOf(anagramSourceId)))
                .onItem()
                .ifNull()
                .failWith(new IllegalArgumentException("Unknown Id"))
                .onItem()
                .apply(AnagramResponse::fromAnagram)
                .await()
                .indefinitely();

What's a fluent way to deliver the value if present, or throw a preferred exception when not? A consumer like `with` would probably make me do things with more code than necessary.

**Comment by k0l0ssus** [comment]
Use `ifNull`  instead of `ifNoItem`
