### ISSUE TITLE
@Generated properties

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#313]
Fields mapped with `@org.hibernate.annotations.Generated` don't work in Hibernate Reactive because we need reactified versions of `processInsertGeneratedProperties()`, `processUpdateGeneratedProperties()`, and `processInsertGeneratedProperties()`.

I don't believe this is a super-high priority, but it's worth keeping track of.

**Comment by gastaldi** [comment]
I have a `BaseEntity extends PanacheEntity` with the following attributes:

```java
    @Version
    @ColumnDefault("0")
    public int versionLock;

    @Temporal(value = TemporalType.TIMESTAMP)
    @Generated(value = GenerationTime.INSERT)
    @ColumnDefault(value = "CURRENT_TIMESTAMP")
    public Date createdAt;
```
But the exception introduced in https://github.com/hibernate/hibernate-reactive/commit/62e439e92906b0bcea1cd408a1c23999b2c83b3b is preventing me from migrating to Hibernate Reactive. 

So I'm +1 in having this fixed when possible 😉

**Comment by gavinking** [comment]
@DavideD @blafond  this one looks really very straightforward, and we have a request for it. So would one of you like to take a look?

**Comment by DavideD** [comment]
I will take care of it

**Comment by gavinking** [comment]
Super!

**Comment by DavideD** [comment]
@gastaldi This fix will be included in the next release

**Comment by gastaldi** [comment]
Awesome! Thanks @DavideD !
