### ISSUE TITLE
Consider exposing a single method to open Sessions

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#316]
Today on SessionFactory we're exposing both options:

- `Uni<Session> openSession()`
- `Session createSession()`

And a similar duality is proposed for the `StatelessSession` opening API (pr #310)

I would suggest exposing a single method only:

    Session openSession()

For various reasons:

## Simplicity

I don't believe there's a good reason to expose both

## `openSession` is the better name

It's the same as people are familiar with from ORM "classic", and it reminds that the `Session` resource needs to be closed.

## Implementation flexibility

Different containers will require different connection release strategies, so I'd rather leave this as an implementation detail of the integration code than something that is exposed on API.

I believe that, while we might need some degree of internal flexibility to accommodate for needs of various integration platforms / containers, we'll never need to open a connection immediately so there should be no need to have a blocking version of this method which requires returning a promise.
(Or, if some exotic container is still requiring this, they should fix it).

# Optimal strategy

For Quarkus today we're using the org.hibernate.ConnectionReleaseMode of `AFTER_STATEMENT`, which is not the most efficient but scales well and is a safe choice on many containers (including WildFly), and is therefore the default in Hibernate ORM.

But we have plans to switch to `BEFORE_TRANSACTION_COMPLETION`, a newly introduced policy (which still isn't production ready) as it will be much more efficient, especially in combination with our preferred connection pool Agroal.

I'm not sure if we'll want to use the same default in Reactive, but take it as an example of why leaving ourselves options open could be useful.

**Comment by gavinking** [comment]
So this is something that was introduced in 33a25d0b7d36c3af19de0eb61d27f3344ccd6a4b and bcdb2550d91a966f7f9339ccb694a6f0921b2c0b when I added support for transactions.

What happened was that starting a session now meant obtaining a `SqlConnection` (instead of just using the `SqlClientPool`), which is a non-blocking operation in Vert.x.

So at first I just changed `openSession()` to return the new `Session` in a non-blocking fashion.

But then @aguibert complained about the usability of that, so to fix it, I added a new `createSession()` operation that uses a `ProxyConnection` which obtains its `Connection` the first time we call a non-blocking operation on the `ReactiveConnection`. Now, I didn't love this design at all because `ProxyConnection` works by introducing a new link in the chain of `CompletionStage`s for every operation on a  `ReactiveConnection`. 

So that's why we have two operations: to provide a way of avoiding all these extra `CompletionStage`s if necessary.

Now, I guess there's a more efficient (but *much* messier) implementation of `ProxyConnection` that avoids creating so many `CompletionStage`s, but even given that I'm still not sure that I love it....

**Comment by gavinking** [comment]
> Now, I guess there's a more efficient (but _much_ messier) implementation of `ProxyConnection` that avoids creating so many `CompletionStage`s, but even given that I'm still not sure that I love it....

Please see #317.

**Comment by gavinking** [comment]
So after #317, my concerns about performance are *probably* gone (though we should test it!) ... however, it's raised an additional concern.

We've talked about how in future we might like to be able to run some persistence operations using parallel non-blocking calls to the database. It looks to me like `ProxyConnection` makes that harder (though I'm not completely sure).

**Comment by Sanne** [comment]
I'm rather optimistic that we should be able to improve such internal implementation details as necessary.

I assuming we agree that the simple user operation of "opening a session" is inherently non-blocking?

Looing at possible _subsequent_ operations which the user might want to schedule on such session, I can see only two kinds: those who will need a connection to be resolved, and are to be modelled as promises, and those which don't need a connection. 

So I think it would be safe to just expose `Session openSession()`

**Comment by gavinking** [comment]
Honestly it's not very clear to me. You're *probably* right, but the "execute these two operations in parallel, but have them both wait 'til we get a connection first, assuming we don't have one yet, isn't a totally trivial thing.

It would certain be possible if we add operations like `updateInParallel()` and `selectInParallel()` to `ReactiveConnection` but then that has a difficult-to-evaluate-in-the-abstract impact on the client code.

Do you see what I'm trying to get at?

**Comment by Sanne** [comment]
Yes I think we're on the same page, but I'm still not too worried :)

I hate to sound overconfident, especially as I'm _still_ uncomfortable writing reactive code, but I just feel that conceptually it's not too complicated to model as 3 different states:

- either you have a connection -> use it
- or someone is "in process" of getting one -> wait for that to be done, then use it
- or there isn't one -> trigger one being opened -> wait for it, then use it

We then make sure that we can switch states atomically; it's just one additional state compared to the boolean you added yesterday.
Not saying we need to implement this right away, but _conceptually_ I expect that we can live happily ever after with a single `openSession` method.

**Comment by gavinking** [comment]
@Sanne You convinced me.

**Comment by Sanne** [comment]
Nice! Many thanks

**Comment by gavinking** [comment]
By the way @Sanne, this change is, I assume, going to break the Q extension, so it will need to be updated.

**Comment by Sanne** [comment]
Sure, good point.
