### ISSUE TITLE
podman instructions aren't understandable

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#324]
@DavideD I still don't understand the [podman instructions](https://github.com/hibernate/hibernate-reactive/blob/master/podman.md), and since I can't run Podman on my Mac, I can't fix them.

- What do "Server" and "CLI" mean here? The document doesn't explain. Are they alternatives approaches or do you need to run *both* commands?
- Are there any additional steps that this document assumes you've already taken before running these commands? (e.g. installing Podman)
- Once you've started the test databases, how do you run tests? (*I* think I know, but I'm not the target audience.)
- Why would I even want to use Podman? Does it offer some specific advantage?
- Do we really still need this document now that Docker is working great for us?

**Comment by DavideD** [comment]
We don't need to mention podman but I would like to keep the scripts. We can replace them for docker.
Even if we have the options in the tests I find it handy to have them so that I can copy and paste what I need  if I want to start a machine separately (and to test that the build works without TestContainers).

> What do "Server" and "CLI" mean here? The document doesn't explain. Are they alternatives approaches or do you need to run both commands?

* Server: The db
* CLI: the [Command line interface](https://en.wikipedia.org/wiki/Command-line_interface) that you can use to connect to the db. For example `psql` for postgres or `mysql` for MySQL. This might not be available immediately and it's much easier to connect this way if you need to quickly check the content of the db.

> Are there any additional steps that this document assumes you've already taken before running these commands? (e.g. installing Podman)

We can change it so that everything refers to docker and podman is not mentioned.
We could probably link to the Docker homepage in the readme though.

> Once you've started the test databases, how do you run tests? (I think I know, but I'm not the target audience)

We explain this here: https://github.com/hibernate/hibernate-reactive#if-you-have-podman

> Why would I even want to use Podman? Does it offer some specific advantage?

* Installing Podman in the latest Fedora is pretty straightforward, installing docker requires several steps. I don't think having the instructions in our project for it is a lot of additional work for us and you can use the same options for Docker. Also podman run root-less and doesn't require a daemon.
But podman is meant to be a replacement for docker (you can write alias docker=podman) so we can reword everything and rewrite the instructions for docker so that podman is not mentioned. 

* Do we really still need this document now that Docker is working great for us?

I would like to keep track of the options that we need to start the containers so that if I need to start the machines without TestContainers, I can just copy and paste those instructions. This is also useful if we want to test additional options or change some of the existing ones because it doesn't requires changes in the Java code (if I'm just testing something that I'm not ready to include). I'm willing to change them so that they will work for docker instead of podman.

**Comment by DavideD** [comment]
By the way are you saying that this doesn't work? https://podman.io/getting-started/installation
```
brew install podman
```

**Comment by DavideD** [comment]
Nevermind, it seems you need some additional steps to make it work with MacOS

**Comment by gavinking** [comment]
> * CLI: the [Command line interface](https://en.wikipedia.org/wiki/Command-line_interface) that you can use to connect to the db. For example `psql` for postgres or `mysql` for MySQL. This might not be available immediately and it's much easier to connect this way if you need to quickly check the content of the db.

And do you need to type this command in order to run the HR tests?

**Comment by gavinking** [comment]
> We don't need to mention podman but I would like to keep the scripts. We can replace them for docker.
> Even if we have the options in the tests I find it handy to have them so that I can copy and paste what I need if I want to start a machine separately (and to test that the build works without TestContainers).
> 
> > What do "Server" and "CLI" mean here? The document doesn't explain. Are they alternatives approaches or do you need to run both commands?
> 
> * Server: The db
> * CLI: the [Command line interface](https://en.wikipedia.org/wiki/Command-line_interface) that you can use to connect to the db. For example `psql` for postgres or `mysql` for MySQL. This might not be available immediately and it's much easier to connect this way if you need to quickly check the content of the db.
> 
> > Are there any additional steps that this document assumes you've already taken before running these commands? (e.g. installing Podman)
> 
> We can change it so that everything refers to docker and podman is not mentioned.
> We could probably link to the Docker homepage in the readme though.
> 
> > Once you've started the test databases, how do you run tests? (I think I know, but I'm not the target audience)
> 
> We explain this here: https://github.com/hibernate/hibernate-reactive#if-you-have-podman
> 
> > Why would I even want to use Podman? Does it offer some specific advantage?
> 
> * Installing Podman in the latest Fedora is pretty straightforward, installing docker requires several steps. I don't think having the instructions in our project for it is a lot of additional work for us and you can use the same options for Docker. Also podman run root-less and doesn't require a daemon.
>   But podman is meant to be a replacement for docker (you can write alias docker=podman) so we can reword everything and rewrite the instructions for docker so that podman is not mentioned.
> * Do we really still need this document now that Docker is working great for us?
> 
> I would like to keep track of the options that we need to start the containers so that if I need to start the machines without TestContainers, I can just copy and paste those instructions. This is also useful if we want to test additional options or change some of the existing ones because it doesn't requires changes in the Java code (if I'm just testing something that I'm not ready to include). I'm willing to change them so that they will work for docker instead of podman.

Well then I want to see a document with proper step-by-step instructions that don't assume that the reader is living inside your head. If even *I* don't understand your documentation, there is *no chance* that a user will.

**Comment by DavideD** [comment]
> And do you need to type this command in order to run the HR tests?

No.

> there is no chance that a user will.

It worked so far for the intended audience and the intended purpose I had in mind initially.
But I agree that we need to add some additional explanations now.

To be fair, this section is less about Podman and more about starting the databases as containers (without using TestContainers). So we could reword it and make it clear that those instructions will work for Docker as well.

**Comment by gavinking** [comment]
The thing is that it's sitting there right in the root directly of the project, and given its prominent location it needs to look professionally-written. 

Look I know I'm hyper-anal about this, but one of my pet peeves is bad developer-written doc.

I mean, given its prominence, it's only slightly less obnoxious than all the fucking gradle metadata. (How the community considers it reasonable that the front page of every project on GitHub be dominated by build artifacts is just beyond me.)

**Comment by DavideD** [comment]
I will rewrite it and then we can continue the review.

Keep in mind that you can test the instructions replacing `podman` with `sudo docker` (in case you want to try them).

**Comment by Sanne** [comment]
> @DavideD I still don't understand the [podman instructions](https://github.com/hibernate/hibernate-reactive/blob/master/podman.md), and since I can't run Podman on my Mac, I can't fix them.
> 
> * What do "Server" and "CLI" mean here? The document doesn't explain. Are they alternatives approaches or do you need to run _both_ commands?

A podman user will know.

> * Are there any additional steps that this document assumes you've already taken before running these commands? (e.g. installing Podman)

Should we really digress into explaining this? We're not requiring Podman, this is just meant as notes for existing Podman users, as a convenience. (e.g. both Davide and me use Podman daily).

> * Once you've started the test databases, how do you run tests? (_I_ think I know, but I'm not the target audience.)

+1

> * Why would I even want to use Podman? Does it offer some specific advantage?

Yes for a Linux user, Podman is a far better choice than Docker. But I don't feel like we should explain as it comes to many subtle details, this would open a massive digression in our docs.

I think we can assume that a Podman user will know, or will already have made such a choice. Perhaps we just reprhase the document as a "for Podman users"? No need to justify who they are.

As an example: Docker doesn't work on Fedora (not without some significant hackin); `podman` provides the exact same functionality, with the exception of separating some tools, which gives benefits such as being able to run containers without starting them as root.

> * Do we really still need this document now that Docker is working great for us?

For me it's very inconvenient to use Docker, an I benefit from the Podman instructions every single time I run tests.

I actually do have Docker running on my Fedora machines, but purely for the purpose of being able to verify that documented instructions we give for Docker users are working fine - it's not working great for me though.

I might suggest just used Podman and delete the Docker instructions :P


Jokes aside, I agree we should clarify that this is meant purely for existing podman users as an alternative to docker. We might add some links to related sections but I don't think we should expand our docs too much with instructions around it, it's a distraction from Hibernate Reactive.

**Comment by gavinking** [comment]
> A podman user will know.

No, that's not right. The mere words "Server" and "CLI" followed by a line of code don't say anything to anyone. That's not how one writes professional documentation. Seriously, it looks unprofessional and gives a bad impression of quality.

> Yes for a Linux user, Podman is a far better choice than Docker. 

Then write that. That's exactly the sort of explanation I'm looking for.

> I think we can assume that a Podman user will know

And that's exactly the sort of mentality that drives me absolutely *nuts*. Do you really think that if this document is sitting in our root directory, then existing Podman users are the only people who will ever see it?

I mean, *I* see it, and I can't make sense of it! That's enough reason to fix it.

**Comment by Sanne** [comment]
Sure let's clarify the doc and its purpose, not arguing about that.

I'm just not sure about spending too much time about explaining the essentials, I'd rather have it point to the better maintained podman references than to have a section to explain how to install a native tool for each OS out there ...

**Comment by gavinking** [comment]
All I'm asking for is for the document to have a basically-reasonable format. I'm not asking anyone to spend a lot of time on it. I would have already done this myself if I had even half of a clue about Podman.
