### ISSUE TITLE
can't determine native query result types

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#336]
Some native queries wrongly return null, for example:

    s.createNativeQuery("select current_timestamp", Timestamp.class).getSingleResult()

The cause is https://github.com/eclipse-vertx/vertx-sql-client/issues/657

**Comment by gavinking** [comment]
Once this feature is added to Vert.x, it needs to be wired in to `ReactiveLoader.discoverTypes()`.

**Comment by DavideD** [comment]
We merged a workround with https://github.com/hibernate/hibernate-reactive/pull/364
I will leave the issue open until we can apply the proper solution
