### ISSUE TITLE
How to compose inner-lazy-fetching event?

### ISSUE THREAD

**Issue by Xset-s** [hibernate/hibernate-reactive#337]
First of all, i wanna thank you for your amazing reactive library. Its really useful for a huge number of tasks. Reactive approach really impressed me. 

However there are some issues connected with lazy fetching and composing Mutiny events. 

For instance, there is relation between two entities:

```
@Entity
@Table(name = "users")
class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_token_id", referencedColumnName = "id")
    var userToken: UserTokenEntity? = null

    @Column(nullable = true)
    var name: String? = null

    @Column(nullable = false)
    lateinit var email: String
}
```

```
@Entity
@Table(name = "user_tokens")
class UserTokenEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sample_id", referencedColumnName = "id")
    var sampleManyToOne: SampleManyToOneEntity? = null

    ...
}
```

Fetching query:

```
val id: Long = 1

// fetch synchronously user entity

val userEntity: UserEntity = sessionFactory.withSession { session ->
    session.find(UserEntity::class.java, id)
                .invoke {  userEntity ->
                    fetch(userEntity.userToken) // fetch lazy userToken
                }
                .invoke {  userEntity ->
                    // ISSUE: I want to compose here Mutiny event, which will extract sampleManyToOne from just fetched userToken
                    // ofc, there is a chain-function, but the final result won't be userEntity, there will be entity from last chain

                    // fetch(userEntity.userToken?.sampleManyToOne) // exception here: reactive sessions do not support transparent lazy fetching. Apparently, the userEntity.userToken isn't fetched yet
                }
}.await().indefinitely()

// now i'm able to use userEntity.userToken
println(userEntity.userToken)

// and sampleManyToOne fetched from userEntity.userToken
// println(userEntity.userToken?.sampleManyToOne) // lazy exception here

```

In code-comment above i described my issue. After performing that query, i would like to see something like this:
userEntity -> fetched lazy entity userToken -> fetched lazy entity sampleManyToOne

**Comment by gavinking** [comment]
Hi, is this what you're trying to do:

```java
User userEntity = factory.withSession(
	session -> session.find(User.class, id).invokeUni (
		u -> fetch(u.userToken).chain(ut -> fetch(ut.sampleManyToOne))
	)
).await().indefinitely();

```

(Note that I have not tested this code but I *think* it's probably what you need.)

**Comment by Xset-s** [comment]
Thank you, your code works fine :))

And one more thing, how about improving lazy-fetch access (or make it easier to access)? 

For instance, in hibernate-orm there is config property `hibernate.enable_lazy_load_no_trans`, which allows fetching lazy entities without writing huge amount of code (yea, i know, some good programmers call it as anti-pattern approach, but in some cases it can be really useful)

Furthermore i think reactive events can offer other ways to implement something like that.

**Comment by gavinking** [comment]
Well the thing is that I don't think there's any way that this can be made truly transparent with a reactive streams-like approach (you need fibers or whatever). Remember that every operation that results in a database access has to receive its result in a callback.

But also don't forget the prime directive of ORM: avoid lazy fetching altogether (where reasonable) in order to minimize round trips to the DB. Instead, specify the associations you want fetched upfront in the query.

**Comment by Xset-s** [comment]
Yes, you are absolutely right, with experience comes awareness that lazy fetching has a lot of pitfalls and it must be used very carefully in order to prevent performance troubles. 

However, i think its possible to make it easier to fetch them (synchronously or asynchronously). 

For example, developer takes risks of low performance (or maybe his app has already taken into account all the subtleties), so he modifies his config:

```
<property name="hibernate.current_session_context_class" value="thread"/>
<property name="hibernate.enable_lazy_load_no_trans" value="true"/>
```

Now he is able to write anywhere in his code something like that:

```
// fetch for me this entity synchronously please:

val userToken = userEntity.userToken
println("${userEntity.name} has ${userToken.id}, thats great!")

...

// ok, but for now let me fetch it providing reactive magic (asynchronously):

fetch(userEntity.userToken) // it uses current context session, so developer doesn't need to open it every time
    .doAfterFetching( userToken -> println("${userEntity.name} has ${userToken.id}, and thats great!") )
    ...

```

I think my ideas sound quite strange, just because reactive approach assumes callbacks and non-blocking fetching. But i think combination of blocking and non-blocking will improve your library and make it more flexible, for me as well xD

**Comment by gavinking** [comment]
Oh you mean you want a contextually-bound reactive session?

Yes, that's going to be possible in Quarkus based on Reactive Contexts. 

@FroMage would know if we already support this, but we certainly plan to.

**Comment by gavinking** [comment]
Closing this one, because it was more of a question than an issue. (Which is fine, since we don't yet offer any other way to ask questions!)
