### ISSUE TITLE
Merging OneToMany collection (after removing)

### ISSUE THREAD

**Issue by Xset-s** [hibernate/hibernate-reactive#344]
Hello, i've just caught strange behavior. It looks like a bug (maybe somehting related to the query cache), but it can also be misuse of sessions' methods, so if i did something wrong, let me know.

There are two entities:

SampleEntity:

```
@Entity
@Table(name = "sample_entities")
public class SampleEntity implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;

    @Column(name = "sample_field")
    public String sampleField;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sampleEntity")
    public Set<SampleJoinEntity> sampleJoinEntities;
}
```

SampleJoinEntity:

```
@Entity
@Table(name = "sample_join_entities")
public class SampleJoinEntity implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sample_entity_id", referencedColumnName = "id")
    public SampleEntity sampleEntity;
}
```

As you can see there is ManyToOne relation, which uses SampleEntity's id as a reference.

Let's persist them:

```
/* Persist one SampleEntity and 5 SampleJoinEntities */

// SampleEntity
final SampleEntity sampleEntity = new SampleEntity();

sampleEntity.sampleField = "Test";

factory.withTransaction((session, transaction) -> session.persist(sampleEntity))
		.await().indefinitely();

// SampleJoinEntities
for (int i = 0; i < 5; i++) {
	final SampleJoinEntity sampleJoinEntity = new SampleJoinEntity();

	sampleJoinEntity.sampleEntity = sampleEntity;

	factory.withTransaction((session, transaction) -> session.persist(sampleJoinEntity))
			.await().indefinitely();
}
```

Let's refresh SimpleEntity:

```
// Refresh our SampleEntity and fetch SampleJoinEntities
factory.withSession((session) -> session.refresh(sampleEntity)
		.then(() -> session.fetch(sampleEntity.sampleJoinEntities)))
		.await().indefinitely();

// Debug SampleJoinEntities
System.out.println("sampleJoinEntities: " + sampleEntity.sampleJoinEntities);
```

Now i want to remove all persisted SampleJoinEntities:

```
// Let's remove all SampleJoinEntities
sampleEntity.sampleJoinEntities.forEach(entity -> {
	factory.withTransaction((session, transaction) -> session.remove(entity))
			.await().indefinitely();
});
```

And the final step:

```
// Now let's do some work with SampleEntity and then merge it
sampleEntity.sampleField = "I've changed!";

// ISSUE: IT THROWS EXCEPTION HERE!
factory.withTransaction((session, transaction) -> session.merge(sampleEntity))
		.await().indefinitely();
```

It throws this exception:

```
Caused by: org.hibernate.HibernateException: java.util.concurrent.CompletionException: org.hibernate.AssertionFailure: Unexpected access to the database
```

After conducting several experiments, i came to the conclusion, that this issue is related to OneToMany collection (if you remove sampleJoinEntities field and fetch sampleJoinEntities using ordinary query, everything will be ok) and it throws this exception only when you are trying to merge entity after removing some entities from collection (see code above, "// Let's remove all SampleJoinEntities")

Full stack: https://pastebin.com/xhuvJ71T

Sample project: 
[SampleProject.zip](https://github.com/hibernate/hibernate-reactive/files/5168106/SampleProject.zip)

**Comment by gavinking** [comment]
OK so it seems to me that this bug is ultimately the result of allowing detached objects to be passed to `refresh()` and `remove()` which is really an ancient legacy Hibernate 1/2 thing from back in the days of `saveOrUpdate()`, which we've already chosen not to support here.

I think HR should do things just as specified by JPA and throw an exception in these cases. We would be doing our users a favor by not letting them shoot themselves in the foot, and ourselves an even bigger favor because we won't have to support users with shot feet, and we won't have to fix this bug which looks like rather a lot of work involving copy/pasting a really deep chain of logic from core and changing all the return types to `CompletionStage`.

**Comment by gavinking** [comment]
I've done the work but I can't push right now because my ISP sucks.

**Comment by Xset-s** [comment]
Ok, following JPA spec is a great thing, but what about my case? I mean, how to rewrite correctly my code in sample case above to achive the same functionality? Now it seems to me, than instead of refresh (or merge) i should always use ```session.find``` method (if we are talking about detached entities as ```SampleEntity``` in this example).

**Comment by gavinking** [comment]
Well you can still use `merge()`, that method is designed to be safe, but you have to *use* the returned object, not ignore it. And yes, you should definitely use `find()` instead of `refresh()` here.

**Comment by DavideD** [comment]
Done https://github.com/hibernate/hibernate-reactive/pull/346
