### ISSUE TITLE
return CompletionStage<Void> instead of CompletionStage<Session> from voidlike session methods

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#347]
Currently operations like `remove()` return `CompletionStage<Session>` or `Uni<Session>`, but I'm now inclined to think that this is useless given the idioms we have for obtaining a reference to the `Session`, and I'm considering changing the return types to `CompletionStage<Void>` and `Uni<Void>`.

Any objections?

**Comment by DavideD** [comment]
Doesn't it make sense for something like
```
openSession().persist().thenCompose( s -> s.remove() ).thenCompose( s -> s.flush());
```
I'm not sure if this scenario is that useful in a real case but it seems to make sense.
I have to admit that the persist confused me initially because I was expecting it to return the persisted object.

Maybe you can add some examples of the benefit of removing it?

**Comment by gavinking** [comment]
Well that code fragment doesn't really make sense because the two idioms we have left are:

- `openSession()` and assign the result to a variable, or
- (better) use `withSession()` and you get it assigned to a parameter for free.

We don't have the version of `openSession()` which returns a `CompletionStage`/`Uni` anymore.

**Comment by DavideD** [comment]
Right, I wasn't thinking about the method in the factory but I forgot we removed it.

I guess ultimately we will have something like this instead:

```
session.persist().thenCompose( () -> session.remove() ).thenCompose( () -> session.flush());
```

Looks good to me

**Comment by DavideD** [comment]
Done
