### ISSUE TITLE
advanced lock options

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#351]
Currently we have no way to:

- request `PessimisticLockScope.EXTENDED`, (`javax.persistence.lock.scope`), or to 
- specify a lock timeout (`javax.persistence.lock.timeout`).

Obviously I don't want to use stringly-typed map keys for this, so we need to invent some sort of API.

**Comment by gavinking** [comment]
The obvious way would be to let them pass a `LockOptions` instance, of course.

**Comment by gavinking** [comment]
Well, actually, upon further research, the only database we currently support that has a `WAIT n` clause is MariaDB. And it's not clear to me that we should (at this stage) be adding complexity to our APIs just for users of MariaDB.

Now, when (someday!) we support _Oracle_, we're going to need it ... but who knows when that will be?

**Comment by gavinking** [comment]
So I've added the internal infrastructure to support this, because I think it actually improves the internal APIs, but I have not exposed it via the API just yet. It will be easy to uncomment the code when someday we get a reactive driver for Ora.

**Comment by jworreth** [comment]
+1 here,

Could you please expose what is needed for oracle?
