### ISSUE TITLE
Session.asReference()

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#355]
Hibernate has historically always let you use references to detached objects to set up associations. TBH I'm not even sure if the JPA spec says anything at all about this practice, or if other JPA implementations allow it.

But there are some reasons to think it's a bad thing: it makes it harder, perhaps, for users to keep track of which objects are managed and which are detached in their object graph.

We could *disallow this* (while adding a setting to allow you to recover the legacy behavior), and add a new operation to the `Session` that lets you transform a detached object into an unfetched reference.

```java
Parent detachedParent = ... //detached object
Child newChild = new Child();
newChild.setParent( session.asReference(detachedParent) );
session.save(newChild);
```

TBH it's kinda surprising to me that we don't already *have* an operation like that.

**Comment by gavinking** [comment]
(Note that you can sorta use `merge()` for this in JPA, but it has the nasty side-effect of hitting the database.)

**Comment by gavinking** [comment]
I've added an overloaded `getReference()` method in #356.

Now I'm wondering if we should add a setting to make it illegal to old references to detached objects from the managed object graph. (This would have to be an optional behavior.)

**Comment by DavideD** [comment]
Fixed https://github.com/hibernate/hibernate-reactive/pull/356!
