### ISSUE TITLE
extra connection pool connection-related properties

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#357]
`SqlConnectionOptions` inherits a bunch of properties from `NetClientOptions` and it seems to me that some of these are relevant, and should be configgable via Hibernate properties. For example, both of the following look useful:

- `hibernate.vertx.pool.idleTimeout`
- `hibernate.vertx.pool.connectTimeout`

@vietj should we add these two properties? Are there any others that would be useful to someone configuring a connection pool for use in HR?

**Comment by gavinking** [comment]
@vietj any comment?

**Comment by vietj** [comment]
they are relevant, however as we want to improve the pool in 4.x and we might have pool properties achieving something similar but at an higher level (like a pool max time idle and pool connection acquisition timeout) that would replace them. In the mean time they can be useful.

**Comment by gavinking** [comment]
> In the mean time they can be useful.

Alright then, I will add them. We can always change them later.

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/commit/f299741cef721c1b48b540dd51b352fd801b5e06
