### ISSUE TITLE
Test for find after flush

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#362]
A user had an issue and mentioned this use case. I tried it and it works but I couldn't find any test case for it.

**Comment by gavinking** [comment]
@DavideD So, I mean, I'm not *against* adding tests that just re-test basic functionality of the underlying Hibernate session, but I don't think we need to go out looking for them, and I definitely don't think we need to open an issue for every new test.

**Comment by DavideD** [comment]
OK, I don't plan to make it on habit.

Thanks

**Comment by gavinking** [comment]
No problem.
