### ISSUE TITLE
persist(), merge(), remove(), refresh() on Mutiny.Session

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#370]
With the Mutiny API changes I requested in 0.8.0, the new `call()` method which replaces `invokeUni()` is now overloaded and this creates an ambiguity when you do:

```java
session.find(Book.class, id).call(session::remove)
```

And so you have to write:

```java
session.find(Book.class, id).call( (b) -> session.remove(b) )
```

So I think we should get rid of the overloading of `persist()`, `merge()`, `remove()`, and `refresh()` on `Mutiny.Session`.

But what should we do instead?

1. Just leave them as unary operations?
2. `persistAll(Object... entities)` 
3. `persist(Object entity, Object... moreEntities)`

I lean toward 2, but eeeeewww, shades of JDO's `makePersistentAll()`!

**Comment by DavideD** [comment]
Definitely 2 or 3. I use that operation often for tests.

What's the drawback of using 3?

**Comment by gavinking** [comment]
> What's the drawback of using 3?

You can't pass an array to it, or use it as a method ref.

**Comment by DavideD** [comment]
I think I prefer 2 as well

**Comment by gavinking** [comment]
> Thanks, I think I prefer 2 as well

Yes, it seems the right thing to do.

**Comment by gavinking** [comment]
Interestingly, after the changes I requested, the Mutiny APIs are *much* more friendly to passing session methods by reference. So this is actually really useful.
