### ISSUE TITLE
lazy collections and bytecode enhancer

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#374]
So I've run into what I consider to be some pretty unexpected behavior of Hibernate ORM when the bytecode enhancer is enabled with `enableLazyInitialization = true`.

There's two aspects of the behavior that, naïvely, look suboptimal to me, at least in the context of HR:

1. By default, lazy collection are marked for field-level lazy fetching. I gotta say I just don't see much advantage to this, how is it better than the collection proxy? Indeed, it's arguably worse, since direct field access doesn't get intercepted. That's tolerable for fields that the user has *explicitly* marked for lazy fetching, but not for this *implicit* behavior.
2. When you *do* fetch the collection, `AbstractEntityPersister.initializeLazyProperty()` doesn't set the field of the entity like what it does for other lazy fields. That's either a bug, or it's due to how we're calling this method in Hibernate reactive. Whatever, it means that `AbstractEntityPersister.initializeLazyProperty()` has a pretty fragile contract.

@Sanne I know you're an expert on this stuff, can you help me understand all this please?

**Comment by gavinking** [comment]
@Sanne the workaround in #375 solves problem (2) at least for HR. But shouldn't this be done in core?

**Comment by Sanne** [comment]
Hi Gavin, I'm not sure on terminology which might be important; and no I'm not the expert in this area, I've just started recently to fix some issues with it in the context of making the existing stuff work in Quarkus. What do you mean by `field-level lazy fetching` exactly?

And by "bytecode enhancer is enabled", I assume you're referring to build time enhancement?

It might help to keep in mind that we can't do proxies in Quarkus, as you can't have a proxy compiled to native image; so we're focusing on bytecode manipulation of the class - which wasn't indeed as stable as I'd like it, but it has other advantages as well over proxies: the type identity is consistent at runtime, which helps with various subtle bugs people had, e.g. integrating with other tools and frameworks.

Regarding field access: we actually intercept field accessors too and re-map them; in particular Panache likes this.

So _conceptually_ I don't feel it's a bad choice, but in practice this is possibly not very mature yet; we certainly had a list of issues manifesting since Quarkus made this model more popular. So please give me some more context on what didn't work - did you have a problem in Quarkus, or a different test?

**Comment by Sanne** [comment]
There's one more novelty to keep in mind; we now support "enhanced proxies": this allows some loading patterns to perform much better.
See Steve's blog for a description:
 - https://in.relation.to/2019/07/30/bytecode-proxy/

**Comment by gavinking** [comment]
> What do you mean by field-level lazy fetching exactly?

I mean `enableLazyInitialization = true`.

> And by "bytecode enhancer is enabled", I assume you're referring to build time enhancement?

Right. In Gradle.

> It might help to keep in mind that we can't do proxies in Quarkus

Yeah but that's doesn't affect *collection* proxies. They're just regular classes.

> Regarding field access: we actually intercept field accessors too and re-map them

Perhaps that works in Quarkus, but it's not working for me, outside Quarkus.

**Comment by Sanne** [comment]
> > Regarding field access: we actually intercept field accessors too and re-map them
> 
> Perhaps that works in Quarkus, but it's not working for me, outside Quarkus.

Field access requires enhancing the caller (the application) so it's not easy to setup generally; Stephane did some extra magic in Quarkus. So I agree it's not the best choice as _general purpose_ strategy, but it's not a bad choice in Quarkus. Just to clarify the context.

So yes I am confused like you by what you say in #2 , that seems odd; we should ask the real experts ( @sebersole @dreab8 ) , but it might be easier to figure out what you mean if you have a failing test they could toy with?

It seems plausible that it's more likely a fragile contract than a bug, as I'd be very surprised if we had no tests covering this area (and no complaints).

**Comment by gavinking** [comment]
@Sanne @sebersole I think perhaps I've tracked it down to this commit:

https://github.com/hibernate/hibernate-orm/commit/cc01f2561dbca95bd58048f85e283ba1719ee588

**Comment by gavinking** [comment]
Specifically, this change:

https://github.com/hibernate/hibernate-orm/commit/cc01f2561dbca95bd58048f85e283ba1719ee588#diff-7c0b4e29c08a30311a237f9811d44861L1057-R1088

**Comment by Sanne** [comment]
Thanks for digging! Interesting, so by reading the https://hibernate.atlassian.net/browse/HHH-11147 description it seems intentional to support `getReference`, which indeed does make good use for a non-initialized entity.

**Comment by gavinking** [comment]
>  it seems intentional to support `getReference`, which indeed does make good use for a non-initialized entity.

This is a *collection proxy*, not an entity proxy.

**Comment by gavinking** [comment]
> Specifically, this change:

Well, no, actually I now realize there's two parts to this:

### `initializeLazyProperty()` doesn't fetch the collection

First, `initializeLazyProperty()` doesn't fetch the collection. In fact, that's probably sorta OK in Hibernate ORM, where collection fetching happens transparently when you access the collection. 

But it's a huge pain in HR, where `fetch()` is an explicit operation, because first I have to explicitly fetch the field, and then I have to explicitly fetch the collection. But OTOH perhaps there's a way for my to hide that from the user. I will see if I can.

Even so, it seems like a useless behavior: why make collection fields lazy in the first place? There doesn't seem to be any useful purpose to that, at least not that I can think of!

### `initializeLazyProperty()` doesn't set the collection wrapper to the field

Now, this seems to be simply wrong. For other lazy properties, `initializeLazyProperty()` sets the field value into the entity, but this doesn't happen for a collection wrapper.

**Comment by gavinking** [comment]
> But OTOH perhaps there's a way for me to hide that from the user. I will see if I can.

Oops, no, there's not. I can't.

**Comment by gavinking** [comment]
The thing is, I guess I also question `EnhancementHelper.includeInBaseFetchGroup()`, which returns `false` for lazy collections. I don't think it should.

**Comment by gavinking** [comment]
> Now, this seems to be simply wrong. For other lazy properties, `initializeLazyProperty()` sets the field value into the entity, but this doesn't happen for a collection wrapper.

Oh, right, so I guess the assumption is that you're only going to access the collection via getter method. So it's *inconsistent* with what happens for other fields, but it's not actually broken.
