### ISSUE TITLE
finish javadoc for org.hibernate.reactive.provider.service package

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#398]
Some of the classes in this package don't have any Javadoc at all. And in a couple of cases it's non obvious what they are for or when they're used.

@Sanne I think most of these are your classes, though a couple of them are probably mine.

**Comment by Sanne** [comment]
thanks, I can polish these next week.

**Comment by gavinking** [comment]
Great, thanks.

**Comment by DavideD** [comment]
@Sanne any update on this? If you are busy I can take care of it

**Comment by Sanne** [comment]
@DavideD yes if you could steal this from me that would be best. Thanks!

**Comment by gavinking** [comment]
Thanks man.
