### ISSUE TITLE
Hibernate RX alongside regular Hibernate

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#40]
While I admit I have not actually *tried*, from my understanding of how the code works, I conclude that it's currently impossible to have reactive sessions alongside regular sessions for the same `SessionFactory`. It might even be impossible to have them coexist in the same *program*.

Right, @DavideD?

I think that's something we eventually need to fix.

**Comment by DavideD** [comment]
I think you are correct, but I will check.

**Comment by gavinking** [comment]
Alright, so a major roadblock to resolving this problem is going to be the fact that we're hijacking Hibernate's regular `PERSIST`, `FLUSH`, etc, event types to do implement our own differently-semantic'd operations.

So today I tried to fix this by breaking us away from Hibernate's `EventType`s and event processing and, surprisingly, I failed! It looked, naively, like there would be about two or three different ways to do this but not a single one of them panned out, and not even with the sort of "adjustments" I made in #36, could I do it this way. Without some sort of a more major change in core, this one is actually much harder than it looks.

The problems relate to the whole interrelated lifecycles of `EventType`s, the `EventListenerRegistry` and `CallbackRegistry`. You might think you can implement this stuff without even using events at all, but that's not, AFAICT, the case, since you've got no other way of getting access to the  `CallbackRegistry`. And you need it!

So to solve this issue we would need to work with the Hibernate core team to add a well-defined way to augment the set of event types.

**Comment by gavinking** [comment]
Take note ☝️@Sanne  :-)

**Comment by Sanne** [comment]
I don't think there's any desire to use one single SessionFactory both in reactive and in non-reactive way?  IMO either you're the kind of developer liking reactive APIs, or not ...

If there's some 10% of people that are say migrating an application and need both APIs available "for some time" I think it would be perfectly fine for them to start two differently configured instances. 

Also, assuming we don't develop some kind of sick adapter, they'll need two differently configured datasources anyway.

**Comment by gavinking** [comment]
> I don't think there's any desire to use one single SessionFactory both in reactive and in non-reactive way?

*Perhaps* not, (it's not clear to me) but I'm pretty sure our current implementation won't even let you have one factory for reactive and one for normal.

**Comment by gavinking** [comment]
> Also, assuming we don't develop some kind of sick adapter, they'll need two differently configured datasources anyway.

I don't think that's right. We already use regular JDBC for schema export right alongside Vert.x for DML.

**Comment by DavideD** [comment]
> assuming we don't develop some kind of sick adapter, they'll need two
differently configured datasources anyway

 Right now we are using the orm properties to create the connection with
the reactive drivers. So, I'm not sure this is going to be an issues.

**Comment by gavinking** [comment]
> Right now we are using the orm properties to create the connection with
> the reactive drivers. So, I'm not sure this is going to be an issues.

Exactly. @Sanne if you look at the new example app I added, I actually use one line in `persistence.xml` to completely configure Hibernate RX.

**Comment by Sanne** [comment]
ok so configuring two datasources won't be hard apparently, but I still don't think this should be a goal - not for the first version at least :)

> but I'm pretty sure our current implementation won't even let you have one factory for reactive and one for normal.

Why not? Global statics being used to hack something? Bear with me, I've not been able to follow all changes.

**Comment by gavinking** [comment]
Because of code like this:

<https://github.com/hibernate/hibernate-rx/blob/%2336/hibernate-rx-core/src/main/java/org/hibernate/rx/service/RxIntegrator.java>

It completely replaces Hibernate's event listeners.

**Comment by gavinking** [comment]
Related discussion here: <https://github.com/hibernate/hibernate-rx/pull/66#issuecomment-591949557>

**Comment by gbadner** [comment]
FYI, a PR for adding custom `EventType` and listeners is getting close:
https://github.com/hibernate/hibernate-orm/pull/3332

**Comment by gavinking** [comment]
@gbadner Excellent! I was going to ask you about that.

**Comment by Sanne** [comment]
FYI Gail's patch was merged in Hibernate ORM, but keep in mind that next ORM's release having it is `5.5.0.Beta1`  (we bumped the minor version).

So ORM 5.4.x is now "stable" for sake of Quarkus, while 5.5x is more suited for fast evolving work like this.

**Comment by gbadner** [comment]
@gavinking, @Sanne, I see that @sebersole suggested a change in how listeners get contributed:
https://github.com/hibernate/hibernate-orm/pull/3332#discussion_r409576346

I'll create a new PR to do that.

**Comment by gavinking** [comment]
> So ORM 5.4.x is now "stable" for sake of Quarkus, while 5.5x is more suited for fast evolving work like this.

Ok, but @emmanuelbernard wants this "fast evolving work" in the next release of Quarkus :-)

**Comment by gavinking** [comment]
Anyway, thanks for this @gbadner!

**Comment by sebersole** [comment]
FWIW I am working on a PR for my suggestion

**Comment by gbadner** [comment]
OK, thanks @sebersole!

**Comment by Sanne** [comment]
> > So ORM 5.4.x is now "stable" for sake of Quarkus, while 5.5x is more suited for fast evolving work like this.
> 
> Ok, but @emmanuelbernard wants this "fast evolving work" in the next release of Quarkus :-)

Sure. He also wants JPA 3... Either way, we'll have the option to either upgrade Quarkus to ORM 5.5 or backport a selection of patches we need for RX to 5.4.

I believe the decision can be deferred, but I'm betting on our need to deliver both Rx and JPA 3 at about the same time.

**Comment by sebersole** [comment]
I need a clarification.  The PR Gail originally worked on provided the ability for RX to register completely new event-types, not just register listeners against the standard set of event-type.

I guess the first question... is that really a requirement here?  Limited to just this discussion thread, I have not seen any mention of wanting to register custom event types.  If that is really the intent, how do y'all envision these custom event types being used/consumed?

At a higher level, I agree with Gavin about the intricacies of the relations between the various actors.  In fact a lot of my thought process on the improvement I was working on centered around ways to better manage the lifecycle between EventType, EventListenerRegistry, etc.  I was already itching to model the relation between these a bit differently.  I resisted and planned to just do those changes in the 6.0 version.  But then I read the rest of the discussion here and I think a lot of the changes I was envisioning would be helpful here.

So let me know about whether custom event-types are needed and I can work from there for now.  If they are, I obviously also need to know how you expect to consume them (fire those events)

**Comment by gavinking** [comment]
> The PR Gail originally worked on provided the ability for RX to register completely new event-types, not just register listeners against the standard set of event-type.

Yep, that's the functionality I wanted. The basic issue is that, for example, our `persist()` operation is really just a bit too different to the semantics of the similarly-named operation in core, and we just can't really reuse much of the same orchestrating code. We're not really using our listeners to slightly adjust the behavior of `Session.persist()`, they're actually implementing a completely different operation.

So replacing the listeners for the built-in event types was really not quite right: we don't actuallu *need* to replace them, and indeed replacing them has the bad side-effect of breaking those operations in core, which I think is a really bad thing. The bits of core that we're reusing are really the bits at the level of persisters and loaders (though they need to be customized a bit, of course), and the persistence context, and everything hanging off the `SessionFactory`.

Sure, there's plenty of commonality between, for example, `DefaultRxLoadEventListener` and `DefaultLoadEventListener`, but little opportunity for code reuse between them, since the signatures are all different, and the actual implementations have to be somewhat rewritten in terms of streams. More importantly, `RxPersistEventListener` and `PersistEventListener` actually have different method signatures and, IMO, are pretty much unrelated types. `RxPersistEventListener` isn't a subtype of `PersistEventListener`, and so it wouldn't really make sense for it to share the same listener queue, even if doing so *didn't* break anything.

Not sure if that was a great explanation.

**Comment by gavinking** [comment]
@sebersole by the way, just FYI, I already tried a different solution which was to simply not use core's event listener registry at all and maintain our own registry of event listeners. The problem with that was that then it was essentially impossible to get hold of certain other things I needed (the thing that invokes JPA lifecycle callbacks) which are only available via some sort of injection into the event objects, IIRC.

**Comment by sebersole** [comment]
Ok, thanks.  That's what I was after.  

Regarding the last comment, yep, that's part of the restructuring I was contemplating anyway.

**Comment by sebersole** [comment]
Stating this another way.. please correct me if I am wrong.

You really don't even care if RX uses Hibernate's "event system" at all for handling the various RX calls.  You really just need to be able to access the JPA callbacks (CallbackRegistry).

Assuming I am correct, do you have a preference?  Register custom event-types or provide a way to access JPA callbacks?

**Comment by gavinking** [comment]
> You really don't even care if RX uses Hibernate's "event system" at all for handling the various RX calls. 

It's not necessary, but I think it would probably be nicer.

> You really just need to be able to access the JPA callbacks (CallbackRegistry).

Yes, that's correct.

> Assuming I am correct, do you have a preference

I would prefer it if we could register new event types with Hibernate's existing infrastructure.

**Comment by Sanne** [comment]
> > I don't think there's any desire to use one single SessionFactory both in reactive and in non-reactive way?
> 
> _Perhaps_ not, (it's not clear to me) but I'm pretty sure our current implementation won't even let you have one factory for reactive and one for normal.

I think we need to really solve at least the ability to not affect a regular SessionFactory just because one happens to have this project on the classpath.

Can I take this issue?

**Comment by gavinking** [comment]
> Can I take this issue?

Sure, but be aware that I suspect it's quite a lot of work. Getting the event handler registration sorted out so that our listeners don't override the built-in listeners is just a *start*.

I'm pretty sure that our `EntityLoader`s are also going to break regular Hibernate because they return `CompletionStage` from methods of type `Object`.

**Comment by Sanne** [comment]
ok, I'm very time constrained but I'd like to try.

**Comment by Sanne** [comment]
Just an update, I started working on this now. Sorry for the delay, quite swamped :(

I'll need another batch of fixes in ORM for this; essentially my plan is to have the bootstrap code of Hibernate Reactive slightly different than the vanilla Hibernate ORM: rather than have it use the `Integrators` API to register new and alternative implementations of `Service`s, I'll have them preloaded into a new default set of services.

This way the Hibernate Reactive project will need to be booted explicitly as reactive; in terms of JPA users will have to choose a different `PersistenceProvider` implementation.

Speaking of: the current PersistenceProvider implementation in Hibernate Reactive is in package `org.hibernate.reactive.jpa.impl` : you have a recommendation for the package name?

Its fully qualified classname will need to be used by end users, so it becomes API (for some definition..). We could also cheat, and match any string we like without it necessarily having the right package name.

**Comment by gavinking** [comment]
> in terms of JPA users will have to choose a different `PersistenceProvider` implementation.

So you'll need to explicitly specify a `<provider>` in `persistence.xml`?

That sounds reasonable.

> you have a recommendation for the package name?

`org.hibernate.reactive.provider`

I could also live with "boot".

**Comment by Sanne** [comment]
Thanks, I'll move it to `org.hibernate.reactive.provider`.

Now that I've made some progress, I realize the non-JPA boot is going to look even more clumsy :(

I'll see if I can avoid making it too complex, but I suppose we might need to follow up on this with a new boot API.

**Comment by gavinking** [comment]
> I realize the non-JPA boot is going to look even more clumsy 

You mean starting it with `StandardServiceRegistryBuilder()`?

**Comment by Sanne** [comment]
yes. I've introduced a `ReactiveServiceRegistryBuilder` now.. still work in progress.

**Comment by Sanne** [comment]
done in #214
