### ISSUE TITLE
Upgrade to Vertx 3.9.4

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#408]

**Comment by gavinking** [comment]
So I guess that means we can remove the workaround for https://github.com/eclipse-vertx/vertx-sql-client/issues/766

**Comment by gavinking** [comment]
@Sanne you assigned yourself but if you prefer I can handle this one....

**Comment by Sanne** [comment]
@gavinking sorry just seen this now. I've sent a PR, feel free to ignore it or re-work it?
