### ISSUE TITLE
PoolConnection and RxQueryExecutor are almost the same thing

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#41]
@DavideD what is the reason behind having two things here, that have almost the same methods?

Do you object if I merge them into one class?

**Comment by DavideD** [comment]
The initial idea was to use the connection to returns the raw results while the RxQueryExecutor is a layer that can convert the result into entities or prepare the parameters. I suppose in practice there is not much difference. Can you wait a bit longer before doing it? Those classes might become more complicated once we have added queries support. If it doesn't happen or if you have strong opinion about it, feel free to merge them into one.

**Comment by gavinking** [comment]
It can wait.

**Comment by DavideD** [comment]
These classes have a different name after https://github.com/hibernate/hibernate-reactive/issues/25 and https://github.com/hibernate/hibernate-reactive/issues/111:
- [SqlClientConnection](https://github.com/hibernate/hibernate-reactive/blob/master/hibernate-reactive-core/src/main/java/org/hibernate/reactive/impl/SqlClientConnection.java)
- [ReactiveQueryExecutor](https://github.com/hibernate/hibernate-reactive/blob/master/hibernate-reactive-core/src/main/java/org/hibernate/reactive/impl/ReactiveQueryExecutor.java)

**Comment by gavinking** [comment]
I have cleaned up the `ReactiveConnection` API and removed ReactiveQueryExecutor.

This is now *much* cleaner.

And dependencies to Vert.x are much better-isolated.

**Comment by DavideD** [comment]
That't great @gavinking but could you please send PR like everybody else and not push directly on master, please? Mainly to make it easier for us to keep track of what's going on in the project and have a chance to have a quick look and ask questions. Thanks
