### ISSUE TITLE
improvement to hi/lo generator

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#411]
In Hibernate core fetching of a new hi value blocks concurrent access to the hi/lo generator.

@cescoffier suggests the following idiom to do the same thing in Vert.x

<blockquote>

I have a specific component used by the rest of the connector. 
This component exposes an asynchronous API, let's call this method `getId` and you pass a callback invoked with the retrieve id. 
The component handles a queue of requests. In this queue, you store the current Vert.x context and the callback. When you needs an id, you do something like:

```java
public void getId(Consumer<Id> callback) {
   if (idIsAvailable()) {
      callback.call(available);
   } else {
      Context ctxt = Vertx.getOrCreateContext();
      queue.add(new Request(context, callback);
      retrieveIfNeeded();
   }
}
```

`retrieveIfNeeded` verify is there is a retrieval in progress:

```java
private void retrieveIfNeeded() {
   if (!inProgess ) {
        retrieve();
   }
}

private void retrieve() {
    inProgress = true;
    retrieveTheIds(ids -> {
         invokeCallbackAndClearTheQueue(ids);
         inProgress = false;
   );
}
```

When invoking the callbacks, we make sure it's invoked on the right context:

```java
ctxt.runOnContext(() -> callback.call(id));
```

</blockquote>

**Comment by cescoffier** [comment]
BTW, do you need some kind of periodic task or enforce a delay between 2 retrievals?

**Comment by gavinking** [comment]
> BTW, do you need some kind of periodic task or enforce a delay between 2 retrievals?

No, this is something that happens when we run out of lo values.
