### ISSUE TITLE
Remove warnings during doc generation

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#413]
Example:
```
asciidoctor: WARNING: introduction.adoc: line 510: invalid style for listing block: java
```

```
ReactiveLoaderBasedResultSetProcessor.java:54: warning - Tag @link: reference not found: Loader#processResultSet
```

**Comment by gavinking** [comment]
> asciidoctor: WARNING: introduction.adoc: line 510: invalid style for listing block: java

Well yeah, but I would love to know why the fuck ASCII doctor can't highlight code fragments for me and instead insists that a java listing has to be a whole fucking class!

We should just open a bug against ASCII doctor because that behavior is simply rubbish.

**Comment by DavideD** [comment]
> We should just open a bug against ASCII doctor because that behavior is simply rubbish.
 
This was actually an issue with the IntelliJ plugin
