### ISSUE TITLE
Test with Vertx SQL client 4

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#417]
Should we create a branch upstream for [vert.x sql client 4](https://github.com/eclipse-vertx/vertx-sql-client/releases/tag/4.0.0-milestone5) and make it work with it?

**Comment by gavinking** [comment]
That sounds like a good idea. And that way we can try adding some simple tests for SQL Server.

**Comment by DavideD** [comment]
The new branch is now upstream:
https://github.com/hibernate/hibernate-reactive/tree/vert.x-4

**Comment by gavinking** [comment]
> The new branch is now upstream:
> https://github.com/hibernate/hibernate-reactive/tree/vert.x-4

Excellent!
