### ISSUE TITLE
pessimistic locking

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#43]
We've been ignoring `LockMode`s and `LockOption`s, which is reasonable because we don't have transactions yet. However, most of the code to support them is already there, I think it just means adding some of the plumbing to let the user pass them in.

**Comment by gavinking** [comment]
Note that this includes adding `RxSession.lock()`, along with supporting `LockModes` in `find()` and `Query`.

**Comment by gavinking** [comment]
Now that we have a prototype for transactions, we can work on adding support for pessimistic locking.

**Comment by gavinking** [comment]
This is now done, except for the `Session.lock()` method.

**Comment by gavinking** [comment]
Shit, I didn't actually mean to push that to master. I meant to push it to the `txns` branch. Uff.

Well, OK, it's fine, no harm done, I guess.

**Comment by gavinking** [comment]
I've opened #142 to cover the missing `lock()` method, which is much more work, and much less useful.

Since I accidently pushed this work already, I might as well close the issue.

Not my *most* competent moment.

**Comment by DavideD** [comment]
No worries, it happens. I'm closing the issue.

**Comment by emmanuelbernard** [comment]
ahaha, you should see Gavin's SVN history. It's full of ops, fixed now, damn now fix, shit I can't code today etc :D

**Comment by gavinking** [comment]
@emmanuelbernard I'm trying to be a better person.
