### ISSUE TITLE
Update comments for ObjectType class

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#433]
The comments in the source implies that we should remove it but it's something that we want to keep because the Vert.x client 
has some special implementations of `getObjects()` for special database types.

**Comment by gavinking** [comment]
I agree that we don't need it. But I kinda like it. I feel like it would be a better fallback than SeriakizabkeType which I think core uses.

**Comment by gavinking** [comment]
So anyway, the point is I was keeping it around for that reason...

**Comment by DavideD** [comment]
OK, how come do you prefer it to `SerializableType`? We at least need to update the comments

**Comment by gavinking** [comment]
Well because the Vert.x driver has some useful implementations of `getObject()` for special database types.

**Comment by DavideD** [comment]
OK, I will update the comments and give a bit of explanation instead of removing it

**Comment by gavinking** [comment]
Might be worth opening an issue mentioning the idea.

**Comment by DavideD** [comment]
I've updated the issue instead of creating  a new one

**Comment by DavideD** [comment]
By the way, could you tell me what is this TODO about? https://github.com/hibernate/hibernate-reactive/blob/60ae3507abea1ad2ddae1e940f6909ee28a991bb/hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveSessionFactoryImpl.java#L33
