### ISSUE TITLE
@ElementCollection

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#44]
I think "element" collections are a rubbish feature, and even worse here since we don't have lazy fetching, but people are going to bitch and moan if we don't provide this particular special way for them to shoot themselves in the foot.

Low priority.

**Comment by cambierr** [comment]
Hi @gavinking 

Could you ellaborate on 

> I think "element" collections are a rubbish feature, (...)

I'm not that experienced yet with JPA / Hibernate but I do not understand why you consider `@ElementCollection` that bad ? is there something I missed or don't know about that feature ? 

Thank you :)

**Comment by gavinking** [comment]
Well I just think it’s quite uncommon to have tables with two columns that don’t eventually wind up needing additional columns as the system evolves. (Even just a version or a time stamp.) At that point, you’ll need to refactor your Java code. So it’s simply a brittle and inflexible design.

(And the same goes for @ManyToMany, by the way.)

Furthermore, this two-column table doesn’t have a very well-defined primary key, which stinks from a data modeling perspective.

I’ve been telling people not to use this for >10 years, but of course people don’t listen.

**Comment by cambierr** [comment]
Interesting indeed, I agree with you on the blocked evolution path when using that ` @ElementCollection` feature.

Regarding the `@ManyToMany`, do you mean that you'd instead recommend a `@OneToMany` on the joining table instead of a direct `@ManyToMany` on the target table ?  for the same "evolution" reason I guess ? 

Thank you for your reply, that's very interesting

**Comment by gavinking** [comment]
Right, my advice is that you should usually have an entity for every table, and that most relationships should be bidirectional @ManyToOne/@OneToMany or @OneToOne.

**Comment by blafond** [comment]
Thought I'd take a look at this one, and run with it if it's not too hard?  Got a lot to learn here as well as ORM...

**Comment by DavideD** [comment]
The PR has been merged. Not sure why this is still open.
