### ISSUE TITLE
Proposal: switching to Vertx 4 already

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#440]
It seems Vert.x 4 is already in CR1, with a CR2 coming soon.

We're currently "stuck" on Vert.x v 3.x because we need to stay compatible with the Vert.x versions used in Quarkus; however:
 
- Quarkus plans to upgrade ASAP in 2021, expecting migration completion by March (but this very issue is meant to simplify that work)
- It seems we only need changes in a single class in Hibernate Reactive to be compatible with both
- It would be odd for the Hibernate Reactive community to impose a major upgrade of such a crucial dependency so close to our own 1.0 release.

So, I'd like us to explore being able to "baseline" on Vert.x 4 already: switch the dependency to v4, and document it as the recommended version, use it in examples - while applying some internal magic to keep runtime compatibility with v3 just for a bit longer, only to satisfy integration needs in Quarkus for as long as Quarkus doesn't upgrade as well.

I've already discussed this in chat with @DavideD and he thought this shouldn't be too hard - pending exploration.

This would also allow us to release with the new drivers (MSSQL support?), as I'm assuming we can keep them out of the Quarkus tree.

Sounds good? Asking @gavinking and @blafond in particular, as I already chatted with Davide.

I hope you like the idea, as it would take some barriers away from our velocity, and reduce the complexity of the Vertx upgrade in Quarkus - so helping them as well.

**Comment by gavinking** [comment]
I'm skeptical that this is worth the effort. March is really not far away and there are other things we could spend time on.

**Comment by Sanne** [comment]
I think it's a small investment and will reduce the total volume of work.

So unless you're highly preferring to release with Vertx 3 first, I'd like to give it a shot - we can abort if it gets unnecessarily complicated.

**Comment by gavinking** [comment]
Well I mean I gotta be honest I'm just not really keen on seeing reflection-based code added to the codebase if we're just going to throw it away in four months time when Vert.x 4 is released.

**Comment by Sanne** [comment]
oh I totally agree, but it's only a couple of methods and we'll get rid of them soon as well.

**Comment by Sanne** [comment]
Closing this as it turns out it was a bad idea: too complex.
