### ISSUE TITLE
replicate HHH-14271 (and HHH-14304?)

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#445]
@Sanne this one is for you.

I've noticed [this commit](https://github.com/hibernate/hibernate-orm/commit/81d526e4db283a92fd3c6adaa5c7efd9c877999d) and I suppose it's something that should be replicated in HR.

**Comment by gavinking** [comment]
HHH-14304 might also be relevant.

**Comment by Sanne** [comment]
Thanks, yes I've made a number of improvements to address a problem of high memory usage. I should be able to replicate them here.

**Comment by gavinking** [comment]
Great, perfect, thanks.

**Comment by Sanne** [comment]
I think I had already done this in 61989677a6dc189d41658b9641c47eb372c5fb41  - need to check if there's another update needed.

**Comment by Sanne** [comment]
right, nothing else is needed. FWIW, that's why I've made these `protected`:

 https://github.com/Sanne/hibernate-orm/blob/33123d267f64298f3f40e7c3671f7f15849831a9/hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java#L4366-L4376

**Comment by gavinking** [comment]
OK, great, thanks, sorry for the noise then.

**Comment by Sanne** [comment]
I'm glad you check :)
