### ISSUE TITLE
Test for correctly detecting dirty attributes of build time enhanced entities

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#447]
In Quarkus we favour build-time enhanced entities; we need better integration tests to cover this functionality.

There's a good template to follow in Hibernate ORM core's `DirtyTrackingTest`

**Comment by DavideD** [comment]
A list of issues that require this feature for testing (at the moment we are testing using the examples):
* https://github.com/hibernate/hibernate-reactive/issues/1386

I will try to keep this up to date

**Comment by DavideD** [comment]
I'm going to close this one for now.
We have an [integration test module that enables bytecode enhancements](https://github.com/hibernate/hibernate-reactive/tree/main/integration-tests/bytecode-enhancements-it) where we can add all the tests we need.
If we decide to work on something more sophisticated, we can create a dedicated issue.
