### ISSUE TITLE
@ManyToMany

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#45]
Like @ElementCollection #44, @ManyToMany is something I don't like much. But we'll have to add it eventually.

Also low priority.

**Comment by gavinking** [comment]
@DavideD You wanna try making a start on this one?

**Comment by DavideD** [comment]
I'm a bit busy working on the website at the moment. If you want to have take it I'm cool with that. Otherwise I will start it after.

**Comment by gavinking** [comment]
> I'm a bit busy working on the website at the moment. 

Ok, that's great, but can you do me a favor and share your work somewhere so we can work on it together?

> If you want to have take it I'm cool with that

No, let's concentrate on getting the website up

**Comment by indalaterre** [comment]
Any progress on this?

**Comment by DavideD** [comment]
We are working on the collection persisters for `@ElementCollection` and it affects this issue a bit as well.
We should be able to merge something soon and then we can focus on this issue

**Comment by indalaterre** [comment]
> We are working on the collection persisters for `@ElementCollection` and it affects this issue a bit as well.
> We should be able to merge something soon and then we can focus on this issue

Thank you very much. This is a critical feature for my team in order to full migrate to a reactive environment

**Comment by GeDep** [comment]
Thank you, this feature would help us too!

**Comment by brikenaKol** [comment]
This is a critical issue as we're not able to migrate into the reactive env.

It would help us, thank you!

**Comment by DavideD** [comment]
@blafond I've assigned this to me, so you can finish the missing bits around `@ElementCollection`. I'm waiting until we merged https://github.com/hibernate/hibernate-reactive/pull/531

**Comment by gavinking** [comment]
Folks, this should now be really very straightforward: all the infrastructure is there now, and `@ManyToMany` is really just a variation of `@ElementCollection`.

**Comment by gavinking** [comment]
If no-one is actively working on this, I will do it now. @DavideD?

**Comment by DavideD** [comment]
Yeah, sorry. I haven't start yet because some other things came out.
But I'm planning to do it on Monday

**Comment by DavideD** [comment]
If you want to take it, I'm fine with it.

**Comment by gavinking** [comment]
There's no work to do anyway: turns out it already works.
