### ISSUE TITLE
native SQL queries

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#46]
We need these.

**Comment by gavinking** [comment]
Uff, sorry @DavideD, I did not see that you had assigned this issue to yourself .... I hope you weren't actively working on it!

**Comment by DavideD** [comment]
It's OK, just keep in mind that Gail is working on the support for parameters.

**Comment by gavinking** [comment]
> just keep in mind that Gail is working on the support for parameters.

Yes, I was deliberately not touching that.
