### ISSUE TITLE
tests+dialect for MariaDB

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#471]
Testcontainers has [a module for MariaDB](https://www.testcontainers.org/modules/databases/mariadb/).

MariaDB is for the most part just a flavor of MySQL, and we support it via the Vert.x driver for MySQL. But I think that's not quite good enough. There are some (very) minor differences in the Hibernate `Dialect`, and so we should treat it as a separate case.

So we should set up tests to run on Maria, and make sure we detect it and use the correct dialect by default, instead of making the user specify it explicitly.

**Comment by DavideD** [comment]
@blafond this might be a good issue for you

**Comment by Sanne** [comment]
+1 for the MariaDB specific testing. But I don't understand why you mention the Dialect differences, won't we use the one from core ORM?

**Comment by gavinking** [comment]
yes we will, but we need to wire it into our stuff in HR.

**Comment by gavinking** [comment]
I’m going to work on this one if no one else is.

**Comment by gavinking** [comment]
So I have this basically done.

Except: Maria doesn't like how we drop schemas. And that's causing lots of errors in the test suite.

**Comment by gavinking** [comment]
Perhaps we just need to up the wait time.

**Comment by gavinking** [comment]
Also it doesn't like the `local temporary table` syntax.

**Comment by gavinking** [comment]
Done, and @DavideD has promised to add Maria to the CI build.
