### ISSUE TITLE
Race condition in ProxyConnection

### ISSUE THREAD

**Issue by snazy** [hibernate/hibernate-reactive#475]
`org.hibernate.reactive.pool.impl.ProxyConnection#withConnection` often triggers `IllegalStateException( "session is currently connecting to database" )` in an application using Quarkus/Mutiny.

Code snippet that triggers the exception:

```
class Foo {
    @Inject
    Mutiny.Session mutinySession;

    @Path("some-endpoint")
    @GET
    Uni<String> someEndpoint() {
        Uni<String> work = mutinySession.find(SomeEntity.class, someId)
                .flatMap(x -> x.toString());
        return mutinySession.withTransaction(tx -> work);
    }
}
```

The pseudo-code above is simplified a lot but shall illustrate the problem. We can neglect concurrency aspects here, because the problem is that both the `Mutiny.Session.find()` and the `Mutiny.session.withTransaction()` trigger `org.hibernate.reactive.pool.impl.ProxyConnection#withConnection`.

In many cases, the first call to `withConnection()` might trigger the creation of a new connection (sets `connected=true`) and the second call to `withTransaction()` hits the `connected == true && connection == null` case resulting in the `IllegalStateException`.

The problem is related to the state management in `withConnection()`:
* The first invocation sets `connected=true` and triggers `sqlClientPool.getConnection()`, which is likely async and can run for some time.
* Any other invocation (same thread or any other thread) of `withConnection()` that arrives before the `getConnection`-stage completed will see `connected==true && connection==null` and trigger the `IllegalStateException`

Another issue is that the fields used to track the state (`closed`, `connection` are not declared `volatile`/guarded by appropriate fences).

I'll come up with a patch in a few minutes.

**Comment by snazy** [comment]
Side note: the scenario in which the actual "work against the database" is constructed before a `withTransaction` is called is also the same scenario that happens with a `javax.interceptor.Interceptor` to encapsulate transactional requests using an `javax.interceptor.AroundInvoke`. For example:
```
@Interceptor
@Transactional
public class TransactionalInterceptor {
    @Inject
    Mutiny.Session mutinySession;

    @AroundInvoke
    Object aroundInvoke(InvocationContext ctx) throws Exception {
        if (ctx.getMethod().getReturnType() != Uni.class)
            throw new IllegalStateException("Only io.smallrye.mutiny.Uni is supported as a return type for methods annotaged with @Transactional");

        var result = ctx.proceed();

        var uni = (Uni<?>) result;
        var method = ctx.getMethod();
        var returnType = method.getReturnType();
        if (returnType == Uni.class) {
            result = mutinySession.withTransaction(tx -> uni)
                    .onFailure(CompositeException.class).transform(TransactionalInterceptor::unwrapCompositeException);
        }

        return result;
    }

    /**
     * Unwraps a {@link CompositeException} thrown from a
     * {@link Mutiny.Session#withTransaction(Function) Mutiny.Session.withTransaction()},
     * which prevents
     */
    private static Throwable unwrapCompositeException(Throwable t) {
        if (!(t instanceof CompositeException))
            return t;

        var c = t.getCause();
        for (var s : t.getSuppressed()) {
            if (s == c)
                continue;
            c.addSuppressed(s);
        }
        return c;
    }
}
```

**Comment by Sanne** [comment]
Issue on the Quarkus side:
 - https://github.com/quarkusio/quarkus/issues/13868

On the Hibernate Reactive side, we need two changes:

 1. ensure that all Session operations are run within a vertx context (and stay on the same context as the first one)
      1.A - simple: we could just check expectations: throw an exception if this isn't the case
      1.B - we could capture/initialize the context on first operation and then route any subsequent operation onto the same

 2. the vertx SQL `Pool` should not be shared across the whole SessionFactory as it's meant to be used by a single context only.

Perhaps we should split the work, especially as both points can be implemented in different ways.

Regarding point 1.A vs 1.B, the second seems nicer to allow easy use of Hibernate Reactive on a variety of runtimes, but possibly requires more exploration and understanding. We probably want to aim for `1.B`, but we might want to do `1.A` as milestone to get there.

Or perhaps have both options, so to allow integrators to test having done a proper integration with the vertx pools, as I can see how Quarkus might want to do this responsibility.

cc/ @gavinking @DavideD please check if we're on the same page :)

**Comment by DavideD** [comment]
> Perhaps we should split the issue (and the work), especially as both points can be implemented in different ways.

+1
I think we could threat these as separate issues.

> Or perhaps have both options,

If we do both options it makes sense to me to start with 1.A.
Otherwise I think we try 1.B first. We might have a better idea about the complexity once we have changed some code.

**Comment by gavinking** [comment]
Yes, the thing about the thread pool is kinda separate from the thing about tracking vert.x context association.

I'm going to open a couple of smaller issues.

**Comment by gavinking** [comment]
I've opened #479, #481, and #480. @DavideD already opened #478.

**Comment by Sanne** [comment]
Thanks. I'll work on #481 myself starting tomorrow - need to manage an ORM release first.

(I'm assuming it's best handled by me as it requires changes across both this repository and the quarkus repository - but if someone is keen to do it instead I can step back into assistance mode)

**Comment by Sanne** [comment]
BTW Quarkus will release a `1.11.0.Beta1` this time around (normally doesn't do betas) so I hope we can take that train.

Exact date is not detfined yet: they'll wait a little for us as I believe this is important, but only if we don't take too long.

So let's be mindful of timing: better merge some progress on these than merge nothing while we strife for the ultimate solution.

**Comment by gavinking** [comment]
@Sanne can we close this now?

**Comment by Sanne** [comment]
yes let's close it.

Many thanks @snazy , the connection issue should be gone now, and latest Quarkus v 1.11 includes all necessary changes.

The only thing I'm not clear about yes is how far we've prevented problems with Panache Reactive, that will need some more investigation - but it's unrelated to this issue.

See also:
 - https://in.relation.to/2021/01/07/hibernate-reactive-beta2/

**Comment by snazy** [comment]
I updated my toy-project today to the latest versions of Quarkus + Hibernate-Reactive (both at the HEAD of the main branches) and it's still not really working / easy to use, because it requires users to either always use `Uni<T> Mutiny.Session.withTransaction(Function<Transaction, Uni<T>> work)` or the user's code must ensure that the code runs on a Vert.x event loop thread.

There are two things IMO that are missing in the API:

1. `Mutiny.Session.withTransaction` should support Mutiny's `Multi`.
2. API usages like the following snippet should just work - otherwise: what's the point of having e.g. `createNamedQuery` in `Mutiny.Session`, if it cannot be directly used.

Consider the following pseudo-REST-code running in Quarkus, which fails with an `AssertionError`: "This needs to be run on the Vert.x event loop" (see below).

The benefit of using a reactive API is IMO also that you can basically stream huge result sets to clients - in this case via a `Multi`. But Hibernate-Reactive's `withTransaction` does not support `Multi` as a return type, so users have to use `Uni`, which requires buffering the whole potentially huge response before it can be sent to the client.

```
@RequestScoped @Path("/some/api")
public class MyService {
  @Inject Mutiny.Session session;

  @GET @Path("retrieve")
  public Multi<SomeEntity> returnHugeResultSet() {
    // fails with AssertionError - "This needs to be run on the Vert.x event loop" (see below)
    return session.createNamedQuery("blah")
      .getResults()
      .map(SomeStuff::mapToEntity);
  }
}
```

```
Caused by: java.lang.AssertionError: This needs to be run on the Vert.x event loop
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.<init>(ReactiveSessionImpl.java:129)
	at org.hibernate.reactive.mutiny.impl.MutinySessionFactoryImpl.openSession(MutinySessionFactoryImpl.java:67)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer.createMutinySession(ReactiveSessionProducer.java:32)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.create(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.zig:259)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.create(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.zig:297)
	at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:68)
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:33)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.arc$delegate(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.zig:61)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.createNamedQuery(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.zig:1041)
```

**Comment by DavideD** [comment]
@gavinking did some work around streaming query results using Multi. You can see the discussion here: https://github.com/hibernate/hibernate-reactive/issues/153

In short, we haven't added it yet because, currently, even if the API would return a `Multi`, the logical behaviour would be the same of a `Uni<List>`. 

> Caused by: java.lang.AssertionError: This needs to be run on the Vert.x event loop

Isn't this error unrelated to the Multi, though? We are working on it and it's something that should be solved in the future.
Would it be possible to have a look at you toy-project?

**Comment by gavinking** [comment]
> `Mutiny.Session.withTransaction` should support Mutiny's `Multi`.

I'm not sure I fully understand what you're asking for here. Is it that you want `.withTransaction()` to be able to return a `Multi`?

If so, I agree that would be sorta nice, but it's a bit hard without being able to implement a `Functor` type in Java due to the lack of higher-order polymorphism.

But anyway, our APIs generally return `Uni<List>` (for a good reason, as mentioned) so I don't think it should be a major problem.

> API usages like the following snippet should just work

Ah, indeed, this is my fault. I'm an idiot and forgot to add calls to `uni()` to the `Query` interface (and `StatelessSession`). Well, its more that that PR was still just in draft form but then we forgot it wasn't finished and merged it.

I will open an issue.

**Comment by gavinking** [comment]
> I will open an issue.

See #520.

**Comment by snazy** [comment]
Ah, okay - GTK it's an oversight :)

The "issue" with `Multi` is that you can do a lot of "big things" with `Multi` without having to buffer huge results in memory (aka in a `Uni<List>`) before it can be returned. I'd agree, that it's mostly useful for read-only requests.
But being able to take a steam (-> Multi) of rows and convert each row into the target format (e.g. entry in a JSON result array or line in a CSV) on-the-fly is really neat.

**Comment by gavinking** [comment]
But the thing is that there's no actual good way to retrieve and process the data as a stream because the underlying database protocols just don't support it. Sure, you could have the Multi wrap a cursor but in reality a cursor is just multiple requests to the database, just like if you were using pagination.

**Comment by snazy** [comment]
True, but with a `Multi` you could do "at least" the conversion "on the fly" and return results to the client when they arrive (result-set-paging).

**Comment by gavinking** [comment]
And the other thing is that if you're using `Session` everything gets cached in memory *anyway*. At least if you use pagination you can `clear()` the session in between queries.

(Though in fairness this objection doesn't apply to `StatelessSession`.)

**Comment by Sanne** [comment]
@gavinking I just noticed that the folks of Panache Reactive decided that a Query returns a `Multi`.. I'm surprised.

**Comment by gavinking** [comment]
OK then it seems we need to have another discussion about that. @FroMage

**Comment by FroMage** [comment]
Errr… ok?

**Comment by Sanne** [comment]
I keep struglging to find this thread to continue the discussion, could we move it here?
 - https://github.com/hibernate/hibernate-reactive/issues/522
