### ISSUE TITLE
Create one SessionFactory per class in tests

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#487]
Not critical or urgent.

At the moment we open/close a session factory after each single test and therefore running the schema generation queries each time.

We could save some time creating the factory only once.
This requires:
* Add appropriate populateDb/cleanUpDb methods before and after each tests (if they are missing)
* Create the factory statically in the base class

Our build is already quite fast with some db but it might help with the slower ones.

**Comment by DavideD** [comment]
> Create the factory statically in the base class
Actually, we might be able to use a JUnit rule to inject the factory

**Comment by gavinking** [comment]
If you do this, make sure that you recreate the factory after any test failure. Otherwise, the failure of one test method would have a cascading effect on all the other tests in that class (because its data won't be cleaned up).
