### ISSUE TITLE
Example get stuck if there is a problem with the connection

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#497]
It can be tested by using wrong credentials for the connection.

The code will get stuck here (in [MutinyMain](https://github.com/hibernate/hibernate-reactive/blob/master/example/src/main/java/org/hibernate/example/reactive/MutinyMain.java#L51)): 
```
		// obtain a reactive session
		factory.withTransaction(
				// persist the Authors with their Books in a transaction
				(session, tx) -> session.persistAll(author1, author2)
		)
				// wait for it to finish
				.await().indefinitely();
```

As far as I know the exception  is propagated but the await continues indefinitely.

I guess we need to add proper exception management in both examples (MutinyMain and Main).

**Comment by Sanne** [comment]
@DavideD didn't we fix this? I might have failed to resolve the issue

**Comment by DavideD** [comment]
No, we fixed the error message but this is still happening

**Comment by Sanne** [comment]
oh, ok.  Could you work on this next then? Seems an annoying usability problem

**Comment by DavideD** [comment]
Yes, I will

**Comment by DavideD** [comment]
FIY: It seems this issue is related to the way we use the vertx `runOnContext` when there is an exception the Stage or Uni invoked never completes and the error is not propagated.

**Comment by DavideD** [comment]
Done
