### ISSUE TITLE
Read Write traffic split

### ISSUE THREAD

**Issue by cambierr** [hibernate/hibernate-reactive#501]
Hi,

I'm currently running a bunch of tests on this library and comparing it against r2dbc and one of my main concerns is that I don't find any way to split read & write traffic.

Do you guys have any suggestion on how to achieve this ? or at least one are I should pay more attention to ? My DB engine is postgres, if this can help in any way :)

**Comment by gavinking** [comment]
I don't quite know what you mean. "Split" in what sense?

**Comment by cambierr** [comment]
I mean having both a master and a slave postgres servers and being able to send non-transactional selects to the slave while the rest goes to the master, for instance

**Comment by gavinking** [comment]
Oh OK. Well you can always achieve it by having two session factories. On the other hand it should also be doable via some sort of [custom connection pool](https://github.com/hibernate/hibernate-reactive/blob/master/documentation/src/main/asciidoc/reference/introduction.adoc#custom-connection-management-and-multitenancy), though I have not tried.

**Comment by gavinking** [comment]
Hi, do you have any further comments on this issue?

**Comment by cambierr** [comment]
do this can be closed, I'm working on integrating it with spring-data for TX management then RO/RW traffic segregation based on TX readonlyness :)

**Comment by hrstoyanov** [comment]
@gavinking @cambierr 
I see this issue has been closed, but "read/write" split is an attractive feature, for example if you want use efficiently  (load-balance) an AWS Aurora Postgres 1 rw master/ N ro replicas cluster configuration.  I think Hibernate can offer something out of the box to help...

For reference, there was some [solution offered](https://stackoverflow.com/questions/25911359/how-to-split-read-only-and-read-write-transactions-with-jpa-and-hibernate)8 years old, but is too Spring-centric (how do I do this in Quarkus?)

Another option could be [Apache ShardingSphere](https://shardingsphere.apache.org/) which has this feature explicitly, but I have not tried it.

**Comment by gavinking** [comment]
Well OK, but I'm not sure how Hibernate is getting in the way of anyone who wants to do this. I have the impression that @cambierr, who reported this issue, was able to get it working.

I would need to know why what we have today doesn't work before I could possibly propose any "solution".
