### ISSUE TITLE
Upgrade to Vert.x 4

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#504]
Some progress already exists, let's create this issue to discuss progress.

@DavideD could you rebase the `vert.x-4` branch and upgrade it to latest vert.x 4?

Next, I want to start testing how the new `io.vertx.sqlclient.Pool` is more suitable for use among multiple threads, in particular from the context of blocking worker threads and executors using a dynamic number of threads.

**Comment by Sanne** [comment]
there's nothing left to dicuss here?

**Comment by DavideD** [comment]
Do we still need this logic in Vert.x 4? https://github.com/hibernate/hibernate-reactive/commit/63dbb027b8126d6ba878a6b22517d2f615ba3f7b
