### ISSUE TITLE
Performance: find an alternative to PostgreSQL's need for the Parameters helper

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#508]
The `Parameters` class is being used to convert SQL into PostgreSQL specific format, but this is being flagged as significant overhead during profiling. It gets highlighted both during CPU and during memory profiling.

A better solution should be investigated, or ideally have us generate the right syntax to begin with.

**Comment by gavinking** [comment]
> A better solution should be investigated, or ideally have us generate the right syntax to begin with.

I mean, we *really* tried to do this about a year ago, but frankly it turned out to be a real mess, and ultimately I just got fed up with it.

**Comment by gavinking** [comment]
What I'm saying is that it might not be worth fixing.

**Comment by gavinking** [comment]
(Though one thing worth trying might be to cache the translated strings in a `WeakHashMap`.)

**Comment by Sanne** [comment]
I'd prefer we customize the ORM's strategy for generating the SQL - let's generate it using the right syntax rather than patching it after? Especially as in that way it would end up into the existing caches.

**Comment by gavinking** [comment]
> I'd prefer we customize the ORM's strategy for generating the SQL 

There *soooo many* places that this touches, and so many classes we would need to extend and override things that sometimes aren't public that this is just a mighty pain. Trust me, I tried.

**Comment by DavideD** [comment]
> There soooo many places that this touches, and so many classes we would need to extend and override things that sometimes aren't public that this is just a mighty pain. Trust me, I tried.

I agree

But what about processing the sql as soon as it is generated?

For example overriding `AbstractEntityPersister#generateUpdateString` to something like:
```
	@Override
	public String generateUpdateString(boolean[] includeProperty, int j, boolean useRowId) {
		String sql = super.generateUpdateString( includeProperty, j, useRowId );
		return sql != null
				? Parameters.process( sql )
				: null;
	}
```

**Comment by gavinking** [comment]
Well, that's probably *better*, but it's still a lot of places, once you take into account all the variations of loaders and batch loaders, and off the top of my head I don't think it would help with queries (though perhaps there is an alternative solution for queries).

**Comment by DavideD** [comment]
Something is wrong. I will send a new one when I've fixed it

**Comment by DavideD** [comment]
Sorry, I closed the issue instead of the PR

**Comment by DavideD** [comment]
I have a working branch that seems to improve the performance. I will update the PR soon
