### ISSUE TITLE
UnsupportedOperationException on CI with MySql when credentials are wrong

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#511]
I've updated the test WrongCredentialsTest so that it runs for every datastore. It seems to work fine locally but when it runs on CI  with MySQL and the latest ORM Snapshot it throws an UnsupportedOperationException instead of the expected one:
```
java.lang.UnsupportedOperationException: Unsupported authentication method: sha256_password
```

I cannot replicate this issue locally and I'm not sure what causing it on CI.
This is the test class: 
https://github.com/DavideD/hibernate-reactive/blob/d131bb2b38662b3bc64ee88faae42a9c223e5a70/hibernate-reactive-core/src/test/java/org/hibernate/reactive/WrongCredentialsTest.java

On CI it seems to happen with the latest ORM snapshot but I don't think it's related.
Here's the failed workflow: https://github.com/hibernate/hibernate-reactive/runs/1687501809?check_suite_focus=true#step:5:314

See also: https://github.com/eclipse-vertx/vertx-sql-client/issues/1132

**Comment by blafond** [comment]
@DavideD So it seems that in the MySQL UnsupportedOperationException didn't occur on my PR's build  but it did fail because the credentials were `Invalid`.  I can expand the check in [WrongCredentialsTest.java](https://github.com/DavideD/hibernate-reactive/blob/d131bb2b38662b3bc64ee88faae42a9c223e5a70/hibernate-reactive-core/src/test/java/org/hibernate/reactive/WrongCredentialsTest.java) to include other DB credentials errors.

However, since this MySQL java exception doesn't occur on CI anymore, should we remove this test class?

**Comment by DavideD** [comment]
> So it seems that in the MySQL UnsupportedOperationException didn't occur on my PR's build but it did fail because the credentials were Invalid

Are you sure? It seems to me that the tests worked for MySQL and it didn't work for Db2 because it has a different error message.

> However, since this MySQL java exception doesn't occur on CI anymore, should we remove this test class?

No. This test set wrong credentials on purpose because we use it to check that the right exception appears to the user in those situations. It failed with MySQL because the exception was an `UnsupportedOperationException`, quite puzzling for a user to see something like that and then discover that it was a problem with the credentials.

This error was happening with ORM 5.5 SNAPSHOT that I've removed from the workflow.
So, we don't really know if it's gone. But I  suppose we don't care and we could close the issue and wait for somebody complains.

I would enable the existing test in master for Postgres and MySQL (it shouldn't require any change apart for the rule) and call it a day.
Actually, if you change the check to be Case insensitive, it will also work for CockroachDB.

**Comment by DavideD** [comment]
> I would enable the existing test in master for Postgres and MySQL (it shouldn't require any change apart for the rule) and call it a day.
> Actually, if you change the check to be Case insensitive, it will also work for CockroachDB.

Up to you

**Comment by DavideD** [comment]
Interesting... the error is back.
And it happens even on master: https://github.com/hibernate/hibernate-reactive/runs/2059115574?check_suite_focus=true

**Comment by blafond** [comment]
Was able to test MySQL locally and PR with fix was applied and CI built OK.

Subsequent CI build failed with `UnsupportedOperationException` again, so this is still intermittent.

For the time being, skipping MySQL with [PR](https://github.com/hibernate/hibernate-reactive/pull/658) and will not close this issue for the time being.

**Comment by DavideD** [comment]
Keeping the username and only change the password seemed to have worked
