### ISSUE TITLE
Performance: optimise access to active event listeners list

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#513]
This stack highlights a suboptimal access to the event listeners on the hot path:

```
void java.util.AbstractList.<init>()
void java.util.Arrays$ArrayList.<init>(Object[])
List java.util.Arrays.asList(Object[])
Iterable org.hibernate.event.service.internal.EventListenerGroupImpl.listeners()
Iterable org.hibernate.reactive.session.impl.ReactiveSessionImpl.eventListeners(EventType)
```

ReactiveSessionImpl should access the event listeners in some better way.

**Comment by gavinking** [comment]
@Sanne note Hibernate core already has an approach to optimizing this. We can just copy what is used there. I speculate that *you* might have written that original optimization in core, so you probably already understand it...

**Comment by Sanne** [comment]
yes that's my touch :)  I need to copy it

**Comment by gavinking** [comment]
@Sanne isn't this done now? We can close it, right?

**Comment by Sanne** [comment]
right! thanks
