### ISSUE TITLE
Return type of queries: Multi vs Uni<List>

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#522]
This is a complex question which has been debated in various places, let's try to keep notes here.

**Comment by Sanne** [comment]
An example problem: I'm trying to fix a demo which is using Panache Reactive to use transactions.

The gist of the task is trivial, for example for a by-id individual love we have:

    @GET
    @Path("/{id}")
    public Uni<Todo> getOne(@PathParam("id") Long id) {
        return Todo.<Todo>findById(id)
                .onItem().ifNull().failWith(() ->
                        new WebApplicationException("Todo with id of " + id + " does not exist.", Status.NOT_FOUND)
                )


Which becomes:


    return Panache.withTransaction(
                () -> Todo.<Todo>findById(id)
                    .onItem().ifNull().failWith(() ->
                        new WebApplicationException("Todo with id of " + id + " does not exist.", Status.NOT_FOUND)
                ));

But when a query is involved, the following method:


    @GET
    public Multi<Todo> getAll() {
        return Todo.streamAll(Sort.by("order"));
    }

Can NOT compile with a similar conversion by using `Panache.withTransaction` because `streamAll` is returning a Multi, while `withTransaction` is returning an `Uni`.
(And the original method exposed on the rest endpoint is a `Multi` as well)

No idea how to get out of this, but in general I feel that the presence of transactions, which we should enforce, makes the API to be centered around `Uni<List>` ?

**Comment by gavinking** [comment]
Alright then, so here's the reason to not do this:

1. The underlying database protocol simply doesn't support streaming results to the client. If you want to hold a result set open on the server (usually a bad idea) then you have to use a cursor which is just a different way to do pagination.
2. We could hide pagination behind a `Multi`, but it doesn't seem better.
3. In particular, if you use `Multi` to hide the details of pagination, you lose the ability to manage the size of the session cache using `Session.clear()`, which seems like something you would most likely need here.
4. We would have to overload `withTransaction()` and `withSession()` to handle `Multi` as well as `Uni`.

It seems to me that the desire for this feature is driven by the perception that `Multi` is sexy, rather than by deep consideration of whether it's actually in any way beneficial taking into account what the actual implementation would be.

**Comment by gavinking** [comment]
@Sanne I mean, you could just use `multi.collect().asList()` to convert the `Multi` back to a `Uni<List>`.

But of course it would be much more convenient to have a `Uni<List>` to begin with.

**Comment by Sanne** [comment]
@gavinking Right.

@FroMage @DavideD @cescoffier agree? We'll need to change the Panache API ?

**Comment by gavinking** [comment]
To clarify, there is one place where this might indeed make sense: in the `StatelessSession` API. But that's not what Panache is using.

**Comment by FroMage** [comment]
Yeah, I know it doesn't actually stream underneath because the driver deals with `List` and not streams. I think at the time I figured we got more useful methods from a `Multi<T>` than a `Uni<List<T>>` and that people wouldn't care that it was not actually streaming.

We could change it, but we'd probably have to change the mongodb-reactive one too.

**Comment by Sanne** [comment]
There are cases in which we could stream stuff from within the transactional context, into a local consumer/processor; e.g. using a cursor.

The problem I had with `Todo.streamAll(Sort.by("order"))` is easily addressed by using `Todo.findAll(Sort.by("order")).list()` instead; that allows me to easily return a Uni<List> from within the transaction scope.

So perhaps it's ok as this very limitation could be seen as a "nudge" to only use the Multi-flavoured methods _within_ the transaction block, so to not have expectations beyond the end of transaction?

**Comment by snazy** [comment]
Currently, hibernate-reactive wraps "plain, synchronous JDBC", but maybe there's a way to properly implement reactive result-sets in the future - thinking of Vert.x `SQLClient` here.

My impression is, that the Quarkus docs suggest `Multi` as the "better way" to return result-lists, so supporting at least a say "stupid Multi->Uni->Multi wrapper" here feels rather less error-prone for users.

`Mutiny.Query.getResults` already returns a `Multi<R>`. But `Mutiny.Session.withTransaction` doesn't support `Multi`. I see, that `Mutiny.Query.getResults` is just a wrapper around `Mutiny.Query.getResultList`, but it would be very convenient to have `withTransaction` support `Multi`. Converting back and forth between `Uni<List<R>>` and `Mutli<R>` is duplicated work - and can be easily done wrong (`Uni` is technically still just an `Uni` - think: Java generics).

Another thing I stumbled upon was that the `@Transactional` annotation doesn't work out of the box, so I wrote my own to remove the `withTransaction`-boilerplate. A transactional interceptor would look much simpler, if it wouldn't have to convert the `Multi` from the implementation to a `Uni<List>` for `withTransaction` and then back to a `Multi`.

I do see that the Session cache can become an issue, but I struggle to see how that is different between `Multi<R>` and `Uni<List>` for huge result sets.

**Comment by gavinking** [comment]
> Currently, hibernate-reactive wraps "plain, synchronous JDBC", but maybe there's a way to properly implement reactive result-sets in the future - thinking of Vert.x `SQLClient` here.
> 
> My impression is, that the Quarkus docs suggest `Multi` as the "better way" to return result-lists, so supporting at least a say "stupid Multi->Uni->Multi wrapper" here feels rather less error-prone for users.
> 
> `Mutiny.Query.getResults` already returns a `Multi<R>`. But `Mutiny.Session.withTransaction` doesn't support `Multi`. I see, that `Mutiny.Query.getResults` is just a wrapper around `Mutiny.Query.getResultList`, but it would be very convenient to have `withTransaction` support `Multi`. Converting back and forth between `Uni<List<R>>` and `Mutli<R>` is duplicated work - and can be easily done wrong (`Uni` is technically still just an `Uni` - think: Java generics).
> 
> Another thing I stumbled upon was that the `@Transactional` annotation doesn't work out of the box, so I wrote my own to remove the `withTransaction`-boilerplate. A transactional interceptor would look much simpler, if it wouldn't have to convert the `Multi` from the implementation to a `Uni<List>` for `withTransaction` and then back to a `Multi`.
> 
> I do see that the Session cache can become an issue, but I struggle to see how that is different between `Multi<R>` and `Uni<List>` for huge result sets.

WDYM? Hibernate Reactive never uses 

> Currently, hibernate-reactive wraps "plain, synchronous JDBC", but maybe there's a way to properly implement reactive result-sets in the future - thinking of Vert.x `SQLClient` here.

WDYM? HR never uses JDBC. It always uses the nonblocking Vert.x reactive client. 

But non-blocking doesn't mean streaming. The two things are very different.

> `Mutiny.Query.getResults` already returns a `Multi<R>`

Only in Panache, not in HR, and I'm arguing that's something we should change.

> I do see that the Session cache can become an issue, but I struggle to see how that is different between `Multi<R>` and `Uni<List>` for huge result sets.

Well it's different because if you're managing pagination via `Query.setFirstResult()`, you have the perfect opportunity to call `Session.clear()` after each page of results. Whereas if pagination is being done for you under the covers and hidden from you by the `Multi` interface, you wouldn't know the right moment to call it.

**Comment by Sanne** [comment]
> but it would be very convenient to have `withTransaction` support `Multi`

Sure it looks handy at first, but I suspect this would be a terrible abstraction? Atomicity of a transaction implies it can't be split, and as such the scope of a transaction is either terminated or not yet - so how can you expose this as a `Multi`?

Also the support for cursors beyond a transaction boundarie varies significantly across different DB implementations - so even entertaining the idea of a `Multi` API which could be used outside/beyond a transaction would be challenging. As Gavin mentioned it might be possible to entertain this idea for a StatelessSession, but currently I'm inclined to think that all use of (stateful) Sessions should require an active transaction.

**Comment by DavideD** [comment]
> > `Mutiny.Query.getResults` already returns a `Multi<R>`
> 
> Only in Panache, not in HR, and I'm arguing that's something we should change.

@gavinking What do you mean `Only in Panache`? We have this in HR as well: https://github.com/hibernate/hibernate-reactive/blob/master/hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java#L167

**Comment by gavinking** [comment]
Oh I see. But it's not actually meaningful, it's just a helper in case you need a `Multi` for some other reason.

**Comment by gavinking** [comment]
After today's discussion, I advocate that we (again) close this issue.

The seems to be that we really don't think this is useful at least given current RDBMS technology. And it might even be actually harmful.

**Comment by Sanne** [comment]
Ok. Does it mean Panache should change its API?

**Comment by gavinking** [comment]
> Ok. Does it mean Panache should change its API?

Well, *in my opinion*, yes.

**Comment by milgner** [comment]
I, too, was surprised a bit that I'm getting a `Uni<List<T>>` instead of a `Multi<T>` and found this issue. Now I'm confused what the difference in requirements is between streaming SQL query results via cursors as described in the Vert.x documentation and streaming to publish Hibernate query results into a `Multi`?

**Comment by cescoffier** [comment]
You can use a Cursor that would provide a _Multi semantic_. However, you need to be aware that you keep a connection and sometimes a transaction (depending on the db) open until the cursor is closed. That's a deliberate choice, and should not be the default.

**Comment by milgner** [comment]
Thank you for the explanation! I didn't consider that it might be related to the lifetime of the connection. But it's true that if one wouldn't consume the Multi, then it would lead to resource starvation.

**Comment by brice-laurencin** [comment]
Bumping here, as I think it's related.
So the repository method returns a `Uni<List<Item>>` but now I need to apply transformation and treatment on each item to construct the response to the client.
I think I understand that if I do `getItems().map` I work on the whole list and will not take advantage of the mutiny engine as everything will be very much synchronous inside the map (tell me if I'm wrong, I'm very new to this).

Is there a way to go from the `Uni<List<Item>>` to a `Multi<Item>` where I would apply transformations as needed?

Thanks.

**Comment by DavideD** [comment]
You can convert a `Uni<List<Item>>` to `Multi<Item>` with:
```
return query.getResultList()
                // Convert the Uni<List<Item> into a Multi<Item>
		.onItem().transformToMulti( Multi.createFrom()::iterable )
```
