### ISSUE TITLE
Test lazy fetching of @ElementCollection

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#551]
Follows: #44 
So far we only have tests for the eager case but we need to check that it also work with `Session#fetch`.

**Comment by gavinking** [comment]
We _do_ need this, but guys, we don't need a massive suite of 20 tests for it, OK, all we need is to spend 10 minutes writing a test that checks that a collection marked `LAZY`:

1. isn't fetched when we retrieve it's owner, and then 
2. *is* fetched after calling `fetch()` on it, and that
3. `join fetch` works in HQL.

That should be a really quick task.

**Comment by gavinking** [comment]
I've confirmed that lazy fetching *doesn't* work, and I'm fixing it.
