### ISSUE TITLE
Test property about mapping of null Embeddables

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#552]
See https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#_misc_options

The property is `hibernate.create_empty_composites.enabled`:
Hibernate ORM returns `null` for an embeddable having all fields set to `null`. This property change the behaviour and 
return an instance with all the field set to null.

I expect this to work already, but a test would be nice.

**Comment by blafond** [comment]
is it enough to convert the tests here to run in reactive?

[EmptyCompositeCollectionKeyEagerTest.java](https://github.com/hibernate/hibernate-orm/blob/5eedda9a467fef44d924f64203023b2345b8415f/hibernate-core/src/test/java/org/hibernate/test/component/empty/EmptyCompositeCollectionKeyEagerTest.java)

**Comment by DavideD** [comment]
In this case we don't care about this:
```
		private Set<String> names;
```

I'm not sure about that test, but what we need to check are these 3 cases:
1. Embeddable field in entity
2. Embeddable in Embeddable
3. Embeddable in collection

By embeddable, I mean a class. Primitives won't be affected by this property.
An example could be:

```
Entity {
   Parent  parent;

    @ElementCollection
    List<Parent> others;   // This might be unecessary, I haven't checked the code  related to that property
}

@Embeddable
Parent {
    Child field1;
    String field2;
 
    @ElementCollection
    List<Child> adresses;
}

@Embeddable
Child {
      String field1 
      String field2
}
```

At first glance, I think a mapping like this, should cover all the cases.

**Comment by blafond** [comment]
k. thx

**Comment by blafond** [comment]
I've committed a test class and it seems to verify that null entities/columns do not prevent embeddable collection from being defined and accessible.

NOTE:  adding the  ```others``` ELementCollection in the  @ElementCollection ends up throwing the following exception
```@OneToMany, @ManyToMany or @ElementCollection cannot be used inside an @Embeddable that is also contained within an @ElementCollection: org.hibernate.reactive.EmptyCompositeCollectionKeyTest$Family.relatives.collection&&element.children```

Is this an expected limitation?

**Comment by DavideD** [comment]
Yes, that's normal. You cannot have an `@ElementCollection` collection where the element contain another `@ElementCollection`.
What I meant was:
```
private List<Child> relatives;   // This might be unecessary, I haven't checked the code  related to that property
```

**Comment by DavideD** [comment]
Here's an article that explains what's going on:
https://blog.eyallupu.com/2010/06/hibernate-exception-simultaneously.html

**Comment by blafond** [comment]
thx.   learned a little more.  change to `Set<>` worked.
