### ISSUE TITLE
[Db2] Setting Query#setFirstResults or Query#setMaxResults causes exception

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#560]
I've discovered this while working at #556 
This is probably a bug in the Vert.x SQL Db2 client: https://github.com/eclipse-vertx/vertx-sql-client/issues/887

```
java.lang.IllegalStateException: Found unknown codepoint: 0x215f / 8543
```

We have already tests for this situation but they are disabled for Db2: See [FilterWithPaginationTest](https://github.com/hibernate/hibernate-reactive/blob/master/hibernate-reactive-core/src/test/java/org/hibernate/reactive/FilterWithPaginationTest.java)

**Comment by gbadner** [comment]
This test still fails using 4.0.4-SNAPSHOT and 4.1.0-SNAPSHOT.
