### ISSUE TITLE
non-primary key associations

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#565]
Looks like we don't have the ability to load an association via a unique key other then the primary key.

We need a reactive version of `UniqueKeyLoadable`.

**Comment by gavinking** [comment]
Perhaps we should document this as a limitation.

**Comment by DavideD** [comment]
Could you write down an example of a mapping affected by this, please?

**Comment by gavinking** [comment]
Whenever you have `@JoinColumn` that refers to something other than the primary key, I suppose. Not sure, I have not tested it.

**Comment by DavideD** [comment]
OK, thanks

**Comment by gavinking** [comment]
So I made great progress on this last night, but it's going to have some impact on hibernate-core, and I'm still trying to evaluate exactly how big or small I should try to make that impact. Because the related code in core is not really very well-designed to begin with.

**Comment by gavinking** [comment]
So it seems to be working.

But I need to propose the changes to ORM before we can do anything here.

**Comment by gavinking** [comment]
> I need to propose the changes to ORM

FTR, see https://github.com/hibernate/hibernate-orm/pull/3733
