### ISSUE TITLE
Move to JBoss Logging annotations

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#571]
We can use `HR` as code and for the list of ids this should do:

* Core: 1-1000
* PostgreSQL: 1101-1200
* MySQL: 1201-1300
* MariaDB: 1301-1400
* Db2: 1401-1500
* CockroachDB: 1501-1600
* Sql Server: 1601-1700

and so on...

We need to match the dependency version in Quarkus.

**Comment by Sanne** [comment]
no let's please not upgrade before Quarkus upgraded.

+1 to get a code assigned. `HR` ?

**Comment by DavideD** [comment]
I don't mind `HR`... but it sounds too short?

**Comment by DavideD** [comment]
> I don't mind `HR`... but it sounds too short?

Never mind, I think `HR` is  fine
