### ISSUE TITLE
Exception: SessionFactory configured for multi-tenancy, but no tenant identifier specified

### ISSUE THREAD

**Issue by anyfon** [hibernate/hibernate-reactive#572]
When I use `SessionFactory.withSession()` and set the tenantID param, but no defined the property `hibernate.tenant_identifier_resolver` (CurrentTenantIdentifierResolver.class) in the PersistenceUnit, I have
```
org.hibernate.HibernateException: SessionFactory configured for multi-tenancy, but no tenant identifier specified
``` 
I use a custom class, that extended from DefaultSqlClientPool.class and method getTenantPool is overrided,  which return a getPool() for tests. Why do i get this exception?

**Comment by DavideD** [comment]
From the Hibernate ORM documentation: [19.4.2. CurrentTenantIdentifierResolver](https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#multitenacy-hibernate-CurrentTenantIdentifierResolver):
>
> org.hibernate.context.spi.CurrentTenantIdentifierResolver is a contract for Hibernate to be able to resolve what the application considers the current tenant identifier. The implementation to use can be either passed directly to Configuration via its setCurrentTenantIdentifierResolver method, or be specified via the hibernate.tenant_identifier_resolver setting.
>
> There are two situations where CurrentTenantIdentifierResolver is used:
>
> The first situation is when the application is using the org.hibernate.context.spi.CurrentSessionContext feature in conjunction with multitenancy. In the case of the current-session feature, Hibernate will need to open a session if it cannot find an existing one in scope. However, when a session is opened in a multitenant environment, the tenant identifier has to be specified. This is where the CurrentTenantIdentifierResolver comes into play; Hibernate will consult the implementation you provide to determine the tenant identifier to use when opening the session. In this case, it is required that a CurrentTenantIdentifierResolver is supplied.
>
> The other situation is when you do not want to explicitly specify the tenant identifier all the time. If a CurrentTenantIdentifierResolver has been specified, Hibernate will use it to determine the default tenant identifier to use when opening the session.
>
> Additionally, if the CurrentTenantIdentifierResolver implementation returns true for its validateExistingCurrentSessions method, Hibernate will make sure any existing sessions that are found in scope have a matching tenant identifier. This capability is only pertinent when the CurrentTenantIdentifierResolver is used in current-session settings.

**Comment by DavideD** [comment]
I hope this answer your question.

**Comment by DavideD** [comment]
I'm going to close this issue because I think I've answered your question, but feel free to comment more if have other doubts.

Thanks
