### ISSUE TITLE
Upgrade to Mutiny 0.14.0

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#578]
I've checked it and it's straight-forward, but opening an issue as I'd prefer to defer this slightly.

Quarkus PR is here: - https://github.com/quarkusio/quarkus/pull/15120

N.B. it's aiming at Quarkus 1.13, not the 1.12 which is being finalized these days. So in case HR were to need another release meant for `1.12` let's keep that option open.

**Comment by Sanne** [comment]
P.S. Mutiny 0.14.0 improves performance significantly.

**Comment by gavinking** [comment]
@Sanne can we go ahead with this now?

The Quarkus PR was already merged so I don't see how that's blocking us. We have no reason to be on an older version of Mutiny.

**Comment by Sanne** [comment]
Would be best to wait a couple more days. The Quarkus PR which was merged is targeting `master` branch, which is the follow-up release `1.13` (not the "current" one, as `1.12` isn't out yet). If we just wait a little longer then 1.12 will be out.

We could of course just ignore this and go ahead full steam for Quarkus 1.13, but in case something urgent pops up that we need to have in 1.12 then we'd need multiple branches of HR, which I prefer to avoid at this stage.

**Comment by gavinking** [comment]
OK, sure.
