### ISSUE TITLE
We need to be able to run a test on multiple databases

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#61]
Maybe it's early for this but we need to figure out a way to run the same tests on multiple dbs.
SImilar to what we have in OGM.

As a note, I wouldn't like to use the same approach we used for OGM. I find it too magical. I would be happy to have a separate module to use as TCK and keep the tests separated from the core (when necessary).

**Comment by aguibert** [comment]
Perhaps we could follow the pattern that vertx-sql-client uses which is to have a TCK package that have abstract classes containing the test logic like so: https://github.com/eclipse-vertx/vertx-sql-client/tree/master/vertx-sql-client/src/test/java/io/vertx/sqlclient/tck
and then each DB has to extend the abstract class and override the basic boostrapping bit.

So the overall project layout might look like this:
- hibernate-rx-core/ (has only basic unit tests that don't involve a DB, and has abstract TCK tests)
- integration-tests/core-postgresql
- integratoin-tests/core-mysql
- etc...

This also follows a similar pattern that we use in Quarkus for having separate integration test projects: https://github.com/quarkusio/quarkus/tree/master/integration-tests

**Comment by DavideD** [comment]
Thanks, seems helpful.
I haven't checked the links yet but
I agree that at some point we will have to organize the project in a similar way.

> hibernate-rx-core/ (has only basic unit tests that don't involve a DB, and has abstract TCK tests)

I'm not sure, but it might not be enough. For example, in core we might have several tests running HQL queries and I would like to make sure that they work on all the datastores. I don't want  to extend several classes in each module. The only thing that would change in the tests is the driver and it would be nice to find some simple way to do that.

We have something similar in OGM and it's not that bad. You have to `register` the new database and then all the tests get executed on it. There was something I didn't like about it (I cannot remember what it is right now) but once you add the new database correctly, you can just add the tests in core and they will get executed on all the selected dbs.

**Comment by aguibert** [comment]
That does sound like a nice mechanism, please leave a pointer to it here once you find it @DavideD. The tradeoff I think we should be mindful of is doing something "too magical" as you described in the OP. In general for tests I try to optimize for ease of maintainability (thinking about others needing to understand it too) over ease of writing the tests.

**Comment by gavinking** [comment]
The question is whether we truly have a hard requirement to test all our functionality across multiple platforms. I would have thought that we're happy to trust Hibernate ORM to shield us from differences between databases, and as long as we have some basic smoke tests for the other DBs, we don't really need to aggressively test *everything* on all of them.

But whatever, I'm certainly not *against* being able to run all the tests against all the databases.

**Comment by aguibert** [comment]
I think it would be good to test on all DBs because, while Hibernate itself is battle-tested, the Vertx drivers we are building on top of are not necessarily. Especially in the case of the DB2 and MSSQL drivers -- both are very new and Hibernate-rx is the first "real world" usage they are getting. We are writing as many tests as we can in the driver layer, but we'll never be able to match the stability of the traditional JDBC drivers this early on. So I think it's in the best interests of hibernate-rx to run its own tests on the code paths it will be driving.

**Comment by gavinking** [comment]
That's a good point.

**Comment by aguibert** [comment]
Now that I'm looking into pulling in the DB2 module, I think it would be a good time to restructure our testing so we can easily re-run all tests with different DBs.

## Proposal

Have one set of test source, but the DB used is control by an envvar/system property (e.g. `-Ddb=MySQL`). When running things locally, you can easily swap between DBs by changing that flag.
When running in CI, we will want the ability to cover all DBs, so we'd simply add more jobs that re-run the same test module with different sysprop flags like this:
```yaml
job1:
  name: PostgreSQL
  run: ./gradlew :hibernate-rx-core:test -Ddb=Postgresql
job2:
  name: MySQL
  run: ./gradlew :hibernate-rx-core:test -Ddb=MySQL
job3:
  name: DB2
  run: ./gradlew :hibernate-rx-core:test -Ddb=DB2
etc...
```

There may be tests that are only valid for some DBs, or not valid on others. For this we can use JUnit assumptions to bail out of the tests early if those assumptions are not met:
```java
@Test 
public void testDB2OnlyThing() {
  assumeTrue(DBConfiguration.is(DBKind.DB2));
  // rest of test...
}
```
and the inverse:
```java
@Test 
public void testThatIsNotValidForPostgresql() {
  assumeFalse(DBConfiguration.is(DBKind.PostgreSQL));
  // rest of test...
}
```

@gavinking @DavideD WDYT?

**Comment by gavinking** [comment]
If it can be done without slowing me down when I'm running the tests quickly inside my IDE, I don't mind.

(But I'm super-anal about this shit. Slow test suites make development almost impossible.)

**Comment by DavideD** [comment]
Sounds good to me.

I don't think it's going to be that slow in the beginning. But even so, I'm sure we can find ways to make it faster.

**Comment by aguibert** [comment]
I'll try to do it in the most transparent way possible. There may be some extra bumps (from CI builds failing more often) but we need the extra coverage since we are getting close to first release.

**Comment by aguibert** [comment]
@gavinking @DavideD I've put out a proposed PR #150 which is pretty minimally invasive. Basically everything will continue to run with PG by default, but you can specify an extra option (`-Pdb=DB2`) to set a different DB type. I don't expect we will ever run the full matrix of all tests with all DBs locally, but instead we'll let CI do that and then have an easy way to replicate that in case things do fail with non-default DBs.

**Comment by DavideD** [comment]
> I don't expect we will ever run the full matrix of all tests with all DBs locally

I actually run them on all the dbs at the moment, quite regularly. CI is usually slower than my machine and if I make a change that will affect potentially all the dbs I don't want to wait for it.
And I don't want to have to remember to set all the profiles.

Would it be possible to set up a job that will test on all the available databases?  Otherwise we have to update the build on CI every time we add a new DB (and we could potentially forget).

(I made a similar comment on the PR but I guess it's better to discuss it here)

**Comment by gavinking** [comment]
> Basically everything will continue to run with PG by default

So it looks like with this change there's a tradeoff: I get to be able to run *everything* on MySQL and DB2 if I want, but by default I don't run *anything* on them. 

Mmm. I mean, it makes sense even though I did kinda like how currently I just had one test that tested the only MySQL-specific feature, and it ran all the time.

OTOH it was a pain that the DB2 test also ran all the time, since I don't have DB2 on my machine.

So sure.

**Comment by gavinking** [comment]
This is done, isn't it. Can I close it?

**Comment by gavinking** [comment]
Certainly seems to be working to me.

Thanks, @aguibert, this is great.
