### ISSUE TITLE
Error when using `InheritanceType#JOINED` with Identity id generation

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#611]
This seems a bug to me but maybe it needs some additional annotations?
If that's the case we should throw a better error message.
Right now it seems that the required sequence is not created on the db.

Mapping example:
```
	@Entity
	@Inheritance(strategy = InheritanceType.JOINED)
	class GeneratedWithIdentityParent {
		@Id
		@GeneratedValue(strategy = GenerationType.IDENTITY)
		public Long id;

		public String firstname;
	}

	@Entity
	class GeneratedWithIdentity extends GeneratedWithIdentityParent {
		public String updatedBy;
	}
```
Causes on insert:
```
Caused by: io.vertx.pgclient.PgException: relation "generatedpropertyjoinedtabletest$generatedwithidentity_id_seq" does not exist
```

When this is fixed we also have to enable the test for generated properties in [GeneratedPropertyJoinedTableTest](https://github.com/hibernate/hibernate-reactive/blob/3cbde407dc8d88820c5ba0328a880c4d8b6ca69e/hibernate-reactive-core/src/test/java/org/hibernate/reactive/GeneratedPropertyJoinedTableTest.java#L54)

**Comment by DavideD** [comment]
I would say that this should be in 1.0 CR
But I haven't look how complex it is

**Comment by gavinking** [comment]
It seems to me like identity id generation doesn't make a *whole* lotta sense with multi-table inheritance strategies, but perhaps Hibernate allows it, I don't remember.

**Comment by DavideD** [comment]
Yes, that mapping works in ORM. It doesn't work when using `TABLE_PER_CLASS`.

**Comment by gavinking** [comment]
OK fine. Then we should at least investigate and see what's going on.

**Comment by DavideD** [comment]
If you try it with `TABLE_PER_CLASS`  you get a `MappingException`.

**Comment by gavinking** [comment]
I will look at this later on.

**Comment by gavinking** [comment]
Fixed.

**Comment by gavinking** [comment]
Wait, it fixed the example shown above, but not the test in `GeneratedPropertyJoinedTableTest`. Hrmph.

**Comment by gavinking** [comment]
It's fine. Test enabled.
