### ISSUE TITLE
verticle example

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#660]
We desperately need an example program showing a verticle calling Mutiny streams with HR.

Because users have *no clue* how to do this.

@cescoffier might need your help with this

**Comment by cescoffier** [comment]
Are you referring to Vert.x Verticle?

**Comment by gavinking** [comment]
Yeah, I mean a verticle started in a main method that delegates to Mutiny streams.

**Comment by gavinking** [comment]
So this has now been done here: <https://github.com/vertx-howtos/hibernate-reactive-howto> by @jponge, so I guess I can close this one.
