### ISSUE TITLE
JUnit 5

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#661]
I was wondering if there is any particular reason for not moving to JUnit 5.

I'm asking because I suspect it will make it easier to work on these other issues:
- #648 Create a common schema for testing #648
- #487 Create the SessionFactory only once per test class

Because it uses a new Extension model.

**Comment by DavideD** [comment]
@gavinking WDYT?

**Comment by gavinking** [comment]
🤷 I have no opinion.
