### ISSUE TITLE
test failure on cockroach

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#675]
We just had a CI failure here <https://github.com/hibernate/hibernate-reactive/runs/2139105014>

`UnionSubclassInheritanceTest.testQueryUpdateWithParameters()` failed on cockroach.

**Comment by gavinking** [comment]
Well, doesn't happen locally :-/

**Comment by DavideD** [comment]
I think this was probably a temporary issue with CI. It seems it's working now
