### ISSUE TITLE
Upgrade spotless gradle plugin to the latest version

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#692]

**Comment by DavideD** [comment]
https://github.com/hibernate/hibernate-reactive/blob/main/build.gradle#L6

**Comment by blafond** [comment]
@DavideD can I assume that **latest** means latest?  i.e. 7.0.0

asking only because we're at 4.0.1 now

**Comment by DavideD** [comment]
`7.0.0`?
I think this is the latest: https://plugins.gradle.org/plugin/com.diffplug.spotless

But you have to check that it works. With the license and the other couple of checks we use it for

**Comment by DavideD** [comment]
This is a plugin that we only use for the build, so we don't have to be as conservative  with it as we are for other dependencies. It's not like it is a requirement to use the hibernate-reactive
