### ISSUE TITLE
MultipleContextTest fails on CI

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#696]
This test checks that we throw the right exception when session run in the wrong `VertxContext`.

I cannot figure out why it doesn't fail on CI.

This is the test: [MultipleContextTest#persistWithStage](https://github.com/hibernate/hibernate-reactive/blob/0daa409116f89daaf18082ca13dfb853a468835c/hibernate-reactive-core/src/test/java/org/hibernate/reactive/MultipleContextTest.java#L60)

We also need to add tests for the Stateless session (kinda related to #1023)

**Comment by blafond** [comment]
FWIW

When I run locally with standard out all 4 tests (Stage & Mutiny) log:

```
STANDARD_ERROR
    [2021-06-03 15:36:17] WARNING io.vertx.core.impl.VertxImpl 
                               You're already on a Vert.x context, are you sure you want to create a new Vertx instance?
```

**Comment by gavinking** [comment]
Interesting. We need to figure out why.

**Comment by DavideD** [comment]
> Which I assume would be expected

Yes, that's exactly what the test is supposed to do.

**Comment by DavideD** [comment]
I suppose we should also check the stateless session, though

**Comment by DavideD** [comment]
Our assertions don't actually check the contexts but the threads. On CI the test run in the same thread and so the exception is not thrown as expected even if the context associated with the session is different than the execution context.

**Comment by DavideD** [comment]
I think we can close this issue, the problem has been solved.
