### ISSUE TITLE
Re-enable tests for Db2

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#697]
Because of [a bug in the Vert.x SQL client](https://github.com/eclipse-vertx/vertx-sql-client/issues/920)

This is the commit that disables the tests: https://github.com/hibernate/hibernate-reactive/commit/d76bb7217e5580d1e387506ca332406bf3ec7768

It should work once we upgrade to Vert.x SQL client 4.1.0

**Comment by gbadner** [comment]
I've confirmed that after reverting [d76bb72](https://github.com/hibernate/hibernate-reactive/commit/d76bb7217e5580d1e387506ca332406bf3ec7768) locally, and running tests with Vert.x 4.1.0-SNAPHOT, all tests pass using DB2.

**Comment by gavinking** [comment]
Ah, nice, thanks.

**Comment by gavinking** [comment]
Note that this issue affects both `EagerOneToOneAssociationTest` and `EagerElementCollectionForBasicTypeListTest`. (And possibly two others.)

**Comment by gavinking** [comment]
Note also that this appears to be the underlying cause of #739.
