### ISSUE TITLE
Create workflow for testing the latest Vert.x SQL client snapshots

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#698]
See https://github.com/DavideD/hibernate-reactive/pull/13

**Comment by gbadner** [comment]
@gavinking, I'm unclear about what is expected for this task. I have not worked on github workflows before so I have some newby questions about how to move forward.

I am currently working on a [branch](https://github.com/gbadner/hibernate-reactive/tree/698-vertx4.1) off of main.

I've cherry-picked @tsegismont's  [commit](https://github.com/tsegismont/hibernate-reactive/commit/a6abbc14b96031c7cdc175ba4ff4443ea99f5cc0) so Vert.x snapshots can be enabled.

In order for the workflow to use Vert.x 4.1.0-SNAPSHOT, should `vertxVersion` be changed to 4.1.0-SNAPSHOT in build.gradle, or should I set `matrix.vertx-version` to 4.1.0-SNAPSHOT in [tracking-vertx-4.build.yml](https://github.com/hibernate/hibernate-reactive/blob/main/.github/workflows/tracking-vertx-4.build.yml) itself?

I know I need to add `-PenableSonatypeOpenSourceSnapshotsRep` to the `gradle` command.

I plan to add what is needed for db2 to the workflow. I will wait until a good point to sync up with Thomas' work for SQL Server before adding it to the workflow.

**Comment by gavinking** [comment]
> I'm unclear about what is expected for this task.

@gbadner well, me too.

You need to ask @DavideD, who I heard a rumor is on vacation or something.

**Comment by gbadner** [comment]
I was trying not to bother Davide. I'll just wing it for now.

**Comment by DavideD** [comment]
Yes, that was the idea. Evaluate if we can start building with it and then
add it it to the build on CI. If you check the Hibernate ORM one, we do the
same thing with Orm 5.4 and 5.5. Vertex should do a similar thing:
https://github.com/hibernate/hibernate-reactive/blob/380a4e3888e8340042e552e4ad8ec1db232f21a1/.github/workflows/tracking-orm-5.build.yml#L25

But if it's too soon, we can wait. It might be still worth it to enable the
snapshots repository for testing the latest 4.0.0-SNAPSHOT

**Comment by gbadner** [comment]
@DavideD, thank you for that tip. I think I get it now!
