### ISSUE TITLE
Support for `@MapsId` and `@PrimaryKeyJoinColumn`

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#710]
We don't have any tests at the moment.

[See examples ](https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#identifiers-derived) in the Hibernate ORM documentation.

**Comment by DavideD** [comment]
I spoke too soon @blafond. Something goes wrong when testing with MariaDB

**Comment by blafond** [comment]
I just ran both new tests locally against MariaDB and they passed

**Comment by DavideD** [comment]
Something fails if you run the whole test suite. Not sure what. You can see an example on our CI: https://github.com/hibernate/hibernate-reactive/actions/runs/793361265

**Comment by DavideD** [comment]
It was the name of the table created conflicting with the same name used for other tests.
It works now

**Comment by blafond** [comment]
k.. thx
