### ISSUE TITLE
ReactiveConnection#close should return a `CompletionStage` 

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#716]
See the discussion on https://github.com/hibernate/hibernate-reactive/pull/715

**Comment by DavideD** [comment]
I think the main issue is that now `ReactiveSessionImpl` cannot extend `SessionImpl` if we change the method for the session as well

**Comment by gavinking** [comment]
> I think the main issue is that now `ReactiveSessionImpl` cannot extend `SessionImpl` if we change the method for the session as well

I don't think that's an issue at all. `ReactiveSessionImpl` would have a `reactiveClose()` method that would be called by `StageSessionImpl.close()` and `MutinySessionImpl.close()`.

**Comment by DavideD** [comment]
Merged
