### ISSUE TITLE
Upgrade gradle-nexus/publish-plugin to version 1.1.0

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#718]

**Comment by SivaTharun** [comment]
@DavideD i am a newbie to open source contribution, can i start working on this issue, also a little description would help.

**Comment by DavideD** [comment]
There is no additional description because it's really about changing the version number here: https://github.com/hibernate/hibernate-reactive/blob/6733bee4b328c0ee712e7e3857afcb1fdce09d84/build.gradle#L9

It should work without any other change but you won't be able to test it.
I still have to add a contributing guide, so, for now, make sure to include the issue number in the commit message.
I like to add it a[t the beginning following this forma](https://github.com/hibernate/hibernate-reactive/commit/9bba8e5ab9aa4928c8d648af9a62fa8ce94f0a49)t:
```
[#704] Update action name in workflow
```

I think is also a nice issue to start with: https://github.com/hibernate/hibernate-reactive/issues/669
You could take [this existing one](https://github.com/hibernate/hibernate-test-case-templates/tree/main/orm/hibernate-orm-5)  and convert it to use reactive. I think I would use gradle instead of maven though

**Comment by DavideD** [comment]
I will add a specific contributing guide next week, but you can have a look at [the one for Hibernate ORM](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md). In particular, we work using [Topic branches](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows#Topic-Branches): we expect you to create a branch with the fix on your repository and then send a PR that we can apply on the `main` branch of hibernate-reactive. Ideally, without having to rebase it. Let us know if you have some other questions. Thanks!

**Comment by SivaTharun** [comment]
Thanks @DavideD for the insights into the contribution guidelines, just had a question related to the version update, is there any integration test case, which i can refer to, check whether the version update is not breaking the current gradle build

**Comment by DavideD** [comment]
All the info about how to run the build is in the [readme](https://github.com/hibernate/hibernate-reactive#readme).
It's a good idea to become familiar on how to build the current project on `main` before starting to contribute.

Basically, make sure that it builds and passes all the tests for the default build with PostgreSQL. And maybe check if you can run the test suite on one of the other supported dbs.

**Comment by DavideD** [comment]
The only way to test this particular issue is by releasing and you don't have the permission to do it. But if the build doesn't fail and CI doesn't complain when you send the PR, I will try it. It;s going to be next week though

**Comment by DavideD** [comment]
Sorry `@SivaTharun`, we need this so I'm going to send a PR
