### ISSUE TITLE
Test error propagation

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#73]
Error propagation is delicate in this project. Everytime we use .handle( (r, e) -> {...}) we need to remember to propagate the error if it's not null or we loose it along the way.

I don't know how to test this, but one idea is to create a fake connector to a db that always throws exception for every operation and check in the unit test if the right exception is thrown.

**Comment by gavinking** [comment]
> Everytime we use `.handle( (r, e) -> {...})` we need to remember to propagate the error if it's not null or we lose it along the way.

Yup, this is a PITA.

**Comment by gavinking** [comment]
Actually I'm really bothered by the exception handling in `ReactiveSessionImpl`.

But I suppose it's all necessary for JPA compliance.

Still, it might be nice if `hibernate-core` exposed a bunch of exception translation methods like `convertPersistException()`, etc, that we could just call.

I think we should do that, actually.

**Comment by gavinking** [comment]
@DavideD I've actually done quite a lot of work on the error handling, over time, which is a lot simpler now, and the errors I see coming out of HR always look pretty reasonable to me.

So I'm not quite sure what specific tasks remain to be done on this issue. For now it looks a bit vague and aspirational.

Can we close it, or is there specific work you were planning to do?

**Comment by DavideD** [comment]
No, let's close this
