### ISSUE TITLE
Closing of Vert.x instance should be waited on

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#736]
We also need to patch `DefaultVertxInstance#stop()` to actually wait for the shutdown of the instance.

I'm assume we could "just" block in this case? But it would be nice to have a way to do it properly; maybe introducing a reactive flavour of `Startable` and `Stoppable` would make sense even for ORM blocking so to allow parallelising some setup/teardown operations.

**Comment by gavinking** [comment]
Blocking sounds fine to me for now.

Introducing new interfaces in ORM doesn't sound like the sort of thing we would do until 6.

**Comment by Sanne** [comment]
Agreed, blocking will do fine for now.

My second point is more like a question/suggestion: we could explore this in 6 - not sure if it's worth it.

**Comment by DavideD** [comment]
Merged!
Thanks
