### ISSUE TITLE
MS SQL: failure when creating local temporary table

### ISSUE THREAD

**Issue by tsegismont** [hibernate/hibernate-reactive#743]
Found the issue while running `UnionSubclassInheritanceTest` with MS SQL.

HR uses `ReactiveIdTableSupport` to generate SQL for creating local temporary table.

MS SQL expects local temporary table names to begin with a single hash sign:
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql#temporary-tables

**Comment by gavinking** [comment]
Yeah it's because we're using `ReactiveBulkIdStrategy` instead of the thing returned by `AbstractTransactSQLDialect.getDefaultMultiTableBulkIdStrategy()`. It should be easy enough to fix. Don't worry too much about this for now.

**Comment by gavinking** [comment]
@tsegismont it should be enough to change `ReactiveIdTableSupport. generateIdTableName ()` as follows:

```java
    @Override
    public String generateIdTableName(String baseName) {
        return (dialect instanceof SQLServerDialect ?  "#" : "ht_") + baseName;
    }
```

**Comment by tsegismont** [comment]
@gavinking thanks for the tip. I went with something slightly different (to keep the `ht_` prefix) and also had to change the `getCreateIdTableCommand` method.

See https://github.com/tsegismont/hibernate-reactive/commit/84caabcefb4eb1a47e7e0c2d931584038d162393

**Comment by gavinking** [comment]
> I went with something slightly different (to keep the `ht_` prefix) 

Well I believe if you check Hibernate ORM (which we try to align with), it drops the `ht_` prefix in the case of SQL Server, because the temporary tables have their own namespace.

**Comment by tsegismont** [comment]
@gavinking :+1: https://github.com/DavideD/hibernate-reactive/pull/13/commits/a52e8e3825dd360a3b3d267fed0b8ec0daed052f

**Comment by gavinking** [comment]
@tsegismont can we close this one?

**Comment by tsegismont** [comment]
I shared some changes in a [PR](https://github.com/DavideD/hibernate-reactive/pull/13) to @DavideD 's fork.

If these changes have been cherry-picked here then yes the issue can be closed.

**Comment by DavideD** [comment]
Thanks @tsegismont,  I will have a look at this today

**Comment by gavinking** [comment]
Thanks guys.
