### ISSUE TITLE
Multitenancy support

### ISSUE THREAD

**Issue by yaakov-berkovitch** [hibernate/hibernate-reactive#754]
Hi,

according to the documentation, to add support for multitenancy, the following must be done:
1. define your own implementation of ReactiveConnectionPool or extend DefaultSqlClientPool and override getTenantPool(String tenantId).
2. a class which implements CurrentTenantIdentifierResolver
3. multitenancy strategy: database or schema

So, regarding (1), as you recommend, I tried to extend the DefaultSqlClientPool and create a pool for each tenant.
It seems that I have a big misunderstanding. I need a pool per URI, and keep them into a map with the tenant-id as the key, so the getTenantPool will return the correct pool for the tenant.
But I cannot use the createPools(URI) to create the pool per tenant because the ThreadLocalPoolManager is not public, and so I have no access to this class.

I would very appreciate some lights how to do it.

Thanks.

**Comment by gavinking** [comment]
Errrm ... @Sanne?

This issue might have slipped through the cracks, since I worked on multitenancy, and then much later Sanne did the `ThreadLocalPoolManager`.

**Comment by Sanne** [comment]
I coincidentally just started looking at vertx 4.1 and its new pool, with the plan of removing our `ThreadLocalPoolManager` so I guess that will help.

To prevent such regressions we need to add a test covering Multitenancy though.

**Comment by gavinking** [comment]
Well, there _is_ a test (`ReactiveMultitenantTest`), but I guess it just doesn't touch whatever is causing _this_ problem.

**Comment by DavideD** [comment]
I will have a look

**Comment by yaakov-berkovitch** [comment]
I also looked at this test, but it is not testing multitenancy . The custom pool (as shown below) you implemented in your test is not creating different pool per tenant:
```
public class MySqlClientPool extends DefaultSqlClientPool {
    @Override
    protected Pool getTenantPool(String tenantId) {
        return getPool();
    }
}
```

**Comment by DavideD** [comment]
Yeah... It's a very simple test
