### ISSUE TITLE
Support R2DBC

### ISSUE THREAD

**Issue by OrangeDog** [hibernate/hibernate-reactive#76]
There's a project building a reactive alternative to JDBC: https://github.com/r2dbc

Supporting this could be valuable, as they currently have drivers for more than just postgres, and a standard API for reactive database stuff could be better cross-inspired.

**Comment by DavideD** [comment]
Sounds interesting. Would you like to give it a try?

**Comment by OrangeDog** [comment]
I'm afraid not. I just wanted to make sure you were aware of each other, as a (hopefully) future user.

**Comment by DavideD** [comment]
That's ok. Thanks for the heads up, we will get to it as soon as we can.

**Comment by aguibert** [comment]
I could possibly look into this one in a few weeks. I'll be doing some deeper investigation into R2DBC shortly and might have the cycles to connect the two projects together.

**Comment by DavideD** [comment]
Sounds great. Please, assign this to yourself when you start to work on it so that people can see that somebody is taking care of it. Unless somebody else wants to send a PR before you start to work on it :)

**Comment by gavinking** [comment]
@aguibert That would be great. It might actually be quite easy to support these drivers, since our dependency to Axle is really pretty localized.

**Comment by aguibert** [comment]
@gavinking  @DavideD Would you prefer to have this worked in sooner or later? On one hand it would be nice to get it integrated sooner so we can be mindful of the requirements of abstracting over both APIs from the start, but on the other hand it will slow us down a bit to need to create extra abstractions over both APIs as we iterate on the HibernateRX design itself

**Comment by DavideD** [comment]
I don't know, do we really need that much more abstraction to support it? Maybe you can have a quick look and let us know more about how hard it is going to be? (Unless you have already looked into it)

**Comment by gavinking** [comment]
> Would you prefer to have this worked in sooner or later?

I don't see it as something we need to have in the first release, but if it's straightforward, it would certainly be nice to have.

> I don't know, do we really need that much more abstraction to support it?

I doubt it. Interaction with the database is already pretty well encapsulated within just a couple of classes.

> it will slow us down a bit to need to create extra abstractions over both APIs as we iterate on the HibernateRX design itself

I don't imagine the impact will be enough to slow us down.

**Comment by gavinking** [comment]
Note that with #155 it is now in principle possible to integrate other reactive database drivers.

**Comment by gavinking** [comment]
I'm going to close this one now because in #154 I introduced an extension point that allows users to experiment with integrating alternative reactive database drivers. If someone actually gets motivated to do this, would could consider accepting a contribution, but we don't have time to work on this right now (that's really quite a lot of work in terms of testing, etc), and @OrangeDog says he doesn't have time to work on it either.

To be clear, I'm not ruling out OOTB support for other driver libs in future, just saying that we've already done what we have time for right now, and now there's nothing stopping other folks from playing with this for themselves.
