### ISSUE TITLE
Question: in which scenario io.vertx.core.VertxException: Transaction already completed may occurred ?

### ISSUE THREAD

**Issue by yaakov-berkovitch** [hibernate/hibernate-reactive#772]
Hi,

I have some logic to implement in the business layer, and this must be in a transactional scope. In the reactive flow, I have some logics that is implemented in methods that get the session as parameter.

For some reason,  in the reactive flow, after the first business logic method did its work (saveAll), then it looks that the transaction is not open anymore for the next operation.

The flow looks like:
```
        CompletionStage<List<Employee>> future = sessionFactory.withTransaction(
                (session, tx) -> saveAll(session, projects)
                                            .thenCompose(v -> {
                                                return saveAllEmployee(session, new HashSet<>(employees)) ;
                                            })
                                            .thenApply(v2 -> employees)
                    );
```
I will be happy to get some hint about such error, and if there is something wrong in the way I want to implement the business logic transactional flow.
Thanks

**Comment by DavideD** [comment]
What's happening in `saveAll`?

**Comment by yaakov-berkovitch** [comment]
```
    CompletionStage<List<Project>> saveAll(Stage.Session existingSession, Set<Project> entities) {
        CompletionStage<List<Project>> future = null;
        if (existingSession != null && existingSession.isOpen()) {
            future = existingSession
                    .persist(entities.toArray(new Project[entities.size()]))
                    .thenApply(v -> entities.stream().collect(Collectors.toList()))
                    .exceptionally(throwable -> {
                        throw new AssertionError("Error occurred - " + throwable.getMessage())
                    }) ;
        } else {
            future = sessionFactory.withTransaction(
                    (session, tx) -> session
                            .persist(entities.toArray(new Project[entities.size()]))
                            .thenApply(v -> entities.stream().collect(Collectors.toList()))
            ).exceptionally(throwable -> {
                throw new AssertionError("Error occurred - " + throwable.getMessage())
            });
        }
        return future ;
    }

```

**Comment by DavideD** [comment]
>  the transaction is not open anymore for the next operation

What makes you say that? Is there an exception? Something doesn't work?

**Comment by DavideD** [comment]
If you could create a small test case, it would be really helpful

**Comment by yaakov-berkovitch** [comment]
Forget it, the code i sent you works. What i tested was:
```
 CompletionStage<List<Employee>> future = sessionFactory.withTransaction(
                (session, tx) -> saveAll(session, projects)
                                            .thenApply(v -> {
                                                return saveAllEmployee(session, new HashSet<>(employees)) ;
                                            })
                                            .thenApply(v2 -> employees)
                    );
```
I just replaced the "thenApply"  by "thenCompose" and it works now.
Does it make sense for you?

**Comment by DavideD** [comment]
The `thenApply` will wrap the result of the `saveAllEmployee` in an additional `CompletionStage`. What's returning is a completed `CompletionStage<CompletionStage<>>`.
So the following `.thenApply(v2 -> employees)` will be applied immediately, even if `saveAllEmployee` hasn't been executed yet.
 This causes the `withTransaction` block to terminate and commit the transaction before `saveAllEmployee` has finished, making the transaction invalid when `saveAllEmployee` actually runs.

When you use `thenCompose` the operation are chained correctly, the way you'd expect.
The `.thenApply(v2 -> employees)` happens when the result of `saveAllEmployee` has completed.

I hope this helps.

**Comment by yaakov-berkovitch** [comment]
Thanks for the explanation, it gave me better understanding.
