### ISSUE TITLE
Upgrade ascii-doctor-plugin

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#822]
Latest version for 1.5.x is 1.5.12 at the moment.

The reason I'm creating a separate issue for this is that we need to compare the generated documentation to make sure that nothing critical as changed and it requires a bit more work than the other plugin.

Note that  [the actual latest of the plugin is 3.x](https://asciidoctor.github.io/asciidoctor-gradle-plugin/development-3.x/user-guide/): but it might require more changes to make it work and could potentially change how the documentation looks like (I haven't checked).

**Comment by blafond** [comment]
Upgrading to `1.5.8` works fine.  Generated docs looks identical.

Upgrading to `1.5.12' causes an exception which requires making `Version` class Serializable.  The impact of doing that pulls in an older 2.4.15 version of `org.codehaus.groovy` which is known for throwing a WARNING exception.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/blafond/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.4.15/74b7e0b99526c569e3a59cb84dbcc6204d601ee6/groovy-2.4.15.jar) to method java.lang.Object.finalize()
```
This exception prevents the asciidoc HTML to be generated.  Javadocs are unaffected.

Might be more productive to move to asciidoctor 3.x version.

Shelving this for the time being.
