### ISSUE TITLE
Handle Null parameters the right way with Vert.x SQL client

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#843]
Based [on this comment](https://github.com/eclipse-vertx/vertx-sql-client/pull/970#issuecomment-854460745),  it seems that we are  not handling nul values the right way:.

See https://vertx.io/docs/vertx-mssql-client/java/#_handling_null

**Comment by gavinking** [comment]
Yeah, but frankly I'm a bit confused by that comment. I mean, none of the other Vert.x clients seem to require this, nor do they have that section in the documentation. So why is this a requirement of the SQL Server client?

**Comment by DavideD** [comment]
I have no idea yet. This issue is mostly a reminder for us (mostly me maybe) to check what's going on.

**Comment by gavinking** [comment]
Well if it's necessary I guess it's easy enough to stick an object with a JDBC type code in the map of bound parameter values, and then translate it to whatever the SQL Server client needs.

**Comment by gavinking** [comment]
On it.
