### ISSUE TITLE
Is Oracle support on the roadmap?

### ISSUE THREAD

**Issue by sloppycoder** [hibernate/hibernate-reactive#847]
Oracle is still very popular in large companies and it would encourage the adoption if such support is available

**Comment by DavideD** [comment]
This is probably a question for the Vert.x SQL client team: https://github.com/eclipse-vertx/vertx-sql-client

In theory, it's possible to use a different reactive driver with Hibernate Reactive but we haven't tried it yet and, for now at least, we are adding support to new databases as soon as a new Vert.x SQL client is available.

**Comment by gavinking** [comment]
Now that SQL Server is almost done, I guess Oracle would be next on the list.
