### ISSUE TITLE
Should we support the vertx-jdbc-client?

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#849]
See https://vertx.io/docs/vertx-jdbc-client/java/

This way people could use a JDBC Driver to connect to databases without a Vert.x SQL client.

@gavinking?

**Comment by gavinking** [comment]
Um, I mean, if it's *easy* then I don't see why not, but its not something I would spend *time* on.

Is the API actually that similar? I had assumed it was different.

**Comment by DavideD** [comment]
I haven't checked but it extends the same Pool class as the others.

**Comment by DavideD** [comment]
I will have a better look when I have some time

**Comment by gavinking** [comment]
> I haven't checked but it extends the same `Pool` class as the others.

Oh OK, I did not know that. Well, then, it might be easy.

(Dunno if we can do it without confusing users who already assume that Hibernate Reactive is based on JDBC though.)

**Comment by DavideD** [comment]
Yeah, that would be the drawback

**Comment by DavideD** [comment]
Alright, let's close it.
