### ISSUE TITLE
Update to Hibernate ORM 5.5.2.Final

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#859]
The `5.5.2.Final` release is being processed, should be available on build mirrors in ~1h.

I believe we had a couple of optimisations which were on hold waiting for it?

**Comment by Sanne** [comment]
I meant `5.5.1.Final`, amended.

**Comment by DavideD** [comment]
> I believe we had a couple of optimisations which were on hold waiting for it?

Not sure what you mean

**Comment by Sanne** [comment]
> I meant `5.5.1.Final`, amended.

well... I did the same mistake when actually releasing, so it's labelled `5.5.2.Final`

**Comment by gavinking** [comment]
> Not sure what you mean

Nope

**Comment by Sanne** [comment]
ok no new optimisations then :+1:  I guess I got confused with the previous upgrade round.

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/issues/859
