### ISSUE TITLE
Support JsonObject as a built-in type

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#869]
We have a test in `BasicTypesForSelectedDBTest` testing that we can save a `JsonObject` via a `UserType`.
But a user needs to create a Json user type and apply it to the column:
```
		@Type(type = "org.hibernate.reactive.types.Json")
		@Column(columnDefinition = "json")
		private JsonObject jsonObj;
```

Should we provide support for this type out of the box?

**Comment by gavinking** [comment]
You're saying you would like this as a built-in type?

It's a good idea, I suppose.

**Comment by gavinking** [comment]
(I'm not sure what you meant by a "type converter".)

**Comment by DavideD** [comment]
> You're saying you would like this as a built-in type?

Yes, exactly

**Comment by DavideD** [comment]
I've renamed the issue

**Comment by gavinking** [comment]
working on it
