### ISSUE TITLE
Value of `hibernate.jdbc.batch_size` is ignored

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#877]
It doesn't matter what we set it to, it's always 0.

The reason is that in `SessionFactoryOptionsBuilder`, [there's a check to see if the database supports batching](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java#L428) and it always return false. It happens because we don't extract the info from the database

**Comment by gavinking** [comment]
What I don't understand about this is that I thought we had tests that test statement batching.

**Comment by DavideD** [comment]
Well... those tests check that if you set the property everything works fine, they don't really test that it is actually using batching (as far as I remember).

**Comment by gavinking** [comment]
Well, you're right, `BatchingConnection` is never instantiated. So whatever tests we have (`ReactiveSessionTest`, FTR) certainly don't test that batching _actually happens_. (Which is not actually surprising, since it's not observable via the API.)

But what is weird is that I certainly did test that `BatchingConnection` works when I first wrote it.

**Comment by gavinking** [comment]
> Well... those tests check that if you set the property everything works fine, they don't really test that it is actually using batching (as far as I remember).

Yes, right, that's what I just realized.

**Comment by DavideD** [comment]
Will this be solved by [this other issue](https://github.com/hibernate/hibernate-reactive/issues/536)?

**Comment by gavinking** [comment]
Rrrrm, not automatically, but in principle perhaps perhaps that's one option for where we could hook in. I'm not sure.

**Comment by gavinking** [comment]
@DavideD isn't there a simpler temporary solution we could use?

Like, do it in `ReactiveSessionFactoryBuilderService.createSessionFactoryBuilder()` and `ReactiveEntityManagerFactoryBuilder.build()`, for example?
