### ISSUE TITLE
UTCTest.testLocalDateTime

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#885]
This test fails on Postgres on my machine, and hangs the whole test suit on MySQL.

**Comment by gavinking** [comment]
Seems to me that this test fails if your database is not set up in UTC.

**Comment by DavideD** [comment]
Weird though, I've never seen this test fail (on CI and on my machine). Are you doing something different than the usual build?

**Comment by gavinking** [comment]
Nope, same thing as always.

**Comment by gavinking** [comment]
Sure it's nothing to do with #857?

**Comment by DavideD** [comment]
That wouldn't explain why it does work "everywhere else".
Are you travelling? Did you change time zone?

**Comment by gavinking** [comment]
Nope, and nope.

**Comment by gavinking** [comment]
Ahem. I just realized that when I reported this issue, I wrote the wrong method name. This is of course the same problem reported in #901. Closing as dupe.
