### ISSUE TITLE
Stateless update doesn't work

### ISSUE THREAD

**Issue by Xset-s** [hibernate/hibernate-reactive#886]
I have two sample entities:

SampleEntity:

```java
@Entity
@Table(name = "sample_entities")
public class SampleEntity implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;

    @Column(name = "sample_field")
    public String sampleField;
}
```

SampleJoinEntity:

```java
@Entity
@Table(name = "sample_join_entities")
public class SampleJoinEntity implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sample_entity_id", referencedColumnName = "id")
    public SampleEntity sampleEntity;
}
```

and after that I would like to execute this code:

```java
<!-- SessionFactory -->
Mutiny.SessionFactory sessionFactory =
        createEntityManagerFactory( "mysql" )
                .unwrap(Mutiny.SessionFactory.class);

<!-- Persist everything -->

// sampleEntity
SampleEntity sampleEntity = new SampleEntity();
sampleEntity.sampleField = "test";

sessionFactory.withTransaction((session, transaction) ->
        session.persist(sampleEntity)
).await().indefinitely();

// sampleJoinEntity
SampleJoinEntity sampleJoinEntity = new SampleJoinEntity();
sampleJoinEntity.sampleEntity = sampleEntity;

sessionFactory.withTransaction((session, transaction) ->
        session.persist(sampleJoinEntity)
).await().indefinitely();

<!-- Find just persisted entity again -->
Long targetId = sampleJoinEntity.id;

SampleJoinEntity sampleJoinEntityFromDatabase = sessionFactory.withTransaction((session, transaction) ->
        session.find(SampleJoinEntity.class, targetId)
                .call((entity) -> session.fetch(entity.sampleEntity))
).await().indefinitely();

<!--Change something and update it using stateless session-->
SampleEntity sampleEntityFromDatabase = sampleJoinEntityFromDatabase.sampleEntity;
sampleEntityFromDatabase.sampleField = "test";

// EXCEPTION IS HERE!
sessionFactory.withStatelessTransaction((session, transaction) ->
        session.update(sampleEntityFromDatabase)
).await().indefinitely();
```

as I understand stateless sessions are able to handle detached entities, but after executing this code (error happens during session.update, furthermore session.refresh or session.delete don't work either), I'm getting this exception:

```
Exception in thread "main" org.hibernate.MappingException: Unknown entity: database.entities.SampleEntity$HibernateProxy$2k2e2VER
```

Full stack: https://pastebin.com/3fj4yavw

# Configuration

```
<persistence xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
             version="2.0">

    <persistence-unit name="mysql">
        <provider>org.hibernate.reactive.provider.ReactivePersistenceProvider</provider>

        <class>database.entities.SampleEntity</class>
        <class>database.entities.SampleJoinEntity</class>

        <properties>

            <property name="javax.persistence.jdbc.url"
                      value="jdbc:mysql://localhost/sample"/>

            <property name="javax.persistence.jdbc.user"
                      value="root"/>

            <property name="javax.persistence.jdbc.password"
                      value="..."/>

            <property name="hibernate.connection.pool_size"
                      value="10"/>

            <property name="javax.persistence.schema-generation.database.action"
                      value="drop-and-create"/>

            <property name="hibernate.format_sql" value="true"/>

        </properties>

    </persistence-unit>

</persistence>
```

Hibernate-Reactive 1.0.0.CR7

**Comment by DavideD** [comment]
It seems you've found a bug. I've created a JBang alias for this issue:
```
jbang --fresh issue886@DavideD/jbang-rep
```
We are going to have a look at it tomorrow.

**Comment by DavideD** [comment]
@blafond Could you have a look at this, please?

**Comment by blafond** [comment]
@DavideD 

The [StatelessSessionImpl.getEntityPersister(...) ](https://github.com/hibernate/hibernate-orm/blob/834f125c07c6c1ed487c1f42b62a2c98b037addc/hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java#L494)method has 2 args:  `entityName` and `object`.  

In [ReactiveStatelessSessionImpl.reactiveUpdate(...)](https://github.com/hibernate/hibernate-reactive/blob/b4589436c366b8fcfa1cf8486d75a74e56bb19c0/hibernate-reactive-core/src/main/java/org/hibernate/reactive/session/impl/ReactiveStatelessSessionImpl.java#L220) we're setting the `entityName` to NULL.

The result is the stateless entity name ends up being a proxy'd name:  `Issue886$SampleEntity$HibernateProxy$CBbPx8Pn`. In debug, I can set the `entityName` to `Issue886$SampleEntity` and it returns the entity.

So  should we discover the name and set it (if we can) in ReactiveStatelessSessionImpl?

Or could this be an ORM issue?

**Comment by DavideD** [comment]
I don't know. You need to adapt the test for ORM and see what happens. I doubt this is a bug in ORM

**Comment by blafond** [comment]
@DavideD @gavinking 
I was able to reproduce this using ORM methods by adding a test to the jbang generated Issue886.java.  The exception is: 
```
Unknown entity: Issue886$SampleEntity$HibernateProxy$b6d1kZ8R
org.hibernate.MappingException: Unknown entity: Issue886$SampleEntity$HibernateProxy$b6d1kZ8R
	at org.hibernate.metamodel.internal.MetamodelImpl.entityPersister(MetamodelImpl.java:704)
	at org.hibernate.internal.StatelessSessionImpl.getEntityPersister(StatelessSessionImpl.java:494)
	at org.hibernate.internal.StatelessSessionImpl.update(StatelessSessionImpl.java:149)
	at org.hibernate.internal.StatelessSessionImpl.update(StatelessSessionImpl.java:143)
	at Issue886_ORM.testInsertAndSelectStateless(Issue886.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```
I searched the ORM tests and couldn't find any that mixes basic Session persistance with StatelessSession.update(...)

**Comment by gavinking** [comment]
So whatever it is that`ReactiveSessionImpl.reactiveFetch()` _does do_ that `ReactiveStatelessSessionImpl.reactiveFetch()` _doesn't do _is what we need to fix.

**Comment by gavinking** [comment]
Wait, sorry, no, what I just said doesn't quite make sense. The problem's not in `reactiveFetch()`, it's in `update()`.

Excuse me.

**Comment by blafond** [comment]
I created a jbang reproducer using ORM: `jbang --fresh --verbose Issue886WithORM@blafond/jbang-rep`

[Issue886WithORM.java](https://github.com/blafond/jbang-rep/blob/main/Issue886WithORM.java)

If it doesn't make sense to **fix** it in ORM, then we'll need to add logic to check if the entity is a proxy, then pass on an entity name without it, which should end up finding the entity in the MetamodelImpl.entityPersisterMap ?

**Comment by DavideD** [comment]
Did you check with the somebody from the ORM team?

**Comment by gavinking** [comment]
> If it doesn't make sense to fix it in ORM

Well we would need to add a `fetch()` method to `StatelessSession` in ORM. It probably *would* make sense, and I thought of it at the time, but it's a new feature.

**Comment by DavideD** [comment]
@Xset-s the problem you are having is because of this line:
```
SampleEntity sampleEntityFromDatabase = sampleJoinEntityFromDatabase.sampleEntity;
```
`sampleJoinEntityFromDatabase` is detached at this point, you would have a `LazyInitializationException` if you were using a getter.  I guess we could make it work but I'm not sure we should.

**Comment by gavinking** [comment]
@DavideD it's a stateless session. *All* instances are detached.

**Comment by DavideD** [comment]
> @DavideD it's a stateless session. _All_ instances are detached.

Right, sorry

**Comment by gavinking** [comment]
As soon as we get this issue sorted, I'm going to contribute `StatelessSession.fetch()` back to Hibernate 6. But I think we'd better finish this before doing that work.
