### ISSUE TITLE
SchemaMigrator/SchemaValidator - add tests for corner cases

### ISSUE THREAD

**Issue by gbadner** [hibernate/hibernate-reactive#936]
There are some corner cases that are covered by ORM tests. They should be migrated to Reactive to make sure they work properly.

Here are some ORM `SchemaMigrator` tests that should be reviewed for possible inclusion in Hibernate Reactive:
```
SchemaUpdateTableBackedSequenceTest
CrossSchemaForeignKeyGenerationTest
UniqueConstraintDropTest
MySQLDropConstraintThrowsExceptionTest
SchemaMigrationTargetScriptCreationTest
SchemaMigrationToOutputScriptTest     -> @RequiresDialect(H2Dialect.class)
SchemaMigratorHaltOnErrorTest        -> skip DB2 & Derby
SchemaUpdateProceedOnErrorTest
SchemaUpdateSchemaNameTest     ->  @RequiresDialect(MySQL5Dialect.class)
```
Here are some ORM `SchemaValidator` tests that should be reviewed for possible inclusion in Hibernate Reactive:
```
LongVarcharValidationTest
NumericValidationTest
GroupedSchemaValidatorImplTest       -> @RequiresDialect(H2Dialect.class)
IndividuallySchemaValidatorImplConnectionTest       -> @RequiresDialect(H2Dialect.class)
IndividuallySchemaValidatorImplTest       -> @RequiresDialect(H2Dialect.class)
SchemaToolTransactionHandlingTest
```

**Comment by gbadner** [comment]
I don't think they all need to be added. I'll take a look at these and see which ones we need.

**Comment by DavideD** [comment]
I think we cover these cases, we will fix errors when they present themselves
