### ISSUE TITLE
"find" vs "get"

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#938]
on `Mutiny.Session` I need to use:

    <T> Uni<T> find(Class<T> entityClass, Object id);

while on `Mutiny.StatelessSession` we have:

    <T> Uni<T> get(Class<T> entityClass, Object id);

There doesn't seem to be a well defined semantic difference. Should we name them consistently?

**Comment by Sanne** [comment]
OK sure there's difference between using a `Session` and `StatelessSession`, but I was now refactoring one of our benchmarks, and changing some operations to use the stateless session: in this case beyond changing the type of the signature (expected) I also had to change all the `find` invocations to `get` to solve compile errors.

I found that really surprising, you don't think it was?

**Comment by gavinking** [comment]
I mean, to me, if they had the same name, that would create the expectation that they're semantically identical, which I don't think they are: I mean, at the most basic level they return a detached object, not a managed object. And there are other differences (off the top of my head: no calls to interceptors).

**Comment by Sanne** [comment]
Ok if it's intentional I'll close this, thanks for explaining.

I'm not entirely sure about this being a good idea though; I can never remember which one I have to look for when developing. In this case I was refactoring some code to take advantage of the better efficiency of stateless session, and this resulted in making me change more code than I'd hope for.
