### ISSUE TITLE
Upgrade Vert.x to 4.1.4

### ISSUE THREAD

**Issue by gbadner** [hibernate/hibernate-reactive#955]
SchemaMigrator/SchemaValidator  "grouped" strategy will not work properly using DB2 or SQL Server  until the following issues are fixed:

For SQL Server: https://github.com/eclipse-vertx/vertx-sql-client/issues/1032 (fixed targeting 4.1.4)
Required by https://github.com/hibernate/hibernate-reactive/issues/912

For DB2: https://github.com/eclipse-vertx/vertx-sql-client/issues/1033
Required by https://github.com/hibernate/hibernate-reactive/issues/911

**Comment by DavideD** [comment]
@gbadner I'm going to merge this one soon. Do you think you can send a pr #911 and #912 rebased on top of this fix?

**Comment by DavideD** [comment]
(if you have something working already)

**Comment by gbadner** [comment]
@DavideD, yes, I'm going to push a draft that depends on this PR.
