### ISSUE TITLE
Blobs/Clobs

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#96]
We need to discuss Blobs and Clobs. Apparently the vert.x driver has some level of support for them (mapping them to `Buffer`), though I don't know any details, and it's not discussed at all in the documentation.

Now, Blob/Clob support has always been a bit uncomfortable in regular Hibernate, but it occurs to me that perhaps it might be a little more natural in this model.

I wonder who knows more details about how this works in the Vert.x driver.

**Comment by emmanuelbernard** [comment]
@vietj is the right person.

**Comment by gavinking** [comment]
> Now, Blob/Clob support has always been a bit uncomfortable in regular Hibernate, but it occurs to me that perhaps it might be a little more natural in this model.

Apparently not, AFAICS.
