### ISSUE TITLE
Feature Request: Add kotlin coroutines support

### ISSUE THREAD

**Issue by andreas-eberle** [hibernate/hibernate-reactive#99]
Hi guys,

I'm really looking forward to beeing able to use non blocking hibernate! 

Would you also consider adding kotlin coroutines support? Probably as a second library, something like hibernate-ktx or so. I think this would be an awesome addition.

**Comment by gavinking** [comment]
I imagine that support for coroutines is something that can be layered over this work as a façade. Anyway, it would *definitely* be a separate component. 


And in the interest of keeping our issue tracker clean of issues that don't refer to actual code I'm actually going to push to this git repo, I'm going to close this issue.

(That doesn't imply anything at all about whether or not we'll have coroutines at some stage in the future.)

**Comment by andreas-eberle** [comment]
I still think this should be tracked somewhere to not be forgotten. And since there is no other repo yet, I think this project would be the best place to have this issue. However, If you know a better place, I'd be happy to open an issue there.

**Comment by gavinking** [comment]
Look, this is just a personal preference, coming from past projects like Hibernate and Ceylon where we've been absolutely overwhelmed as a result of taking a very "welcoming" approach with issue reports, to the point that the issue tracker becomes a lot less useful as a way of seeing what are the important things we need to be working on.

The issue tracker shouldn't be a list of "nice-but-vague ideas that nobody's working on nor plans to work on". (Nor should it even really be anybody's personal TODO list, though of course we all use it that way from time to time.) It's a system for managing bugs and well-defined roadmap features for the particular git repo to which it belongs.

Now, I know people get super-offended when I close their pet issues, and so in the past I've tended to try to avoid giving offence by leaving stuff open. And then we end up with a system full of thousands of open zombie issues that nobody is working on and nobody plans to work on, with less than 100 being things that we're *ever* going to actually work on.

So this time I want to do things differently and be aggressive about closing stuff.

If, on the other hand, you're volunteering to start work on this issue right now, I'm happy to reopen it for you.

Please don't be offended.
