### ISSUE TITLE
Class Persistence.createEntityManagerFactory() used in Verticle produced new Vertx Instance

### ISSUE THREAD

**Issue by codingxu97** [hibernate/hibernate-reactive#995]
Here is my code:
![Code](https://user-images.githubusercontent.com/35094351/137104886-5a6033df-d80c-4748-a0ad-261a7c3988b7.png)
Console printed the following message:
![Warn](https://user-images.githubusercontent.com/35094351/137104442-91f68733-4e05-436a-8fb9-e929541896eb.png)

**Comment by DavideD** [comment]
I'm working on the documentation of this part, but basically you need to register the already existing Vert.x instance when you create the SessionFactory.

I've explained how to do it [as an answer to this question](https://github.com/hibernate/hibernate-reactive/issues/750#issuecomment-839611870).

 Let me know if that helps. I will add that section to the documentation before the final release

**Comment by DavideD** [comment]
Please, it would be better if you could attach the code as preformatted text and not using images.

You don't show what the class `MyProvider` looks like so I cannot tell you why it doesn't work.
Also, you don't need to access the VertxInstance service.

These are the two approaches:

1. Create the factory programmatically:
    ````
    public Stage.SessionFactory createFactory() {
        Configuration configuration = new Configuration();
        // ... set the values for your configuration 

       StandardServiceRegistryBuilder builder = new ReactiveServiceRegistryBuilder()
                                // Add the service that returns the current Vert.x instance
				.addService( VertxInstance.class, (VertxInstance) () -> vertx )
				.applySettings( configuration.getProperties() );

       StandardServiceRegistry registry = builder.build();
       return configuration.buildSessionFactory( registry )
           .unwrap( Stage.SessionFactory.class );
    }
    ````
2.  Your class could implement the interface `VertxInstace`:
     ````
     package com.fospot.trader.hibernatetest;

     public class MainVerticle implements VertxInstance { }
     ````
     Now your file `/META-INF/services/org.hibernate.reactive.vertx.VertxInstance` will contain:

     `com.fospot.trader.hibernatetest.MainVerticle`

If none of these work, a test case that I can run will make it easier for me to help.

**Comment by Mr-CodingXu** [comment]
Thanks a lot!

On your suggestion,it still create new one.Maybe I should give up using Persistence.

But,is there any possibility that Hibernate reactive could support to use Persistence in Verticle in the future?It seems that ```persistence.xml``` was more general than ```hibernate.cfg.xml``` IMHO.
